// Code generated by tui generate. DO NOT EDIT.
// Source: component.gsx

package workspace_connect

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/clientconnect"
	cockpitui "github.com/swobuforge/swobu/internal/cockpit/ui"
)

type FlowTextView = cockpitui.FlowTextView

func FlowText(text string) *FlowTextView {
	return cockpitui.FlowText(text)
}

func EndpointRow(d *Disclosure) *cockpitui.SelectableRow {
	return cockpitui.NewSelectableRow("workspace-connect:endpoint:"+d.Target.WorkspaceSlug(), "endpoint", d.Target.WorkspaceURL(), d.endpointAction(), d.toggleEndpoint)
}

func OtherClientsRow(d *Disclosure) *cockpitui.SelectableRow {
	return d.rowEscape(cockpitui.NewSelectableRow("workspace-connect:other-clients", "Other clients", "", "setup ↵", d.openManualSetup))
}

func OtherClientsHeaderRow(d *Disclosure) *cockpitui.SelectableRow {
	return d.rowEscape(cockpitui.NewSelectableRow("workspace-connect:other-clients", "Other clients", "", "close ↵", d.closeChildScope))
}

func ClientHeaderRow(d *Disclosure, id clientconnect.ClientID, name string) *cockpitui.SelectableRow {
	return d.rowEscape(cockpitui.NewSelectableRow("workspace-connect:client:"+string(id), name, "", "close ↵", d.closeChildScope))
}

func PlanActionRow(d *Disclosure, obs clientObservation) *cockpitui.SelectableRow {
	if obs.Applying {
		return d.rowEscape(cockpitui.NewSelectableRow("workspace-connect:apply:"+string(obs.Client.ID), "config", shortLoci(obs.Plan.ConfigPaths), "configuring…", nil))
	}
	action := "apply ↵"
	if obs.Plan.RequiresReplace() {
		action = "replace ↵"
	}
	return d.rowEscape(cockpitui.NewSelectableRow("workspace-connect:apply:"+string(obs.Client.ID), "config", shortLoci(obs.Plan.ConfigPaths), action, func() { d.applyPlan(obs.Client.ID) }))
}

func ManualCopyRow(d *Disclosure, key, label, displayValue, copyValue string, allowFileFallback bool) *cockpitui.SelectableRow {
	return d.rowEscape(cockpitui.NewSelectableRow("workspace-connect:manual:"+key, label, displayValue, d.copyAction(key), func() { d.copyItem(key, copyValue, allowFileFallback) }))
}

func ClientPicker(d *Disclosure) *cockpitui.SearchPicker {
	observations := d.Observations.Get()
	options := make([]cockpitui.SearchOption, 0, len(observations))
	for _, obs := range observations {
		action := "checking…"
		switch obs.Kind {
		case observationMatch:
			action = "configured ↵"
		case observationNeedsChange:
			action = "configure ↵"
			if obs.Applying {
				action = "configuring…"
			}
		case observationFailed:
			action = "retry ↵"
		}
		options = append(options, cockpitui.SearchOption{ID: string(obs.Client.ID), Label: obs.Client.Name, Keywords: []string{string(obs.Client.ID)}, Action: action})
	}
	picker := cockpitui.NewSearchPicker("workspace-connect:clients", "client", options, func(sel cockpitui.Selection) { d.chooseClient(clientconnect.ClientID(sel.Value)) }, func() { d.Back() })
	return picker
}

type FindingClientsRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FindingClientsRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FindingClientsRowView) GetRoot() *tui.Element { return v.Root }

func (v *FindingClientsRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FindingClientsRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FindingClientsRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FindingClientsRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FindingClientsRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FindingClientsRowView)(nil)

var _ tui.AppUnbinder = (*FindingClientsRowView)(nil)

var _ tui.PropsUpdater = (*FindingClientsRowView)(nil)

func FindingClientsRow() *FindingClientsRowView {
	var view FindingClientsRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("finding installed clients…"),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("wait"),
		tui.WithWidth(14),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = FindingClientsRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type CheckingConfigRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *CheckingConfigRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *CheckingConfigRowView) GetRoot() *tui.Element { return v.Root }

func (v *CheckingConfigRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *CheckingConfigRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *CheckingConfigRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *CheckingConfigRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*CheckingConfigRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*CheckingConfigRowView)(nil)

var _ tui.AppUnbinder = (*CheckingConfigRowView)(nil)

var _ tui.PropsUpdater = (*CheckingConfigRowView)(nil)

func CheckingConfigRow() *CheckingConfigRowView {
	var view CheckingConfigRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("checking configuration…"),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("wait"),
		tui.WithWidth(14),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = CheckingConfigRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type InertRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *InertRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *InertRowView) GetRoot() *tui.Element { return v.Root }

func (v *InertRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *InertRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *InertRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *InertRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*InertRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*InertRowView)(nil)

var _ tui.AppUnbinder = (*InertRowView)(nil)

var _ tui.PropsUpdater = (*InertRowView)(nil)

func InertRow(label string, value string) *InertRowView {
	var view InertRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(label),
		tui.WithWidth(18),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(value),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = InertRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type PlanChangeRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *PlanChangeRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *PlanChangeRowView) GetRoot() *tui.Element { return v.Root }

func (v *PlanChangeRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *PlanChangeRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *PlanChangeRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *PlanChangeRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*PlanChangeRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*PlanChangeRowView)(nil)

var _ tui.AppUnbinder = (*PlanChangeRowView)(nil)

var _ tui.PropsUpdater = (*PlanChangeRowView)(nil)

func PlanChangeRow(field string, value string) *PlanChangeRowView {
	var view PlanChangeRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_2 := tui.New(
		tui.WithWidth(2),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(field),
		tui.WithWidth(18),
	)
	__tui_1.AddChild(__tui_3)
	__tui_0.AddChild(__tui_1)
	__tui_4 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithPaddingTRBL(0, 0, 0, 20),
	)
	__tui_5 := FlowText(value)
	__tui_4.AddChild(__tui_5.Root)
	__tui_0.AddChild(__tui_4)

	watchers = append(watchers, __tui_5.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_5).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_5).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = PlanChangeRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type DetailRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *DetailRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *DetailRowView) GetRoot() *tui.Element { return v.Root }

func (v *DetailRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *DetailRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *DetailRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *DetailRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*DetailRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*DetailRowView)(nil)

var _ tui.AppUnbinder = (*DetailRowView)(nil)

var _ tui.PropsUpdater = (*DetailRowView)(nil)

func DetailRow(value string) *DetailRowView {
	var view DetailRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithPaddingTRBL(0, 0, 0, 20),
	)
	__tui_1 := FlowText(value)
	__tui_0.AddChild(__tui_1.Root)

	watchers = append(watchers, __tui_1.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_1).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_1).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = DetailRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type DangerDetailRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *DangerDetailRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *DangerDetailRowView) GetRoot() *tui.Element { return v.Root }

func (v *DangerDetailRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *DangerDetailRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *DangerDetailRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *DangerDetailRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*DangerDetailRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*DangerDetailRowView)(nil)

var _ tui.AppUnbinder = (*DangerDetailRowView)(nil)

var _ tui.PropsUpdater = (*DangerDetailRowView)(nil)

func DangerDetailRow(value string) *DangerDetailRowView {
	var view DangerDetailRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithPaddingTRBL(0, 0, 0, 20),
	)
	__tui_1 := FlowText(value)
	__tui_0.AddChild(__tui_1.Root)

	watchers = append(watchers, __tui_1.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_1).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_1).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = DangerDetailRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

func (d *Disclosure) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := app.Mount(d, 0, func() tui.Component {
		return EndpointRow(d)
	})
	__tui_0.AddChild(__tui_1)
	if !d.EndpointOpen.Get() {
		__tui_2 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithWidthPercent(100.00),
		)
		__tui_3 := tui.New(
			tui.WithWidth(2),
		)
		__tui_2.AddChild(__tui_3)
		__tui_4 := tui.New(
			tui.WithWidth(18),
		)
		__tui_2.AddChild(__tui_4)
		__tui_5 := tui.New(
			tui.WithText("OpenAI · Anthropic"),
			tui.WithFlexGrow(1),
		)
		__tui_2.AddChild(__tui_5)
		__tui_0.AddChild(__tui_2)
	}
	if d.EndpointOpen.Get() {
		__tui_6 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		if d.DiscoveryPending.Get() {
			__tui_7 := FindingClientsRow()
			__tui_6.AddChild(__tui_7.Root)
		}
		if d.Child.Get().kind == childNone && !d.DiscoveryPending.Get() {
			__tui_8 := app.Mount(d, 1, func() tui.Component {
				return ClientPicker(d)
			})
			__tui_6.AddChild(__tui_8)
		}
		for __idx_0, obs := range d.Observations.Get() {
			_ = __idx_0
			if d.Child.Get().isClient(obs.Client.ID) {
				__tui_9 := app.Mount(d, tui.MountKey(2, __idx_0), func() tui.Component {
					return ClientHeaderRow(d, obs.Client.ID, obs.Client.Name)
				})
				__tui_6.AddChild(__tui_9)
				__tui_10 := tui.New(
					tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
					tui.WithWidthPercent(100.00),
					tui.WithPaddingTRBL(0, 0, 0, 3),
				)
				if obs.Kind == observationChecking {
					__tui_11 := CheckingConfigRow()
					__tui_10.AddChild(__tui_11.Root)
				} else if obs.Kind == observationMatch {
					__tui_12 := InertRow("status", "current")
					__tui_10.AddChild(__tui_12.Root)
					if obs.Err != "" {
						__tui_13 := DetailRow(obs.Err)
						__tui_10.AddChild(__tui_13.Root)
					}
				} else if obs.Kind == observationFailed {
					__tui_14 := DangerDetailRow(obs.Err)
					__tui_10.AddChild(__tui_14.Root)
				} else if obs.Kind == observationNeedsChange {
					for __idx_1, change := range obs.Plan.Changes {
						_ = __idx_1
						__tui_15 := PlanChangeRow(change.Field, displayChange(d.Target, change))
						__tui_10.AddChild(__tui_15.Root)
					}
					__tui_16 := app.Mount(d, tui.MountKey(3, __idx_0), func() tui.Component {
						return PlanActionRow(d, obs)
					})
					__tui_10.AddChild(__tui_16)
					if obs.Err != "" {
						__tui_17 := DetailRow(obs.Err)
						__tui_10.AddChild(__tui_17.Root)
					}
				}
				__tui_6.AddChild(__tui_10)
			}
		}
		if d.Child.Get().isManual() {
			__tui_18 := app.Mount(d, 4, func() tui.Component {
				return OtherClientsHeaderRow(d)
			})
			__tui_6.AddChild(__tui_18)
			__tui_19 := tui.New(
				tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
				tui.WithWidthPercent(100.00),
				tui.WithPaddingTRBL(0, 0, 0, 3),
			)
			__tui_20 := InertRow("API", "OpenAI · Anthropic")
			__tui_19.AddChild(__tui_20.Root)
			__tui_21 := app.Mount(d, 5, func() tui.Component {
				return ManualCopyRow(d, "base-url", "Base URL", d.Target.WorkspaceURL(), d.Target.WorkspaceURL(), true)
			})
			__tui_19.AddChild(__tui_21)
			if d.Feedback.Get().key == "base-url" && d.Feedback.Get().savedPath != "" {
				__tui_22 := DetailRow("saved " + d.Feedback.Get().savedPath)
				__tui_19.AddChild(__tui_22.Root)
			}
			__tui_23 := app.Mount(d, 6, func() tui.Component {
				return ManualCopyRow(d, "model", "Model", "default", "default", true)
			})
			__tui_19.AddChild(__tui_23)
			if d.Feedback.Get().key == "model" && d.Feedback.Get().savedPath != "" {
				__tui_24 := DetailRow("saved " + d.Feedback.Get().savedPath)
				__tui_19.AddChild(__tui_24.Root)
			}
			__tui_25 := app.Mount(d, 7, func() tui.Component {
				return ManualCopyRow(d, "models-url", "Models URL", d.Target.WorkspaceURL()+"/models", d.Target.WorkspaceURL()+"/models", true)
			})
			__tui_19.AddChild(__tui_25)
			if d.Feedback.Get().key == "models-url" && d.Feedback.Get().savedPath != "" {
				__tui_26 := DetailRow("saved " + d.Feedback.Get().savedPath)
				__tui_19.AddChild(__tui_26.Root)
			}
			__tui_27 := app.Mount(d, 8, func() tui.Component {
				return ManualCopyRow(d, "api-key", "API key", "swobu · placeholder", "swobu", false)
			})
			__tui_19.AddChild(__tui_27)
			if d.Feedback.Get().saveErr != nil {
				__tui_28 := DangerDetailRow("copy failed · " + d.Feedback.Get().saveErr.Error())
				__tui_19.AddChild(__tui_28.Root)
			} else if d.Feedback.Get().clipboard.Status == cockpitui.CopyFailed && d.Feedback.Get().savedPath == "" {
				__tui_29 := DangerDetailRow("copy failed · run swobu doctor --copy")
				__tui_19.AddChild(__tui_29.Root)
			}
			if d.Feedback.Get().clipboard.Status == cockpitui.CopyUnavailable && d.Feedback.Get().savedPath == "" {
				__tui_30 := DetailRow("clipboard unavailable")
				__tui_19.AddChild(__tui_30.Root)
			}
			__tui_6.AddChild(__tui_19)
		} else if d.Child.Get().kind == childNone {
			__tui_31 := app.Mount(d, 9, func() tui.Component {
				return OtherClientsRow(d)
			})
			__tui_6.AddChild(__tui_31)
		}
		__tui_0.AddChild(__tui_6)
	}

	return __tui_0
}
