package canonical

// CapabilityPath names one stable semantic path through a canonical request or
// response. It never names a provider, route, wire field, delivery carrier, or
// collection occurrence.
type CapabilityPath string

func (p CapabilityPath) String() string { return string(p) }

const (
	RequestModel                            CapabilityPath = "request.model"
	RequestInstructions                     CapabilityPath = "request.instructions"
	RequestItemsKind                        CapabilityPath = "request.items.kind"
	RequestItemsMessageRole                 CapabilityPath = "request.items.message.role"
	RequestItemsMessageText                 CapabilityPath = "request.items.message.content.text"
	RequestItemsMessageImage                CapabilityPath = "request.items.message.content.image"
	RequestItemsMessageImageSourceURL       CapabilityPath = "request.items.message.content.image.source.url"
	RequestItemsMessageImageSourceInline    CapabilityPath = "request.items.message.content.image.source.inline"
	RequestItemsMessageImageMediaType       CapabilityPath = "request.items.message.content.image.media_type"
	RequestItemsMessageImageDetail          CapabilityPath = "request.items.message.content.image.detail"
	RequestItemsToolResultImage             CapabilityPath = "request.items.tool_result.content.image"
	RequestItemsToolResultImageSourceURL    CapabilityPath = "request.items.tool_result.content.image.source.url"
	RequestItemsToolResultImageSourceInline CapabilityPath = "request.items.tool_result.content.image.source.inline"
	RequestItemsToolResultImageMediaType    CapabilityPath = "request.items.tool_result.content.image.media_type"
	RequestItemsToolResultImageDetail       CapabilityPath = "request.items.tool_result.content.image.detail"
	RequestItemsToolCallCallID              CapabilityPath = "request.items.tool_call.call_id"
	RequestItemsToolCallTool                CapabilityPath = "request.items.tool_call.tool.kind"
	RequestItemsToolCallName                CapabilityPath = "request.items.tool_call.tool.name"
	RequestItemsToolCallInput               CapabilityPath = "request.items.tool_call.input"
	RequestItemsToolResultCallID            CapabilityPath = "request.items.tool_result.call_id"
	RequestItemsToolResultContent           CapabilityPath = "request.items.tool_result.content"
	RequestItemsToolResultContentBoundaries CapabilityPath = "request.items.tool_result.content.boundaries"
	RequestItemsToolResultIsError           CapabilityPath = "request.items.tool_result.is_error"
	RequestItemsResponsesReasoningReplay    CapabilityPath = "request.items.reasoning.responses_replay"
	RequestTools                            CapabilityPath = "request.tools"
	RequestToolsKind                        CapabilityPath = "request.tools.kind"
	RequestToolsName                        CapabilityPath = "request.tools.name"
	RequestToolsDescription                 CapabilityPath = "request.tools.description"
	RequestToolsSchema                      CapabilityPath = "request.tools.schema"
	RequestToolsSchemaStrict                CapabilityPath = "request.tools.schema.strict"
	RequestToolPolicy                       CapabilityPath = "request.tool_policy"
	RequestToolCallBatch                    CapabilityPath = "request.tool_call_batch"
	RequestOutputFormat                     CapabilityPath = "request.output_format"
	RequestOutputFormatSchema               CapabilityPath = "request.output_format.schema"
	RequestControlsMaxOutputTokens          CapabilityPath = "request.controls.max_output_tokens"
	RequestControlsTemperature              CapabilityPath = "request.controls.temperature"
	RequestControlsTopP                     CapabilityPath = "request.controls.top_p"
	RequestControlsStopSequences            CapabilityPath = "request.controls.stop_sequences"
	RequestControlsEffort                   CapabilityPath = "request.controls.effort"
	RequestReasoning                        CapabilityPath = "request.reasoning"
	RequestReasoningContext                 CapabilityPath = "request.reasoning.context"
	RequestReasoningContextResponses        CapabilityPath = "request.reasoning.context.responses"
	RequestPreviousResponse                 CapabilityPath = "request.previous_response"
	RequestPreviousResponseResponses        CapabilityPath = "request.previous_response.responses"

	ResponseID                    CapabilityPath = "response.id"
	ResponseIDResponses           CapabilityPath = "response.id.responses"
	ResponseItemsKind             CapabilityPath = "response.items.kind"
	ResponseItemsMessageRole      CapabilityPath = "response.items.message.role"
	ResponseItemsMessageText      CapabilityPath = "response.items.message.content.text"
	ResponseItemsMessageCitations CapabilityPath = "response.items.message.content.text.citations"
	ResponseItemsToolCallCallID   CapabilityPath = "response.items.tool_call.call_id"
	ResponseItemsToolCallTool     CapabilityPath = "response.items.tool_call.tool.kind"
	ResponseItemsToolCallName     CapabilityPath = "response.items.tool_call.tool.name"
	ResponseItemsToolCallInput    CapabilityPath = "response.items.tool_call.input"
	ResponseItemsReasoning        CapabilityPath = "response.items.reasoning"
	ResponseFinishReason          CapabilityPath = "response.finish_reason"
	ResponseUsageInputTokens      CapabilityPath = "response.usage.input_tokens"
	ResponseUsageOutputTokens     CapabilityPath = "response.usage.output_tokens"
	ResponseUsageReasoningTokens  CapabilityPath = "response.usage.reasoning_tokens"
	ResponseUsageCacheReadTokens  CapabilityPath = "response.usage.cache_read_tokens"
	ResponseUsageCacheWriteTokens CapabilityPath = "response.usage.cache_write_tokens"
)
