// Code generated by tui generate. DO NOT EDIT.
// Source: section.gsx

package workspace_overview

import (
	"context"
	"net/url"
	"time"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/app/operator/shares"
	workspace_delete "github.com/swobuforge/swobu/internal/cockpit/features/workspace_delete"
	workspace_edit "github.com/swobuforge/swobu/internal/cockpit/features/workspace_edit"
	"github.com/swobuforge/swobu/internal/cockpit/ports"
	"github.com/swobuforge/swobu/internal/cockpit/readmodel"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
	"github.com/swobuforge/swobu/internal/sharestate"
)

type SectionView struct {
	Model                readmodel.WorkspaceReadModel
	Expanded             *tui.State[bool]
	RenameWorkspace      workspace_edit.RenameFunc
	DeleteWorkspace      workspace_delete.DeleteFunc
	OnWorkspaceSaved     func(readmodel.WorkspaceReadModel)
	OnWorkspaceDeleted   func(readmodel.WorkspaceID)
	OnWorkspaceDiscarded func()
	ShareCommands        ports.ShareCommands
	SharePending         *tui.State[bool]
	ShareCopied          *tui.State[bool]
	ShareFeedback        *tui.State[shareFeedback]
	WorkspaceWarning     *tui.State[string]
	app                  *tui.App
	shareCopyGeneration  uint64
	// PendingDeleteWorkspaceID seeds the delete confirmation child while the
	// delete row is armed. The parent keeps the request here so Back() can clear
	// it without holding a persistent child reference.
	PendingDeleteWorkspaceID *tui.State[readmodel.WorkspaceID]
	headerRef                *tui.Ref
}

type shareFeedback struct {
	Message string
	Tone    ui.Tone
}

func Section(model readmodel.WorkspaceReadModel, commands ...ports.WorkspaceCommands) *SectionView {
	section := &SectionView{
		Model:                    model,
		Expanded:                 tui.NewState(true),
		PendingDeleteWorkspaceID: tui.NewState(readmodel.WorkspaceID("")),
		SharePending:             tui.NewState(false),
		ShareCopied:              tui.NewState(false),
		ShareFeedback:            tui.NewState(shareFeedback{}),
		WorkspaceWarning:         tui.NewState(""),
		headerRef:                tui.NewRef(),
	}
	if len(commands) > 0 && commands[0] != nil {
		section.RenameWorkspace = commands[0].RenameWorkspace
		section.DeleteWorkspace = commands[0].DeleteWorkspace
	}
	return section
}

func (s *SectionView) workspaceSaved(workspace readmodel.WorkspaceReadModel) {
	s.Model = workspace
	s.resetTransientState()
	if s.OnWorkspaceSaved != nil {
		s.OnWorkspaceSaved(workspace)
	}
}

func (s *SectionView) workspaceDeleted(workspaceID readmodel.WorkspaceID) {
	if workspaceID == s.Model.ID {
		// Summary-only rendering keeps the section visible but suppresses
		// destructive actions after the workspace it owned is gone.
	}
	if s.OnWorkspaceDeleted != nil {
		s.OnWorkspaceDeleted(workspaceID)
	}
}

func (s *SectionView) workspaceDiscarded() error {
	if s.OnWorkspaceDiscarded != nil {
		s.OnWorkspaceDiscarded()
	}
	return nil
}

func (s *SectionView) resetTransientState() {
	s.PendingDeleteWorkspaceID.Set("")
	s.SharePending.Set(false)
	s.ShareCopied.Set(false)
	s.ShareFeedback.Set(shareFeedback{})
}

func (s *SectionView) Back() bool {
	if s.Model.IsDraft() || !s.Expanded.Get() {
		return false
	}
	s.Expanded.Set(false)
	return true
}

func (s *SectionView) deleteIsOpen() bool { return s.PendingDeleteWorkspaceID.Get() != "" }

func (s *SectionView) closeDelete() { s.PendingDeleteWorkspaceID.Set("") }

func (s *SectionView) OpenDeleteConfirmation(workspaceID readmodel.WorkspaceID) {
	s.PendingDeleteWorkspaceID.Set(workspaceID)
}

func WorkspaceEdit(s *SectionView) *workspace_edit.Workflow {
	return workspace_edit.NewWorkflow(
		s.Model,
		s.RenameWorkspace,
		s.workspaceSaved,
	)
}

func DeleteConfirmation(s *SectionView) *workspace_delete.ConfirmationView {
	confirmation := workspace_delete.Confirmation(
		s.Model,
		s.DeleteWorkspace,
		s.workspaceDeleted,
	)
	if s.PendingDeleteWorkspaceID.Get() != "" {
		confirmation.Request(s.PendingDeleteWorkspaceID.Get())
	}
	confirmation.OnArm = func(_ readmodel.WorkspaceID) {
		s.OpenDeleteConfirmation(s.Model.ID)
	}
	confirmation.OnCancel = func(_ readmodel.WorkspaceID) {
		s.closeDelete()
	}
	return confirmation
}

func DraftDiscardComponent(s *SectionView) *ui.ConfirmActionRow {
	copy := ui.ConfirmActionCopy{
		Label: "discard", IdleValue: "setup", IdleAction: "discard ↵",
		ConfirmValue: "discard " + s.Model.Slug + "?", ConfirmAction: "confirm ↵",
		SubmittingValue: "discarding setup…", SubmittingHint: "wait",
		FailedValue: "discard failed", FailedAction: "retry ↵",
	}
	return ui.NewConfirmActionRow("workspace-discard:+", copy, s.workspaceDiscarded)
}

func workspaceShareKey(s *SectionView) string { return "workspace-share:" + workspaceIdentity(s) }

func (s *SectionView) issueShare(expiry sharestate.Expiry) {
	if s.ShareCommands == nil || s.SharePending.Get() {
		return
	}
	s.SharePending.Set(true)
	s.ShareCopied.Set(false)
	s.ShareFeedback.Set(shareFeedback{})
	complete := func(result shares.Result, err error) {
		s.SharePending.Set(false)
		if err != nil {
			s.setShareFailure(err.Error())
			return
		}
		parsed, parseErr := url.Parse(result.ShareURL)
		if parseErr != nil || parsed.Hostname() == "" {
			s.setShareFailure("share response is invalid")
			return
		}
		share := &readmodel.ShareReadModel{Hostname: parsed.Hostname(), Never: result.ExpiresAt == "never"}
		if !share.Never {
			share.ExpiresAt, parseErr = time.Parse(time.RFC3339, result.ExpiresAt)
			if parseErr != nil {
				s.setShareFailure("share expiry is invalid")
				return
			}
		}
		s.Model.Share = share
	}
	if s.app == nil {
		result, err := s.ShareCommands.IssueShare(context.Background(), s.Model.Slug, expiry)
		complete(result, err)
		return
	}
	go func() {
		result, err := s.ShareCommands.IssueShare(context.Background(), s.Model.Slug, expiry)
		s.app.QueueUpdate(func() { complete(result, err) })
	}()
}

func (s *SectionView) copyShare() {
	if s.ShareCommands == nil {
		return
	}
	s.shareCopyGeneration++
	generation := s.shareCopyGeneration
	result, err := s.ShareCommands.RevealShare(context.Background(), s.Model.Slug)
	if err != nil {
		s.setShareFailure(err.Error())
		return
	}
	copyResult := ui.CopyToClipboard(result.ShareURL)
	s.ShareCopied.Set(copyResult.Status == ui.CopyOK)
	s.ShareFeedback.Set(shareClipboardFeedback(copyResult))
	if copyResult.Status == ui.CopyOK {
		s.expireShareCopied(generation)
	}
}

func (s *SectionView) expireShareCopied(generation uint64) {
	if s.app == nil {
		return
	}
	app := s.app
	go func() {
		time.Sleep(1200 * time.Millisecond)
		app.QueueUpdate(func() { s.clearShareCopied(generation) })
	}()
}

func (s *SectionView) clearShareCopied(generation uint64) {
	if s.shareCopyGeneration == generation {
		s.ShareCopied.Set(false)
	}
}

func (s *SectionView) revokeShare() error {
	if s.ShareCommands == nil {
		return nil
	}
	if err := s.ShareCommands.RevokeShare(context.Background(), s.Model.Slug); err != nil {
		return err
	}
	s.Model.Share = nil
	s.ShareCopied.Set(false)
	s.ShareFeedback.Set(shareFeedback{})
	return nil
}

func (s *SectionView) setShareFailure(message string) {
	s.ShareCopied.Set(false)
	s.ShareFeedback.Set(shareFeedback{Message: message, Tone: ui.ToneFailure})
}

func shareClipboardFeedback(result ui.ClipboardResult) shareFeedback {
	switch result.Status {
	case ui.CopyUnavailable:
		return shareFeedback{Message: "clipboard unavailable", Tone: ui.ToneWarning}
	case ui.CopyFailed:
		return shareFeedback{Message: "copy failed", Tone: ui.ToneFailure}
	default:
		return shareFeedback{}
	}
}

func WorkspaceShareRowComponent(s *SectionView) tui.Component {
	props := ui.SelectProps{ID: workspaceShareKey(s), Label: "share"}
	if s.SharePending.Get() {
		props.Value = "setting up HTTPS…"
		props.OnActivate = func() {}
		return ui.NewSelect(props)
	}
	if s.Model.Share != nil {
		value := s.Model.Share.EndpointValue()
		if s.ShareCopied.Get() {
			value = "copied"
		}
		props.Value = value
		props.Action = "copy ↵"
		if s.ShareFeedback.Get().Message != "" {
			props.Action = "retry ↵"
		}
		props.OnActivate = s.copyShare
		return ui.NewSelect(props)
	}
	props.Value = "not shared"
	props.Action = "share ↵"
	props.Body = func(backout func()) tui.Component {
		options := []ui.ChoiceOption{{ID: string(sharestate.ExpiryOneDay), Label: "1 day"}, {ID: string(sharestate.ExpirySevenDays), Label: "7 days · preview"}, {ID: string(sharestate.ExpiryThirtyDays), Label: "30 days · preview"}, {ID: string(sharestate.ExpiryNever), Label: "until revoked · preview"}}
		return ui.NewChoicePicker(workspaceShareKey(s)+":expiry", options, string(sharestate.ExpiryOneDay), func(value string) { backout(); s.issueShare(sharestate.Expiry(value)) }, backout)
	}
	return ui.NewSelect(props)
}

func WorkspaceShareRevokeComponent(s *SectionView) *ui.ConfirmActionRow {
	copy := ui.ConfirmActionCopy{Label: "expires", IdleValue: s.Model.Share.ExpiryValue(), IdleAction: "revoke ↵", ConfirmValue: "Revoke shared workspace?", ConfirmAction: "revoke ↵", SubmittingValue: "revoking…", SubmittingHint: "wait", FailedValue: "revoke failed", FailedAction: "retry ↵"}
	return ui.NewConfirmActionRow(workspaceShareKey(s)+":revoke", copy, s.revokeShare)
}

func workspaceEditKey(s *SectionView) string {
	return "workspace-edit:" + workspaceIdentity(s)
}

func workspaceDeleteKey(s *SectionView) string {
	return "workspace-delete:" + workspaceIdentity(s)
}

func workspaceIdentity(s *SectionView) string {
	if s.Model.ID != "" {
		return string(s.Model.ID)
	}
	if s.Model.Slug != "" {
		return s.Model.Slug
	}
	return "+"
}

func sectionHeaderKey(s *SectionView) string { return "workspace-header" }

func WorkspaceDisclosureComponent(s *SectionView) tui.Component {
	disclosure := ui.NewSectionDisclosure(sectionHeaderKey(s), "workspace", s.Expanded)
	disclosure.AutoFocus = true
	disclosure.UseRef(s.headerRef)
	return disclosure
}

func (s *SectionView) BackRef() *tui.Ref { return s.headerRef }

func (s *SectionView) UpdateProps(fresh tui.Component) {
	headerRef := s.headerRef
	shareCopyGeneration := s.shareCopyGeneration
	s.updatePropsFields(fresh)
	s.headerRef = headerRef
	s.shareCopyGeneration = shareCopyGeneration
}

func (s *SectionView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if s.Model.IsDraft() {
		__tui_1 := DraftWorkspaceHeader()
		__tui_0.AddChild(__tui_1.Root)
	} else {
		__tui_2 := tui.New(
			tui.WithWidthPercent(100.00),
		)
		__tui_3 := app.Mount(s, tui.MountKey(0, sectionHeaderKey(s)), func() tui.Component {
			return WorkspaceDisclosureComponent(s)
		})
		__tui_2.AddChild(__tui_3)
		__tui_0.AddChild(__tui_2)
	}
	if s.Expanded.Get() {
		__tui_4 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		if s.WorkspaceWarning.Get() != "" {
			__tui_5 := tui.New(
				tui.WithWidthPercent(100.00),
				tui.WithTextStyle(ui.ToneStyle(ui.ToneWarning)),
			)
			__tui_6 := app.Mount(s, 1, func() tui.Component {
				return ui.FlowText(s.WorkspaceWarning.Get())
			})
			__tui_5.AddChild(__tui_6)
			__tui_4.AddChild(__tui_5)
		}
		if s.Model.IsDraft() {
			__tui_7 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_8 := app.Mount(s, tui.MountKey(2, workspaceEditKey(s)), func() tui.Component {
				return WorkspaceEdit(s)
			})
			__tui_7.AddChild(__tui_8)
			__tui_4.AddChild(__tui_7)
			if s.Model.Slug != "" {
				__tui_9 := tui.New(
					tui.WithWidthPercent(100.00),
				)
				__tui_10 := app.Mount(s, tui.MountKey(3, "workspace-discard:+"), func() tui.Component {
					return DraftDiscardComponent(s)
				})
				__tui_9.AddChild(__tui_10)
				__tui_4.AddChild(__tui_9)
			}
		} else if s.Model.IsBootstrap() {
			__tui_11 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_12 := app.Mount(s, tui.MountKey(4, endpointRowKey(s)), func() tui.Component {
				return EndpointRowComponent(s)
			})
			__tui_11.AddChild(__tui_12)
			__tui_4.AddChild(__tui_11)
		} else {
			__tui_13 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_14 := app.Mount(s, tui.MountKey(5, workspaceEditKey(s)), func() tui.Component {
				return WorkspaceEdit(s)
			})
			__tui_13.AddChild(__tui_14)
			__tui_4.AddChild(__tui_13)
			__tui_15 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_16 := app.Mount(s, tui.MountKey(6, endpointRowKey(s)), func() tui.Component {
				return EndpointRowComponent(s)
			})
			__tui_15.AddChild(__tui_16)
			__tui_4.AddChild(__tui_15)
			__tui_17 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_18 := app.Mount(s, tui.MountKey(7, workspaceShareKey(s)), func() tui.Component {
				return WorkspaceShareRowComponent(s)
			})
			__tui_17.AddChild(__tui_18)
			__tui_4.AddChild(__tui_17)
			if s.ShareFeedback.Get().Message != "" {
				__tui_19 := tui.New(
					tui.WithWidthPercent(100.00),
					tui.WithPaddingTRBL(0, 0, 0, 3),
					tui.WithTextStyle(ui.ToneStyle(s.ShareFeedback.Get().Tone)),
				)
				__tui_20 := app.Mount(s, 8, func() tui.Component {
					return ui.FlowText(s.ShareFeedback.Get().Message)
				})
				__tui_19.AddChild(__tui_20)
				__tui_4.AddChild(__tui_19)
			}
			if s.Model.Share != nil {
				__tui_21 := tui.New(
					tui.WithWidthPercent(100.00),
					tui.WithPaddingTRBL(0, 0, 0, 3),
				)
				__tui_22 := tui.New(
					tui.WithWidthPercent(100.00),
				)
				__tui_23 := app.Mount(s, tui.MountKey(9, workspaceShareKey(s)+":revoke"), func() tui.Component {
					return WorkspaceShareRevokeComponent(s)
				})
				__tui_22.AddChild(__tui_23)
				__tui_21.AddChild(__tui_22)
				__tui_4.AddChild(__tui_21)
			}
			__tui_24 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_25 := app.Mount(s, tui.MountKey(10, workspaceDeleteKey(s)), func() tui.Component {
				return DeleteConfirmation(s)
			})
			__tui_24.AddChild(__tui_25)
			__tui_4.AddChild(__tui_24)
		}
		__tui_0.AddChild(__tui_4)
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (s *SectionView) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*SectionView)
	if !ok {
		return
	}
	s.Model = f.Model
	s.RenameWorkspace = f.RenameWorkspace
	s.DeleteWorkspace = f.DeleteWorkspace
	s.ShareCommands = f.ShareCommands
	s.app = f.app
	s.shareCopyGeneration = f.shareCopyGeneration
}

var _ tui.PropsUpdater = (*SectionView)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (s *SectionView) bindAppFields(app *tui.App) {
	s.app = app
	if s.Expanded != nil {
		s.Expanded.BindApp(app)
	}
	if s.SharePending != nil {
		s.SharePending.BindApp(app)
	}
	if s.ShareCopied != nil {
		s.ShareCopied.BindApp(app)
	}
	if s.ShareFeedback != nil {
		s.ShareFeedback.BindApp(app)
	}
	if s.WorkspaceWarning != nil {
		s.WorkspaceWarning.BindApp(app)
	}
	if s.PendingDeleteWorkspaceID != nil {
		s.PendingDeleteWorkspaceID.BindApp(app)
	}
}

func (s *SectionView) BindApp(app *tui.App) {
	s.bindAppFields(app)
}

var _ tui.AppBinder = (*SectionView)(nil)

type DraftWorkspaceHeaderView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *DraftWorkspaceHeaderView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *DraftWorkspaceHeaderView) GetRoot() *tui.Element { return v.Root }

func (v *DraftWorkspaceHeaderView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *DraftWorkspaceHeaderView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *DraftWorkspaceHeaderView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *DraftWorkspaceHeaderView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*DraftWorkspaceHeaderView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*DraftWorkspaceHeaderView)(nil)

var _ tui.AppUnbinder = (*DraftWorkspaceHeaderView)(nil)

var _ tui.PropsUpdater = (*DraftWorkspaceHeaderView)(nil)

func DraftWorkspaceHeader() *DraftWorkspaceHeaderView {
	var view DraftWorkspaceHeaderView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("new workspace"),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = DraftWorkspaceHeaderView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
