// Code generated by tui generate. DO NOT EDIT.
// Source: section.gsx

package workspace_overview

import (
	tui "github.com/grindlemire/go-tui"
	workspace_delete "github.com/swobuforge/swobu/internal/cockpit/features/workspace_delete"
	workspace_edit "github.com/swobuforge/swobu/internal/cockpit/features/workspace_edit"
	"github.com/swobuforge/swobu/internal/cockpit/ports"
	"github.com/swobuforge/swobu/internal/cockpit/readmodel"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
)

type SectionView struct {
	Model                readmodel.WorkspaceReadModel
	Expanded             *tui.State[bool]
	RenameWorkspace      workspace_edit.RenameFunc
	DeleteWorkspace      workspace_delete.DeleteFunc
	OnWorkspaceSaved     func(readmodel.WorkspaceReadModel)
	OnWorkspaceDeleted   func(readmodel.WorkspaceID)
	OnWorkspaceDiscarded func()
	OnNotice             func(readmodel.Notice)
	// PendingDeleteWorkspaceID seeds the delete confirmation child while the
	// delete row is armed. The parent keeps the request here so Back() can clear
	// it without holding a persistent child reference.
	PendingDeleteWorkspaceID *tui.State[readmodel.WorkspaceID]
}

func Section(model readmodel.WorkspaceReadModel, commands ...ports.WorkspaceCommands) *SectionView {
	section := &SectionView{
		Model:                    model,
		Expanded:                 tui.NewState(true),
		PendingDeleteWorkspaceID: tui.NewState(readmodel.WorkspaceID("")),
	}
	if len(commands) > 0 && commands[0] != nil {
		section.RenameWorkspace = commands[0].RenameWorkspace
		section.DeleteWorkspace = commands[0].DeleteWorkspace
	}
	return section
}

func (s *SectionView) workspaceSaved(workspace readmodel.WorkspaceReadModel) {
	s.Model = workspace
	s.resetTransientState()
	if s.OnWorkspaceSaved != nil {
		s.OnWorkspaceSaved(workspace)
	}
}

func (s *SectionView) workspaceDeleted(workspaceID readmodel.WorkspaceID) {
	if workspaceID == s.Model.ID {
		// Summary-only rendering keeps the section visible but suppresses
		// destructive actions after the workspace it owned is gone.
	}
	if s.OnWorkspaceDeleted != nil {
		s.OnWorkspaceDeleted(workspaceID)
	}
}

func (s *SectionView) workspaceDiscarded() error {
	if s.OnWorkspaceDiscarded != nil {
		s.OnWorkspaceDiscarded()
	}
	return nil
}

func (s *SectionView) resetTransientState() {
	s.PendingDeleteWorkspaceID.Set("")
}

func (s *SectionView) Back() bool {
	if s.deleteIsOpen() {
		s.closeDelete()
		return true
	}
	return false
}

func (s *SectionView) deleteIsOpen() bool { return s.PendingDeleteWorkspaceID.Get() != "" }

func (s *SectionView) closeDelete() { s.PendingDeleteWorkspaceID.Set("") }

func (s *SectionView) OpenDeleteConfirmation(workspaceID readmodel.WorkspaceID) {
	s.PendingDeleteWorkspaceID.Set(workspaceID)
}

func WorkspaceEdit(s *SectionView) *workspace_edit.Workflow {
	return workspace_edit.NewWorkflow(
		s.Model,
		s.RenameWorkspace,
		s.workspaceSaved,
	)
}

func DeleteConfirmation(s *SectionView) *workspace_delete.ConfirmationView {
	confirmation := workspace_delete.Confirmation(
		s.Model,
		s.DeleteWorkspace,
		s.workspaceDeleted,
	)
	if s.PendingDeleteWorkspaceID.Get() != "" {
		confirmation.Request(s.PendingDeleteWorkspaceID.Get())
	}
	confirmation.OnArm = func(_ readmodel.WorkspaceID) {
		s.OpenDeleteConfirmation(s.Model.ID)
	}
	confirmation.OnCancel = func(_ readmodel.WorkspaceID) {
		s.closeDelete()
	}
	return confirmation
}

func DraftDiscardComponent(s *SectionView) *ui.ConfirmActionRow {
	copy := ui.ConfirmActionCopy{
		Label: "discard", IdleValue: "setup", IdleAction: "discard ↵",
		ConfirmValue: "discard " + s.Model.Slug + "?", ConfirmAction: "confirm ↵",
		SubmittingValue: "discarding setup…", SubmittingHint: "wait",
		FailedValue: "discard failed", FailedAction: "retry ↵",
	}
	return ui.NewConfirmActionRow("workspace-discard:+", copy, s.workspaceDiscarded)
}

func workspaceEditKey(s *SectionView) string {
	return "workspace-edit:" + workspaceIdentity(s)
}

func workspaceDeleteKey(s *SectionView) string {
	return "workspace-delete:" + workspaceIdentity(s)
}

func workspaceIdentity(s *SectionView) string {
	if s.Model.ID != "" {
		return string(s.Model.ID)
	}
	if s.Model.Slug != "" {
		return s.Model.Slug
	}
	return "+"
}

func sectionHeaderKey(s *SectionView) string { return "section-header:" + workspaceIdentity(s) }

func WorkspaceDisclosureComponent(s *SectionView) tui.Component {
	disclosure := ui.NewSectionDisclosure(sectionHeaderKey(s), "workspace", s.Expanded)
	disclosure.AutoFocus = true
	return disclosure
}

func (s *SectionView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if s.Model.IsDraft() {
		__tui_1 := DraftWorkspaceHeader()
		__tui_0.AddChild(__tui_1.Root)
	} else {
		__tui_2 := tui.New(
			tui.WithWidthPercent(100.00),
		)
		__tui_3 := app.Mount(s, tui.MountKey(0, sectionHeaderKey(s)), func() tui.Component {
			return WorkspaceDisclosureComponent(s)
		})
		__tui_2.AddChild(__tui_3)
		__tui_0.AddChild(__tui_2)
	}
	if s.Expanded.Get() {
		__tui_4 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		if s.Model.IsDraft() {
			__tui_5 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_6 := app.Mount(s, tui.MountKey(1, workspaceEditKey(s)), func() tui.Component {
				return WorkspaceEdit(s)
			})
			__tui_5.AddChild(__tui_6)
			__tui_4.AddChild(__tui_5)
			if s.Model.Slug != "" {
				__tui_7 := tui.New(
					tui.WithWidthPercent(100.00),
				)
				__tui_8 := app.Mount(s, tui.MountKey(2, "workspace-discard:+"), func() tui.Component {
					return DraftDiscardComponent(s)
				})
				__tui_7.AddChild(__tui_8)
				__tui_4.AddChild(__tui_7)
			}
		} else if s.Model.IsBootstrap() {
			__tui_9 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_10 := app.Mount(s, tui.MountKey(3, endpointRowKey(s)), func() tui.Component {
				return EndpointRowComponent(s)
			})
			__tui_9.AddChild(__tui_10)
			__tui_4.AddChild(__tui_9)
		} else {
			__tui_11 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_12 := app.Mount(s, tui.MountKey(4, workspaceEditKey(s)), func() tui.Component {
				return WorkspaceEdit(s)
			})
			__tui_11.AddChild(__tui_12)
			__tui_4.AddChild(__tui_11)
			__tui_13 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_14 := app.Mount(s, tui.MountKey(5, endpointRowKey(s)), func() tui.Component {
				return EndpointRowComponent(s)
			})
			__tui_13.AddChild(__tui_14)
			__tui_4.AddChild(__tui_13)
			__tui_15 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_16 := app.Mount(s, tui.MountKey(6, workspaceDeleteKey(s)), func() tui.Component {
				return DeleteConfirmation(s)
			})
			__tui_15.AddChild(__tui_16)
			__tui_4.AddChild(__tui_15)
		}
		__tui_0.AddChild(__tui_4)
	}

	return __tui_0
}

func (s *SectionView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SectionView)
	if !ok {
		return
	}
	s.Model = f.Model
	s.RenameWorkspace = f.RenameWorkspace
	s.DeleteWorkspace = f.DeleteWorkspace
}

var _ tui.PropsUpdater = (*SectionView)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (s *SectionView) bindAppFields(app *tui.App) {
	if s.Expanded != nil {
		s.Expanded.BindApp(app)
	}
	if s.PendingDeleteWorkspaceID != nil {
		s.PendingDeleteWorkspaceID.BindApp(app)
	}
}

func (s *SectionView) BindApp(app *tui.App) {
	s.bindAppFields(app)
}

var _ tui.AppBinder = (*SectionView)(nil)

type DraftWorkspaceHeaderView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *DraftWorkspaceHeaderView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *DraftWorkspaceHeaderView) GetRoot() *tui.Element { return v.Root }

func (v *DraftWorkspaceHeaderView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *DraftWorkspaceHeaderView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *DraftWorkspaceHeaderView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *DraftWorkspaceHeaderView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*DraftWorkspaceHeaderView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*DraftWorkspaceHeaderView)(nil)

var _ tui.AppUnbinder = (*DraftWorkspaceHeaderView)(nil)

var _ tui.PropsUpdater = (*DraftWorkspaceHeaderView)(nil)

func DraftWorkspaceHeader() *DraftWorkspaceHeaderView {
	var view DraftWorkspaceHeaderView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("new workspace"),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = DraftWorkspaceHeaderView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
