// Code generated by tui generate. DO NOT EDIT.
// Source: page_view.gsx

package help

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/readmodel"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
)

const (
	communityURL = "https://discord.gg/UejYpMGmw"
	issueURL     = "https://github.com/swobuforge/swobu/issues/new"
)

type PageView struct {
	Version           string
	DaemonVersion     string
	DiagnosticsStatus readmodel.DiagnosticsStatus
	DiagnosticsPath   string
	CommunityError    *tui.State[string]
	IssueError        *tui.State[string]
}

func View(model readmodel.HelpReadModel) *PageView {
	ds := model.DiagnosticsStatus
	if ds == 0 {
		ds = readmodel.DiagnosticsReady
	}
	return &PageView{
		Version:           model.Version,
		DaemonVersion:     model.DaemonVersion,
		DiagnosticsStatus: ds,
		CommunityError:    tui.NewState(""),
		IssueError:        tui.NewState(""),
	}
}

func (v *PageView) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnStop(tui.KeyDown, ui.SelectNext),
		tui.OnStop(tui.KeyUp, ui.SelectPrevious),
		tui.OnStop(tui.KeyEscape, func(event tui.KeyEvent) {
			if app := event.App(); app != nil {
				app.Stop()
			}
		}),
	}
}

func (v *PageView) versionValue() string {
	version := strings.TrimSpace(v.Version)
	if version == "" {
		version = "unknown"
	}
	daemon := strings.TrimSpace(v.DaemonVersion)
	if daemon == "" || daemon == version {
		return "swobu " + version
	}
	return "swobu " + daemon + " / " + version
}

func (v *PageView) diagnosticsValue() string {
	switch v.DiagnosticsStatus {
	case readmodel.DiagnosticsCopied:
		return "copied · paste into issue/Discord"
	case readmodel.DiagnosticsSaved:
		return "saved to " + v.DiagnosticsPath
	case readmodel.DiagnosticsFailed:
		return "failed · run swobu doctor --copy"
	default:
		return "copy report context"
	}
}

func (v *PageView) diagnosticsAction() string { return "copy \u21b5" }

func (v *PageView) diagnosticsPayloadText() string {
	payload := readmodel.DiagnosticsPayload{Version: v.Version}
	if v.DaemonVersion != "" {
		payload.DaemonVersion = v.DaemonVersion
	}
	return payload.Text()
}

func (v *PageView) onDiagnosticsCopied(result ui.ClipboardResult) {
	switch result.Status {
	case ui.CopyOK:
		v.DiagnosticsStatus = readmodel.DiagnosticsCopied
	default:
		path, err := ui.SaveTextFile("swobu-diagnostics-", v.diagnosticsPayloadText())
		if err != nil {
			v.DiagnosticsStatus = readmodel.DiagnosticsFailed
			return
		}
		v.DiagnosticsStatus = readmodel.DiagnosticsSaved
		v.DiagnosticsPath = path
	}
}

func VersionRowComponent(v *PageView) *ui.SelectableRow {
	return ui.NewSelectableRow("help:version", "version", v.versionValue(), "", nil)
}

func linkFailure(err error, url string) string {
	if err != nil {
		return "browser could not open · " + url
	}
	return ""
}

func CommunityRowComponent(v *PageView) *ui.SelectableRow {
	return ui.LinkRowComponent("help:community", "community", "Discord", communityURL, func(err error) { v.CommunityError.Set(linkFailure(err, communityURL)) })
}

func IssueRowComponent(v *PageView) *ui.SelectableRow {
	return ui.LinkRowComponent("help:issue", "issue", "GitHub issue", issueURL, func(err error) { v.IssueError.Set(linkFailure(err, issueURL)) })
}

func DiagnosticsRowComponent(v *PageView) *ui.SelectableRow {
	row := ui.CopyPasteRowComponent(
		"help:diagnostics",
		"diagnostics",
		v.diagnosticsValue(),
		v.diagnosticsAction(),
		func() ui.ClipboardResult { return ui.CopyToClipboard(v.diagnosticsPayloadText()) },
		v.onDiagnosticsCopied,
	)
	return row
}

func (v *PageView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
		tui.WithPaddingTRBL(0, 0, 0, 2),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_2 := tui.New(
		tui.WithText("help"),
		tui.WithTextStyle(ui.HeadingStyle()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	__tui_3 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_5 := app.Mount(v, 0, func() tui.Component {
		return VersionRowComponent(v)
	})
	__tui_4.AddChild(__tui_5)
	__tui_6 := app.Mount(v, 1, func() tui.Component {
		return CommunityRowComponent(v)
	})
	__tui_4.AddChild(__tui_6)
	if v.CommunityError.Get() != "" {
		__tui_7 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
			tui.WithTextStyle(ui.ToneStyle(ui.ToneFailure)),
		)
		__tui_8 := app.Mount(v, 2, func() tui.Component {
			return ui.FlowText(v.CommunityError.Get())
		})
		__tui_7.AddChild(__tui_8)
		__tui_4.AddChild(__tui_7)
	}
	__tui_9 := app.Mount(v, 3, func() tui.Component {
		return IssueRowComponent(v)
	})
	__tui_4.AddChild(__tui_9)
	if v.IssueError.Get() != "" {
		__tui_10 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
			tui.WithTextStyle(ui.ToneStyle(ui.ToneFailure)),
		)
		__tui_11 := app.Mount(v, 4, func() tui.Component {
			return ui.FlowText(v.IssueError.Get())
		})
		__tui_10.AddChild(__tui_11)
		__tui_4.AddChild(__tui_10)
	}
	__tui_12 := app.Mount(v, 5, func() tui.Component {
		return DiagnosticsRowComponent(v)
	})
	__tui_4.AddChild(__tui_12)
	__tui_0.AddChild(__tui_4)
	__tui_13 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_13)

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (v *PageView) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*PageView)
	if !ok {
		return
	}
	v.Version = f.Version
	v.DaemonVersion = f.DaemonVersion
	v.DiagnosticsStatus = f.DiagnosticsStatus
	v.DiagnosticsPath = f.DiagnosticsPath
}

func (v *PageView) UpdateProps(fresh tui.Component) {
	v.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*PageView)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (v *PageView) bindAppFields(app *tui.App) {
	if v.CommunityError != nil {
		v.CommunityError.BindApp(app)
	}
	if v.IssueError != nil {
		v.IssueError.BindApp(app)
	}
}

func (v *PageView) BindApp(app *tui.App) {
	v.bindAppFields(app)
}

var _ tui.AppBinder = (*PageView)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*PageView)(nil)
)
