// swobu:lint ignore test-only-dead-cluster because=compat feature vocabulary is authoritative even when only tests exercise some names.
package compat

// Feature names a compatibility-addressable canonical or approved
// representation path. For canonical data, the value mirrors its typed schema
// path. Optional scoped suffixes are protocol, then provider; collection
// indices are omitted because Subject identifies one occurrence.
type Feature string

const (
	// Canonical request paths.
	RequestModel                            Feature = "request.model"
	RequestInstructions                     Feature = "request.instructions"
	RequestItemsKind                        Feature = "request.items.kind"
	RequestItemsMessageRole                 Feature = "request.items.message.role"
	RequestItemsMessageText                 Feature = "request.items.message.content.text"
	RequestItemsMessageImage                Feature = "request.items.message.content.image"
	RequestItemsMessageImageSourceURL       Feature = "request.items.message.content.image.source.url"
	RequestItemsMessageImageSourceInline    Feature = "request.items.message.content.image.source.inline"
	RequestItemsMessageImageMediaType       Feature = "request.items.message.content.image.media_type"
	RequestItemsMessageImageDetail          Feature = "request.items.message.content.image.detail"
	RequestItemsToolResultImage             Feature = "request.items.tool_result.content.image"
	RequestItemsToolResultImageSourceURL    Feature = "request.items.tool_result.content.image.source.url"
	RequestItemsToolResultImageSourceInline Feature = "request.items.tool_result.content.image.source.inline"
	RequestItemsToolResultImageMediaType    Feature = "request.items.tool_result.content.image.media_type"
	RequestItemsToolResultImageDetail       Feature = "request.items.tool_result.content.image.detail"
	RequestItemsToolCallCallID              Feature = "request.items.tool_call.call_id"
	RequestItemsToolCallTool                Feature = "request.items.tool_call.tool.kind"
	RequestItemsToolCallName                Feature = "request.items.tool_call.tool.name"
	RequestItemsToolCallInput               Feature = "request.items.tool_call.input"
	RequestItemsToolResultCallID            Feature = "request.items.tool_result.call_id"
	RequestItemsToolResultContent           Feature = "request.items.tool_result.content"
	RequestItemsToolResultContentBoundaries Feature = "request.items.tool_result.content.boundaries"
	RequestItemsToolResultIsError           Feature = "request.items.tool_result.is_error"
	RequestItemsResponsesReasoningReplay    Feature = "request.items.reasoning.responses_replay"
	RequestTools                            Feature = "request.tools"
	RequestToolsKind                        Feature = "request.tools.kind"
	RequestToolsName                        Feature = "request.tools.name"
	RequestToolsDescription                 Feature = "request.tools.description"
	RequestToolsSchema                      Feature = "request.tools.schema"
	RequestToolsSchemaStrict                Feature = "request.tools.schema.strict"
	RequestToolPolicy                       Feature = "request.tool_policy"
	RequestToolCallBatch                    Feature = "request.tool_call_batch"
	RequestOutputFormat                     Feature = "request.output_format"
	RequestOutputFormatSchema               Feature = "request.output_format.schema"
	RequestControlsMaxOutputTokens          Feature = "request.controls.max_output_tokens"
	RequestControlsTemperature              Feature = "request.controls.temperature"
	RequestControlsTopP                     Feature = "request.controls.top_p"
	RequestControlsStopSequences            Feature = "request.controls.stop_sequences"
	RequestControlsEffort                   Feature = "request.controls.effort"
	RequestReasoning                        Feature = "request.reasoning"
	RequestReasoningContext                 Feature = "request.reasoning.context"
	RequestReasoningContextResponses        Feature = "request.reasoning.context.responses"
	RequestPreviousResponse                 Feature = "request.previous_response"
	RequestPreviousResponseResponses        Feature = "request.previous_response.responses"

	// Canonical response paths.
	ResponseID                    Feature = "response.id"
	ResponseIDResponses           Feature = "response.id.responses"
	ResponseItemsKind             Feature = "response.items.kind"
	ResponseItemsMessageRole      Feature = "response.items.message.role"
	ResponseItemsMessageText      Feature = "response.items.message.content.text"
	ResponseItemsMessageCitations Feature = "response.items.message.content.text.citations"
	ResponseItemsToolCallCallID   Feature = "response.items.tool_call.call_id"
	ResponseItemsToolCallTool     Feature = "response.items.tool_call.tool.kind"
	ResponseItemsToolCallName     Feature = "response.items.tool_call.tool.name"
	ResponseItemsToolCallInput    Feature = "response.items.tool_call.input"
	ResponseItemsReasoning        Feature = "response.items.reasoning"
	ResponseFinishReason          Feature = "response.finish_reason"
	ResponseUsageInputTokens      Feature = "response.usage.input_tokens"
	ResponseUsageOutputTokens     Feature = "response.usage.output_tokens"
	ResponseUsageReasoningTokens  Feature = "response.usage.reasoning_tokens"
	ResponseUsageCacheReadTokens  Feature = "response.usage.cache_read_tokens"
	ResponseUsageCacheWriteTokens Feature = "response.usage.cache_write_tokens"

	// Approved noncanonical representation roots.
	DeliveryStreaming        Feature = "delivery.streaming"
	DeliveryServerSentEvents Feature = "delivery.server_sent_events"
	DeliveryWebSocket        Feature = "delivery.websocket"
	DeliveryIncremental      Feature = "delivery.incremental"
	DeliveryTerminalEvent    Feature = "delivery.terminal_event"
	WireJSONMode             Feature = "wire.json_mode"
	WireConversation         Feature = "wire.conversation"
	ErrorShape               Feature = "error.shape"
	ErrorClass               Feature = "error.class"
)
