// Code generated by tui generate. DO NOT EDIT.
// Source: ambient_or_reference_authentication.gsx

package target_config

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
	"github.com/swobuforge/swobu/internal/domain/credentialref"
)

type AmbientOrReferenceAuthenticationProps struct {
	ID              string
	AmbientLabel    string
	ReferenceLabel  string
	SuggestedEnvVar string
	Ref             string
	Apply           func(string)
	Store           func(string) (string, error)
}

type ambientOrReferenceStage uint8

const (
	ambientOrReferenceClosed ambientOrReferenceStage = iota
	ambientOrReferenceMenu
	ambientOrReferenceChooser
)

type ambientOrReferenceAuthentication struct {
	props   AmbientOrReferenceAuthenticationProps
	stage   *tui.State[ambientOrReferenceStage]
	ref     *tui.State[string]
	chooser *tui.State[*credentialRow]
}

func AmbientOrReferenceAuthentication(props AmbientOrReferenceAuthenticationProps) tui.Component {
	a := &ambientOrReferenceAuthentication{
		props: props,
		stage: tui.NewState(ambientOrReferenceClosed),
		ref:   tui.NewState(strings.TrimSpace(props.Ref)),
	}
	chooser := newCredentialField(CredentialFieldProps{
		ID:              props.ID + ":reference",
		SuggestedEnvVar: props.SuggestedEnvVar,
		Store:           props.Store,
		ChoiceAction:    "select ↵",
	})
	chooser.props.Apply = func(ref string) {
		a.apply(ref)
		a.stage.Set(ambientOrReferenceClosed)
	}
	chooser.stage.Set(credStageMenu)
	a.chooser = tui.NewState(chooser)
	return a
}

func (a *ambientOrReferenceAuthentication) BindApp(app *tui.App) {
	a.bindAppFields(app)
	a.chooser.Get().BindApp(app)
}

func (a *ambientOrReferenceAuthentication) UnbindApp() {}

func (a *ambientOrReferenceAuthentication) KeyMap() tui.KeyMap {
	return ui.BackScope(func() bool { return a.stage.Get() != ambientOrReferenceClosed }, a.retreat)
}

func (a *ambientOrReferenceAuthentication) key(suffix string) string {
	return a.props.ID + ":" + suffix
}

func (a *ambientOrReferenceAuthentication) toggle() {
	if a.stage.Get() == ambientOrReferenceClosed {
		a.stage.Set(ambientOrReferenceMenu)
		return
	}
	a.stage.Set(ambientOrReferenceClosed)
}

func (a *ambientOrReferenceAuthentication) open() {
	if a.stage.Get() == ambientOrReferenceClosed {
		a.stage.Set(ambientOrReferenceMenu)
	}
}

func (a *ambientOrReferenceAuthentication) retreat() {
	if a.stage.Get() == ambientOrReferenceChooser {
		if a.chooser.Get().stage.Get() != credStageMenu {
			a.chooser.Get().stage.Set(credStageMenu)
			return
		}
		a.stage.Set(ambientOrReferenceMenu)
		return
	}
	a.stage.Set(ambientOrReferenceClosed)
}

func (a *ambientOrReferenceAuthentication) apply(ref string) {
	ref = strings.TrimSpace(ref) // swobu:io-string source=boundary
	a.ref.Set(ref)
	if a.props.Apply != nil {
		a.props.Apply(ref)
	}
}

func (a *ambientOrReferenceAuthentication) useAmbient() {
	a.apply("")
	a.stage.Set(ambientOrReferenceClosed)
}

func (a *ambientOrReferenceAuthentication) chooseReference() {
	a.chooser.Get().reset()
	a.chooser.Get().stage.Set(credStageMenu)
	a.stage.Set(ambientOrReferenceChooser)
}

func (a *ambientOrReferenceAuthentication) referenceSource() string {
	return credentialSourceDisplay(credentialref.Parse(a.ref.Get()))
}

func (a *ambientOrReferenceAuthentication) referenceDetail() string {
	parsed := credentialref.Parse(a.ref.Get())
	_, detail, ok := strings.Cut(parsed.String(), ":")
	if !ok {
		return parsed.String()
	}
	return detail
}

func AmbientOrReferenceHeader(a *ambientOrReferenceAuthentication) *ui.SelectableRow {
	value := a.props.AmbientLabel
	if strings.TrimSpace(a.ref.Get()) != "" {
		value = a.props.ReferenceLabel + " · " + a.referenceSource()
	} else if a.stage.Get() == ambientOrReferenceChooser {
		value = a.props.ReferenceLabel
	}
	action := "manage ↵"
	if a.stage.Get() != ambientOrReferenceClosed {
		action = "close ↵"
	}
	return ui.NewSelectableRow(a.key("header"), "authentication", value, action, a.toggle)
}

func AmbientOrReferenceUseReferenceOption(a *ambientOrReferenceAuthentication) *ui.SelectableRow {
	return ui.NewSelectableRow(a.key("use-reference"), "", "use "+a.props.ReferenceLabel, "select ↵", a.chooseReference)
}

func AmbientOrReferenceChangeOption(a *ambientOrReferenceAuthentication) *ui.SelectableRow {
	return ui.NewSelectableRow(a.key("change-reference"), "", "change credential", "enter ↵", a.chooseReference)
}

func AmbientOrReferenceUseAmbientOption(a *ambientOrReferenceAuthentication) *ui.SelectableRow {
	return ui.NewSelectableRow(a.key("use-ambient"), "", "use "+a.props.AmbientLabel, "select ↵", a.useAmbient)
}

func (a *ambientOrReferenceAuthentication) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := app.Mount(a, 0, func() tui.Component {
		return AmbientOrReferenceHeader(a)
	})
	__tui_0.AddChild(__tui_1)
	if a.stage.Get() == ambientOrReferenceMenu {
		__tui_2 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		if strings.TrimSpace(a.ref.Get()) == "" {
			__tui_3 := app.Mount(a, 1, func() tui.Component {
				return AmbientOrReferenceUseReferenceOption(a)
			})
			__tui_2.AddChild(__tui_3)
		} else {
			__tui_4 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_5 := app.Mount(a, 2, func() tui.Component {
				return FlowText(a.referenceDetail())
			})
			__tui_4.AddChild(__tui_5)
			__tui_2.AddChild(__tui_4)
			__tui_6 := app.Mount(a, 3, func() tui.Component {
				return AmbientOrReferenceChangeOption(a)
			})
			__tui_2.AddChild(__tui_6)
			__tui_7 := app.Mount(a, 4, func() tui.Component {
				return AmbientOrReferenceUseAmbientOption(a)
			})
			__tui_2.AddChild(__tui_7)
		}
		__tui_0.AddChild(__tui_2)
	} else if a.stage.Get() == ambientOrReferenceChooser {
		__tui_8 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		__tui_9 := app.Mount(a, 5, func() tui.Component {
			return CredentialChooser(a.chooser.Get())
		})
		__tui_8.AddChild(__tui_9)
		__tui_0.AddChild(__tui_8)
	} else if detail := a.referenceDetail(); detail != "" {
		__tui_10 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 18),
		)
		__tui_11 := app.Mount(a, 6, func() tui.Component {
			return FlowText(detail)
		})
		__tui_10.AddChild(__tui_11)
		__tui_0.AddChild(__tui_10)
	}

	return __tui_0
}

func (a *ambientOrReferenceAuthentication) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ambientOrReferenceAuthentication)
	if !ok {
		return
	}
	a.props = f.props
}

var _ tui.PropsUpdater = (*ambientOrReferenceAuthentication)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (a *ambientOrReferenceAuthentication) bindAppFields(app *tui.App) {
	if a.stage != nil {
		a.stage.BindApp(app)
	}
	if a.ref != nil {
		a.ref.BindApp(app)
	}
	if a.chooser != nil {
		a.chooser.BindApp(app)
	}
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*ambientOrReferenceAuthentication)(nil)
)
