// Code generated by tui generate. DO NOT EDIT.
// Source: credential.gsx

package target_config

import (
	"os"
	"path/filepath"
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
	"github.com/swobuforge/swobu/internal/domain/credentialref"
)

type credentialStage int

const (
	credStageClosed credentialStage = iota
	credStageMenu
	credStageEnv
	credStageFile
	credStagePaste
)

type credentialRow struct {
	props      CredentialFieldProps
	stage      *tui.State[credentialStage]
	envName    *tui.State[string]
	filePath   *tui.State[string]
	secret     *tui.State[string]
	localError *tui.State[string]
	readDir    func(string) ([]ui.FileBrowserEntry, error)
}

type CredentialFieldProps struct {
	ID              string
	Optional        bool
	SuggestedEnvVar string
	Ref             string
	AutoFocus       bool
	Apply           func(string)
	Store           func(string) (string, error)
	ChoiceAction    string
}

type credentialChooserBody struct{ row *credentialRow }

func credentialRefDisplay(raw string) string {
	ref := strings.TrimSpace(raw) // swobu:io-string source=boundary
	parsed := credentialref.Parse(ref)
	_, payload, hasPrefix := strings.Cut(parsed.String(), ":")
	if !hasPrefix {
		payload = parsed.String()
	}
	payload = strings.TrimSpace(payload) // swobu:io-string source=boundary
	switch parsed.Kind() {
	case credentialref.KindEnv:
		return credentialSourceDisplay(parsed) + " · " + payload
	case credentialref.KindFile:
		return credentialSourceDisplay(parsed) + " · " + payload
	case credentialref.KindSecret, credentialref.KindSecretFile:
		return credentialSourceDisplay(parsed) + " credential"
	default:
		return ref
	}
}

func credentialSourceDisplay(ref credentialref.Ref) string {
	switch ref.Kind() {
	case credentialref.KindEnv:
		return "environment"
	case credentialref.KindFile:
		return "file"
	case credentialref.KindSecret, credentialref.KindSecretFile:
		return "stored"
	default:
		return "credential"
	}
}

func newCredentialField(props CredentialFieldProps) *credentialRow {
	return &credentialRow{
		props: props,
		stage: tui.NewState(credStageClosed), envName: tui.NewState(""),
		filePath: tui.NewState(""), secret: tui.NewState(""), localError: tui.NewState(""), readDir: ui.OSReadDir,
	}
}

func (r *credentialRow) key(suffix string) string { return r.props.ID + ":" + suffix }

func (r *credentialRow) optional() bool { return r.props.Optional }

func (r *credentialRow) fail(message string) { r.localError.Set(message) }

func (r *credentialRow) BindApp(app *tui.App) {
	r.stage.BindApp(app)
	r.envName.BindApp(app)
	r.filePath.BindApp(app)
	r.secret.BindApp(app)
	r.localError.BindApp(app)
}

func (r *credentialRow) UnbindApp() {}

func (r *credentialRow) KeyMap() tui.KeyMap {
	return ui.BackScope(func() bool { return r.stage.Get() != credStageClosed }, r.retreat)
}

func FileCredentialBrowser(r *credentialRow) *ui.FileBrowser {
	dir := r.filePath.Get()
	if info, err := os.Stat(dir); dir != "" && err == nil && !info.IsDir() {
		dir = filepath.Dir(dir)
	}
	browser := ui.NewFileBrowser(r.key("file-browser"), "credential file", dir, r.readDir, func(path string) { r.filePath.Set(path); r.saveFile(path) }, r.retreat)
	browser.AutoFocus = true
	return browser
}

func (r *credentialRow) toggle() {
	if r.stage.Get() == credStageClosed {
		r.stage.Set(credStageMenu)
		return
	}
	r.stage.Set(credStageClosed)
}

func (r *credentialRow) open() {
	r.stage.Set(credStageMenu)
}

func (r *credentialRow) selectRef(ref string) {
	ref = strings.TrimSpace(ref) // swobu:io-string source=boundary
	if ref == "" {
		return
	}
	r.stage.Set(credStageClosed)
	if r.props.Apply != nil {
		r.props.Apply(ref)
	}
}

func (r *credentialRow) enter(stage credentialStage) bool {
	if r.stage.Get() != credStageMenu {
		return false
	}
	r.stage.Set(stage)
	return true
}

func (r *credentialRow) retreat() {
	if r.stage.Get() == credStageMenu {
		r.stage.Set(credStageClosed)
		return
	}
	r.stage.Set(credStageMenu)
}

func (r *credentialRow) reset() {
	r.stage.Set(credStageClosed)
	r.envName.Set("")
	r.filePath.Set("")
	r.secret.Set("")
}

func (r *credentialRow) openEnv() {
	if !r.enter(credStageEnv) {
		return
	}
	if strings.TrimSpace(r.envName.Get()) == "" {
		r.envName.Set(strings.TrimSpace(r.props.SuggestedEnvVar))
	}
}

func (r *credentialRow) saveEnv(raw string) {
	name := strings.TrimSpace(raw) // swobu:io-string source=boundary
	if name == "" {
		r.fail("variable is required")
		return
	}
	r.fail("")
	r.selectRef("env:" + name)
}

func (r *credentialRow) openFile() {
	r.enter(credStageFile)
}

func (r *credentialRow) saveFile(raw string) {
	path := strings.TrimSpace(raw) // swobu:io-string source=boundary
	if path == "" {
		r.fail("file path is required")
		return
	}
	r.fail("")
	r.selectRef("file:" + path)
}

func (r *credentialRow) openPaste() {
	r.enter(credStagePaste)
}

func (r *credentialRow) savePasted() {
	secret := strings.TrimSpace(r.secret.Get()) // swobu:io-string source=boundary
	if secret == "" {
		r.fail("secret is required")
		return
	}
	if r.props.Store == nil {
		r.fail("credential store is not wired yet")
		return
	}
	ref, err := r.props.Store(secret)
	if err != nil {
		r.fail(err.Error())
		return
	}
	r.fail("")
	if r.props.Apply != nil {
		r.props.Apply(ref)
	}
	r.secret.Set("")
	r.stage.Set(credStageClosed)
}

func (r *credentialRow) selectNone() {
	if !r.optional() {
		r.fail("credential is required")
		return
	}
	r.fail("")
	r.stage.Set(credStageClosed)
	if r.props.Apply != nil {
		r.props.Apply("")
	}
}

func CredentialControlWithAutoFocus(r *credentialRow) *ui.SelectableRow {
	value := credentialRefDisplay(r.props.Ref)
	label := "credential"
	action := "change ↵"
	if strings.TrimSpace(value) == "" {
		if r.optional() {
			value, action = "none", "add ↵"
		} else {
			value, action = "required", "choose ↵"
		}
	}
	if r.stage.Get() != credStageClosed {
		action = "close ↵"
	}
	row := ui.NewSelectableRow(
		r.key("display"),
		label,
		value,
		action,
		r.toggle,
	)
	row.AutoFocus = strings.TrimSpace(r.props.Ref) == "" && r.stage.Get() == credStageClosed && r.props.AutoFocus
	return row
}

func CredentialRemoveOption(r *credentialRow) *ui.SelectableRow {
	row := ui.NewSelectableRow(
		r.key("none-action"),
		"",
		"remove credential",
		"remove ↵",
		r.selectNone,
	)
	row.AutoFocus = false
	return row
}

func CredentialEnvOption(r *credentialRow) *ui.SelectableRow {
	action := strings.TrimSpace(r.props.ChoiceAction)
	if action == "" {
		action = "enter ↵"
	}
	row := ui.NewSelectableRow(
		r.key("env-action"),
		"",
		"environment variable",
		action,
		r.openEnv,
	)
	row.AutoFocus = true
	return row
}

func CredentialFileOption(r *credentialRow) *ui.SelectableRow {
	action := strings.TrimSpace(r.props.ChoiceAction)
	if action == "" {
		action = "enter ↵"
	}
	row := ui.NewSelectableRow(
		r.key("file-action"),
		"",
		"file",
		action,
		r.openFile,
	)
	return row
}

func CredentialPasteSecretOption(r *credentialRow) *ui.SelectableRow {
	action := strings.TrimSpace(r.props.ChoiceAction)
	if action == "" {
		action = "enter ↵"
	}
	row := ui.NewSelectableRow(
		r.key("paste-secret-action"),
		"",
		"paste credential",
		action,
		r.openPaste,
	)
	return row
}

func EnvCredentialInput(r *credentialRow) *ui.EditableRow {
	row := ui.NewEditableRow(
		r.key("env-input"),
		"variable",
		r.envName,
	)
	row.Placeholder = "_"
	row.ViewAction = "edit ↵"
	row.EditAction = "save ↵"
	row.StartEditing = true
	row.AutoFocus = true
	row.OnSubmit = func(raw string) {
		r.envName.Set(strings.TrimSpace(raw))
		r.saveEnv(r.envName.Get())
	}
	row.OnClose = r.retreat
	return row
}

func PasteSecretInput(r *credentialRow) *ui.EditableRow {
	row := ui.NewEditableRow(
		r.key("secret-value"),
		"secret",
		r.secret,
	)
	row.Placeholder = "_"
	row.Sensitive = true
	row.ViewAction = "edit ↵"
	row.EditAction = "save ↵"
	row.AutoFocus = true
	row.StartEditing = true
	row.OnSubmit = func(raw string) {
		r.secret.Set(strings.TrimSpace(raw))
		r.savePasted()
	}
	row.OnClose = r.retreat
	return row
}

func CredentialChooser(r *credentialRow) *credentialChooserBody {
	return &credentialChooserBody{row: r}
}

func (r *credentialRow) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := app.Mount(r, 0, func() tui.Component {
		return CredentialControlWithAutoFocus(r)
	})
	__tui_0.AddChild(__tui_1)
	if r.stage.Get() != credStageClosed {
		__tui_2 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		if r.stage.Get() == credStageMenu {
			__tui_3 := app.Mount(r, 1, func() tui.Component {
				return CredentialEnvOption(r)
			})
			__tui_2.AddChild(__tui_3)
			__tui_4 := app.Mount(r, 2, func() tui.Component {
				return CredentialFileOption(r)
			})
			__tui_2.AddChild(__tui_4)
			__tui_5 := app.Mount(r, 3, func() tui.Component {
				return CredentialPasteSecretOption(r)
			})
			__tui_2.AddChild(__tui_5)
			if r.optional() && strings.TrimSpace(r.props.Ref) != "" {
				__tui_6 := app.Mount(r, 4, func() tui.Component {
					return CredentialRemoveOption(r)
				})
				__tui_2.AddChild(__tui_6)
			}
		} else if r.stage.Get() == credStageEnv {
			__tui_7 := app.Mount(r, 5, func() tui.Component {
				return EnvCredentialInput(r)
			})
			__tui_2.AddChild(__tui_7)
		} else if r.stage.Get() == credStageFile {
			__tui_8 := app.Mount(r, 6, func() tui.Component {
				return FileCredentialBrowser(r)
			})
			__tui_2.AddChild(__tui_8)
		} else if r.stage.Get() == credStagePaste {
			__tui_9 := app.Mount(r, 7, func() tui.Component {
				return PasteSecretInput(r)
			})
			__tui_2.AddChild(__tui_9)
		}
		__tui_0.AddChild(__tui_2)
		if strings.TrimSpace(r.localError.Get()) != "" {
			__tui_10 := CredentialInputError(r.localError.Get())
			__tui_0.AddChild(__tui_10.Root)
		}
	}

	return __tui_0
}

func (r *credentialRow) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*credentialRow)
	if !ok {
		return
	}
	r.props = f.props
}

var _ tui.PropsUpdater = (*credentialRow)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (r *credentialRow) bindAppFields(app *tui.App) {
	if r.stage != nil {
		r.stage.BindApp(app)
	}
	if r.envName != nil {
		r.envName.BindApp(app)
	}
	if r.filePath != nil {
		r.filePath.BindApp(app)
	}
	if r.secret != nil {
		r.secret.BindApp(app)
	}
	if r.localError != nil {
		r.localError.BindApp(app)
	}
}

type CredentialInputErrorView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *CredentialInputErrorView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *CredentialInputErrorView) GetRoot() *tui.Element { return v.Root }

func (v *CredentialInputErrorView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *CredentialInputErrorView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *CredentialInputErrorView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *CredentialInputErrorView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*CredentialInputErrorView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*CredentialInputErrorView)(nil)

var _ tui.AppUnbinder = (*CredentialInputErrorView)(nil)

var _ tui.PropsUpdater = (*CredentialInputErrorView)(nil)

func CredentialInputError(message string) *CredentialInputErrorView {
	var view CredentialInputErrorView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithPaddingTRBL(0, 0, 0, 18),
	)
	__tui_1 := FlowText(message)
	__tui_0.AddChild(__tui_1.Root)

	watchers = append(watchers, __tui_1.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_1).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_1).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = CredentialInputErrorView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

func (b *credentialChooserBody) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if b.row.stage.Get() == credStageMenu {
		__tui_1 := app.Mount(b, 0, func() tui.Component {
			return CredentialEnvOption(b.row)
		})
		__tui_0.AddChild(__tui_1)
		__tui_2 := app.Mount(b, 1, func() tui.Component {
			return CredentialFileOption(b.row)
		})
		__tui_0.AddChild(__tui_2)
		__tui_3 := app.Mount(b, 2, func() tui.Component {
			return CredentialPasteSecretOption(b.row)
		})
		__tui_0.AddChild(__tui_3)
	} else if b.row.stage.Get() == credStageEnv {
		__tui_4 := app.Mount(b, 3, func() tui.Component {
			return EnvCredentialInput(b.row)
		})
		__tui_0.AddChild(__tui_4)
	} else if b.row.stage.Get() == credStageFile {
		__tui_5 := app.Mount(b, 4, func() tui.Component {
			return FileCredentialBrowser(b.row)
		})
		__tui_0.AddChild(__tui_5)
	} else if b.row.stage.Get() == credStagePaste {
		__tui_6 := app.Mount(b, 5, func() tui.Component {
			return PasteSecretInput(b.row)
		})
		__tui_0.AddChild(__tui_6)
	}
	if strings.TrimSpace(b.row.localError.Get()) != "" {
		__tui_7 := CredentialInputError(b.row.localError.Get())
		__tui_0.AddChild(__tui_7.Root)
	}

	return __tui_0
}

func (b *credentialChooserBody) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*credentialChooserBody)
	if !ok {
		return
	}
	b.row = f.row
}

var _ tui.PropsUpdater = (*credentialChooserBody)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*credentialRow)(nil)
)
