// Code generated by tui generate. DO NOT EDIT.
// Source: error.gsx

package target_config

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
)

type FlowTextView = ui.FlowTextView

func FlowText(text string) *FlowTextView {
	return ui.FlowText(text)
}

type TargetConfigErrorView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *TargetConfigErrorView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *TargetConfigErrorView) GetRoot() *tui.Element { return v.Root }

func (v *TargetConfigErrorView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *TargetConfigErrorView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *TargetConfigErrorView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *TargetConfigErrorView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*TargetConfigErrorView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*TargetConfigErrorView)(nil)

var _ tui.AppUnbinder = (*TargetConfigErrorView)(nil)

var _ tui.PropsUpdater = (*TargetConfigErrorView)(nil)

func TargetConfigError(w *TargetConfig) *TargetConfigErrorView {
	var view TargetConfigErrorView
	var watchers []tui.Watcher

	var __tui_2 *FlowTextView
	__tui_0 := tui.New()
	if strings.TrimSpace(w.Error.Get()) != "" {
		__tui_1 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 18),
		)
		__tui_2 = FlowText(w.Error.Get())
		__tui_1.AddChild(__tui_2.Root)
		__tui_0.AddChild(__tui_1)
	}

	if __tui_2 != nil {
		watchers = append(watchers, __tui_2.GetWatchers()...)
	}

	__bindApp := func(app *tui.App) {
		if __tui_2 != nil {
			if binder, ok := any(__tui_2).(tui.AppBinder); ok {
				binder.BindApp(app)
			}
		}
	}

	__unbindApp := func() {
		if __tui_2 != nil {
			if unbinder, ok := any(__tui_2).(tui.AppUnbinder); ok {
				unbinder.UnbindApp()
			}
		}
	}

	view = TargetConfigErrorView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
