// Code generated by tui generate. DO NOT EDIT.
// Source: provider_custom.gsx

package target_config

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
	"github.com/swobuforge/swobu/internal/profile"
)

type customProviderForm struct{ target *TargetConfig }

func CustomProviderForm(w *TargetConfig) tui.Component {
	return &customProviderForm{target: w}
}

func customReadiness(w *TargetConfig, base providerSetupState) providerSetupState {
	setup := base
	endpointValue := strings.TrimSpace(w.BaseURL.Get()) // swobu:io-string source=boundary
	if endpointValue == "" {
		setup.Status = setupMissingLocator
		return setup
	}
	if setup.CredentialRequired && strings.TrimSpace(setup.CredentialRef) == "" {
		setup.Status = setupMissingCredential
		return setup
	}
	setup.Status = setupReady
	return setup
}

func (w *TargetConfig) IsCustomFlow() bool {
	return profile.ProviderID(w.Draft.Get().ProviderSpec) == profile.ProviderSpecCustom
}

func shouldRenderCredentialHeaderRow(w *TargetConfig) bool {
	return w.IsCustomFlow() &&
		strings.TrimSpace(w.BaseURL.Get()) != "" &&
		strings.TrimSpace(w.Draft.Get().CredentialRef) != ""
}

func shouldRenderCustomCredentialRow(w *TargetConfig) bool {
	return w.IsCustomFlow() && strings.TrimSpace(w.BaseURL.Get()) != ""
}

func CredentialHeaderControl(w *TargetConfig) *ui.Select {
	value := strings.TrimSpace(w.Draft.Get().CredentialHeader)
	if value == "" {
		value = w.inferredCredentialHeader()
	}
	return ui.NewSelect(ui.SelectProps{
		ID:     TargetAddMountKey(w, "credential-header"),
		Label:  "credential header",
		Value:  value,
		Action: "change ↵",
		Body: func(backout func()) tui.Component {
			return CredentialHeaderPicker(w, backout)
		},
	})
}

func (w *TargetConfig) commitCredentialHeader(header string) {
	d := w.Draft.Get()
	d.CredentialHeader = header
	w.Draft.Set(d)
	if w.CredentialHeaderEdited != nil {
		w.CredentialHeaderEdited.Set(true)
	}
}

func (w *TargetConfig) inferredCredentialHeader() string {
	return profile.InferredCredentialHeaderForBackendURL(w.BaseURL.Get())
}

func (w *TargetConfig) reseedInferredCredentialHeader() {
	if w.CredentialHeaderEdited != nil && w.CredentialHeaderEdited.Get() {
		return
	}
	d := w.Draft.Get()
	d.CredentialHeader = w.inferredCredentialHeader()
	w.Draft.Set(d)
}

func resolvedCredentialHeader(spec, header string) string {
	if h := strings.TrimSpace(header); h != "" {
		return h
	}
	if profile.ProviderID(spec) != profile.ProviderSpecCustom {
		return ""
	}
	if defaults := profile.SupportedAuthHeadersForSpec(spec); len(defaults) > 0 {
		return defaults[0]
	}
	return "Authorization"
}

func CredentialHeaderPicker(w *TargetConfig, backout func()) *ui.SearchPicker {
	common := profile.SupportedAuthHeadersForSpec(w.Draft.Get().ProviderSpec)
	opts := make([]ui.SearchOption, 0, len(common))
	for _, header := range common {
		opts = append(opts, ui.SearchOption{
			ID:       header,
			Label:    header,
			Keywords: []string{header, strings.ToLower(header)},
		})
	}
	picker := ui.NewSearchPicker(
		TargetAddMountKey(w, "credential-header-picker"),
		"credential header",
		opts,
		func(sel ui.Selection) {
			w.commitCredentialHeader(strings.TrimSpace(sel.Value))
			if backout != nil {
				backout()
			}
		},
		func() {
			if backout != nil {
				backout()
			}
		},
	)
	picker.Mode = ui.SearchPickerOpen
	picker.AutoFocus = true
	return picker
}

func (f *customProviderForm) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if shouldRenderEndpointRow(f.target) {
		__tui_1 := app.Mount(f, 0, func() tui.Component {
			return EndpointInput(f.target, setupRequiresLocator(f.target))
		})
		__tui_0.AddChild(__tui_1)
	}
	if shouldRenderCustomCredentialRow(f.target) {
		__tui_2 := tui.New(
			tui.WithWidthPercent(100.00),
		)
		__tui_3 := app.Mount(f, tui.MountKey(1, credentialRegionKey(f.target)), func() tui.Component {
			return CredentialControlRegion(f.target, setupRequiresCredential(f.target))
		})
		__tui_2.AddChild(__tui_3)
		__tui_0.AddChild(__tui_2)
	}
	if shouldRenderCredentialHeaderRow(f.target) {
		__tui_4 := app.Mount(f, 2, func() tui.Component {
			return CredentialHeaderControl(f.target)
		})
		__tui_0.AddChild(__tui_4)
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (f *customProviderForm) updatePropsFields(fresh tui.Component) {
	ff, ok := fresh.(*customProviderForm)
	if !ok {
		return
	}
	f.target = ff.target
}

func (f *customProviderForm) UpdateProps(fresh tui.Component) {
	f.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*customProviderForm)(nil)
