// Code generated by tui generate. DO NOT EDIT.
// Source: provider_zai.gsx

package target_config

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
	"github.com/swobuforge/swobu/internal/routing"
)

type zaiProviderForm struct{ target *TargetConfig }

func ZAIProviderForm(w *TargetConfig) tui.Component { return &zaiProviderForm{target: w} }

func zaiAccessDisplay(raw string) string {
	access, err := routing.ParseZAIAccess(raw)
	if err != nil {
		return "required"
	}
	return access.Label()
}

func ZAIAccessPicker(w *TargetConfig, backout func()) *ui.SearchPicker {
	options := routing.ZAIAccesses()
	items := make([]ui.SearchOption, 0, len(options))
	for _, option := range options {
		items = append(items, ui.SearchOption{ID: string(option), Label: option.Label()})
	}
	picker := ui.NewSearchPicker(TargetAddMountKey(w, "zai-access-picker"), "access", items, func(selection ui.Selection) {
		w.SelectZAIAccess(selection.Value)
		if backout != nil {
			backout()
		}
	}, func() {
		if backout != nil {
			backout()
		}
	})
	picker.AutoFocus = true
	return picker
}

func ZAIAccessSelect(w *TargetConfig) *ui.Select {
	raw := strings.TrimSpace(w.Draft.Get().ZAIAccess)
	action := "change ↵"
	if raw == "" {
		action = "choose ↵"
	}
	return ui.NewSelect(ui.SelectProps{
		ID:        TargetAddMountKey(w, "zai-access"),
		Label:     "access",
		Value:     zaiAccessDisplay(raw),
		Action:    action,
		AutoFocus: raw == "",
		CanEnter:  func() bool { return true },
		Body:      func(backout func()) tui.Component { return ZAIAccessPicker(w, backout) },
	})
}

func (f *zaiProviderForm) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := app.Mount(f, 0, func() tui.Component {
		return ZAIAccessSelect(f.target)
	})
	__tui_0.AddChild(__tui_1)
	if strings.TrimSpace(f.target.Draft.Get().ZAIAccess) != "" {
		__tui_2 := tui.New(
			tui.WithWidthPercent(100.00),
		)
		__tui_3 := app.Mount(f, tui.MountKey(1, credentialRegionKey(f.target)), func() tui.Component {
			return CredentialControlRegion(f.target, setupRequiresCredential(f.target))
		})
		__tui_2.AddChild(__tui_3)
		__tui_0.AddChild(__tui_2)
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (f *zaiProviderForm) updatePropsFields(fresh tui.Component) {
	ff, ok := fresh.(*zaiProviderForm)
	if !ok {
		return
	}
	f.target = ff.target
}

func (f *zaiProviderForm) UpdateProps(fresh tui.Component) {
	f.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*zaiProviderForm)(nil)
