// Code generated by tui generate. DO NOT EDIT.
// Source: provider_chatgpt.gsx

package target_config

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
)

type chatGPTProviderForm struct{ target *TargetConfig }

type chatGPTAuthModeMenu struct {
	target         *TargetConfig
	backout        func()
	replaceSession bool
}

type authCodeCopyFeedback struct {
	Message string
	Tone    ui.Tone
}

func ChatGPTProviderForm(w *TargetConfig) tui.Component { return &chatGPTProviderForm{target: w} }

func ChatGPTAuthControl(w *TargetConfig) *ui.Select {
	_, label := w.interactiveAuthMode()
	return ui.NewSelect(ui.SelectProps{
		ID:        TargetAddMountKey(w, "auth-mode"),
		Label:     "authentication",
		Value:     label,
		Action:    "choose ↵",
		AutoFocus: true,
		Body: func(backout func()) tui.Component {
			return &chatGPTAuthModeMenu{target: w, backout: backout}
		},
	})
}

func ChatGPTPendingAuthControl(w *TargetConfig) *ui.Select {
	return ui.NewSelect(ui.SelectProps{
		ID:     TargetAddMountKey(w, "auth-mode-pending"),
		Label:  "authentication",
		Value:  chatGPTAuthModeLabel(w),
		Action: "change ↵",
		Body: func(backout func()) tui.Component {
			return &chatGPTAuthModeMenu{target: w, backout: backout, replaceSession: true}
		},
	})
}

func (m *chatGPTAuthModeMenu) KeyMap() tui.KeyMap {
	return ui.BackScope(func() bool { return true }, m.backout)
}

func (m *chatGPTAuthModeMenu) choose(mode chatGPTAuthMode) {
	m.backout()
	if m.replaceSession {
		m.target.replaceInteractiveAuth(mode)
		return
	}
	m.target.ChatGPTAuthMode.Set(mode)
	m.target.startInteractiveAuth()
}

func ChatGPTAuthModeOption(m *chatGPTAuthModeMenu, mode chatGPTAuthMode) *ui.SelectableRow {
	action := "sign in ↵"
	if m.replaceSession {
		action = "switch ↵"
	}
	row := ui.NewSelectableRow(
		TargetAddMountKey(m.target, "auth-mode-"+mode.requestValue()),
		"",
		mode.label(),
		action,
		func() { m.choose(mode) },
	)
	row.AutoFocus = mode == m.target.ChatGPTAuthMode.Get()
	return row
}

func chatGPTAuthModeLabel(w *TargetConfig) string {
	_, label := w.interactiveAuthMode()
	if label == "" {
		label = "browser login"
	}
	return label
}

func chatGPTAuthURL(w *TargetConfig) string {
	url := ""
	if session := w.AuthSession.Get(); session.SessionID != "" {
		url = session.AuthorizeURL
	}
	return url
}

func ChatGPTAuthOpenBrowser(w *TargetConfig) *ui.SelectableRow {
	url := chatGPTAuthURL(w)
	return ui.NewSelectableRow(TargetAddMountKey(w, "auth-open"), "login URL", "", "open ↵", func() {
		if err := ui.OpenURL(url); err != nil {
			w.AuthBrowserError.Set("browser could not open")
			return
		}
		w.AuthBrowserError.Set("")
	})
}

func ChatGPTAuthStatus(w *TargetConfig) *ui.SelectableRow {
	row := ui.NewSelectableRow(TargetAddMountKey(w, "auth-status"), "status", "waiting for login", "refresh ↵", w.RefreshAuthSession)
	row.AutoFocus = true
	return row
}

func ChatGPTAuthCancel(w *TargetConfig) *ui.SelectableRow {
	return ui.NewSelectableRow(TargetAddMountKey(w, "auth-cancel"), "cancel", "", "cancel ↵", w.CancelAuthSession)
}

func ChatGPTAuthSignedIn(w *TargetConfig) *ui.SelectableRow {
	row := ui.NewSelectableRow(TargetAddMountKey(w, "auth-signed-in"), "authentication", "signed in", "reconnect ↵", w.startInteractiveAuth)
	row.AutoFocus = false
	return row
}

func ChatGPTAuthFailed(w *TargetConfig) *ui.SelectableRow {
	row := ui.NewSelectableRow(TargetAddMountKey(w, "auth-failed"), "authentication", "failed", "retry ↵", w.startInteractiveAuth)
	row.ValueTone = ui.ToneFailure
	row.AutoFocus = true
	return row
}

func ChatGPTAuthUserCode(w *TargetConfig) *ui.SelectableRow {
	code := strings.TrimSpace(w.AuthSession.Get().UserCode)
	feedback := w.AuthCodeCopy.Get()
	action := "copy ↵"
	if feedback.Tone == ui.ToneAccent {
		action = "copied"
	}
	if feedback.Tone == ui.ToneWarning || feedback.Tone == ui.ToneFailure {
		action = "retry ↵"
	}
	row := ui.CopyPasteRowComponent(TargetAddMountKey(w, "auth-code"), "code", code, action, func() ui.ClipboardResult {
		return ui.CopyToClipboard(code)
	}, w.setAuthCodeCopyResult)
	return row
}

func (f *chatGPTProviderForm) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if targetAuthPending(f.target) {
		__tui_1 := tui.New()
		__tui_2 := app.Mount(f, 0, func() tui.Component {
			return ChatGPTPendingAuthControl(f.target)
		})
		__tui_1.AddChild(__tui_2)
		__tui_3 := app.Mount(f, 1, func() tui.Component {
			return ChatGPTAuthOpenBrowser(f.target)
		})
		__tui_1.AddChild(__tui_3)
		if f.target.AuthBrowserError.Get() != "" {
			__tui_4 := tui.New(
				tui.WithWidthPercent(100.00),
				tui.WithPaddingTRBL(0, 0, 0, 3),
				tui.WithTextStyle(ui.ToneStyle(ui.ToneFailure)),
			)
			__tui_5 := app.Mount(f, 2, func() tui.Component {
				return FlowText(f.target.AuthBrowserError.Get())
			})
			__tui_4.AddChild(__tui_5)
			__tui_1.AddChild(__tui_4)
		}
		__tui_6 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		__tui_7 := ChatGPTAuthURLText(f.target)
		__tui_6.AddChild(__tui_7.Root)
		__tui_1.AddChild(__tui_6)
		if strings.TrimSpace(f.target.AuthSession.Get().UserCode) != "" {
			__tui_8 := app.Mount(f, 3, func() tui.Component {
				return ChatGPTAuthUserCode(f.target)
			})
			__tui_1.AddChild(__tui_8)
			if feedback := f.target.AuthCodeCopy.Get(); feedback.Tone == ui.ToneWarning || feedback.Tone == ui.ToneFailure {
				__tui_9 := tui.New(
					tui.WithWidthPercent(100.00),
					tui.WithPaddingTRBL(0, 0, 0, 3),
					tui.WithTextStyle(ui.ToneStyle(feedback.Tone)),
				)
				__tui_10 := app.Mount(f, 4, func() tui.Component {
					return FlowText(feedback.Message)
				})
				__tui_9.AddChild(__tui_10)
				__tui_1.AddChild(__tui_9)
			}
		}
		__tui_11 := app.Mount(f, 5, func() tui.Component {
			return ChatGPTAuthStatus(f.target)
		})
		__tui_1.AddChild(__tui_11)
		__tui_12 := app.Mount(f, 6, func() tui.Component {
			return ChatGPTAuthCancel(f.target)
		})
		__tui_1.AddChild(__tui_12)
		__tui_0.AddChild(__tui_1)
	} else if targetAuthFailed(f.target) {
		__tui_13 := app.Mount(f, 7, func() tui.Component {
			return ChatGPTAuthFailed(f.target)
		})
		__tui_0.AddChild(__tui_13)
	} else if targetUsesInteractiveAuth(f.target) && strings.TrimSpace(f.target.Draft.Get().CredentialRef) == "" {
		__tui_14 := app.Mount(f, 8, func() tui.Component {
			return ChatGPTAuthControl(f.target)
		})
		__tui_0.AddChild(__tui_14)
	} else if strings.TrimSpace(f.target.Draft.Get().CredentialRef) != "" {
		__tui_15 := app.Mount(f, 9, func() tui.Component {
			return ChatGPTAuthSignedIn(f.target)
		})
		__tui_0.AddChild(__tui_15)
	}

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (f *chatGPTProviderForm) updatePropsFields(fresh tui.Component) {
	ff, ok := fresh.(*chatGPTProviderForm)
	if !ok {
		return
	}
	f.target = ff.target
}

func (f *chatGPTProviderForm) UpdateProps(fresh tui.Component) {
	f.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*chatGPTProviderForm)(nil)

func (m *chatGPTAuthModeMenu) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := app.Mount(m, 0, func() tui.Component {
		return ChatGPTAuthModeOption(m, chatGPTAuthBrowser)
	})
	__tui_0.AddChild(__tui_1)
	__tui_2 := app.Mount(m, 1, func() tui.Component {
		return ChatGPTAuthModeOption(m, chatGPTAuthDevice)
	})
	__tui_0.AddChild(__tui_2)

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (m *chatGPTAuthModeMenu) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*chatGPTAuthModeMenu)
	if !ok {
		return
	}
	m.target = f.target
	m.replaceSession = f.replaceSession
}

func (m *chatGPTAuthModeMenu) UpdateProps(fresh tui.Component) {
	m.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*chatGPTAuthModeMenu)(nil)

type ChatGPTAuthURLTextView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ChatGPTAuthURLTextView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ChatGPTAuthURLTextView) GetRoot() *tui.Element { return v.Root }

func (v *ChatGPTAuthURLTextView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ChatGPTAuthURLTextView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ChatGPTAuthURLTextView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ChatGPTAuthURLTextView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ChatGPTAuthURLTextView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ChatGPTAuthURLTextView)(nil)

var _ tui.AppUnbinder = (*ChatGPTAuthURLTextView)(nil)

var _ tui.PropsUpdater = (*ChatGPTAuthURLTextView)(nil)

func ChatGPTAuthURLText(w *TargetConfig) *ChatGPTAuthURLTextView {
	var view ChatGPTAuthURLTextView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithPaddingTRBL(0, 0, 0, 2),
	)
	__tui_1 := FlowText(chatGPTAuthURL(w))
	__tui_0.AddChild(__tui_1.Root)

	watchers = append(watchers, __tui_1.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_1).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_1).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = ChatGPTAuthURLTextView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*chatGPTAuthModeMenu)(nil)
)
