// Code generated by tui generate. DO NOT EDIT.
// Source: provider_http.gsx

package target_config

import (
	tui "github.com/grindlemire/go-tui"
)

type httpProviderForm struct{ target *TargetConfig }

func HTTPProviderForm(w *TargetConfig) tui.Component { return &httpProviderForm{target: w} }

func (f *httpProviderForm) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if shouldRenderEndpointRow(f.target) {
		__tui_1 := app.Mount(f, 0, func() tui.Component {
			return EndpointInput(f.target, setupRequiresLocator(f.target))
		})
		__tui_0.AddChild(__tui_1)
	}
	if credential, ok := ambientOrReferenceCredential(f.target); ok {
		__tui_2 := tui.New(
			tui.WithWidthPercent(100.00),
		)
		__tui_3 := app.Mount(f, tui.MountKey(1, credentialRegionKey(f.target)), func() tui.Component {
			return AmbientOrReferenceAuthentication(ambientOrReferenceAuthenticationProps(f.target, credential))
		})
		__tui_2.AddChild(__tui_3)
		__tui_0.AddChild(__tui_2)
	} else if genericCredentialRowVisible(f.target) {
		__tui_4 := tui.New(
			tui.WithWidthPercent(100.00),
		)
		__tui_5 := app.Mount(f, tui.MountKey(2, credentialRegionKey(f.target)), func() tui.Component {
			return CredentialControlRegion(f.target, setupRequiresCredential(f.target))
		})
		__tui_4.AddChild(__tui_5)
		__tui_0.AddChild(__tui_4)
	}

	return __tui_0
}

func (f *httpProviderForm) UpdateProps(fresh tui.Component) {
	ff, ok := fresh.(*httpProviderForm)
	if !ok {
		return
	}
	f.target = ff.target
}

var _ tui.PropsUpdater = (*httpProviderForm)(nil)
