// Code generated by tui generate. DO NOT EDIT.
// Source: provider_bedrock.gsx

package target_config

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/readmodel"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
	"github.com/swobuforge/swobu/internal/domain/credentialref"
	"github.com/swobuforge/swobu/internal/domain/protocolkind"
	"github.com/swobuforge/swobu/internal/profile"
)

type bedrockProviderForm struct{ target *TargetConfig }

type bedrockAuthenticationMenu struct {
	target  *TargetConfig
	backout func()
	// chooser is stable mounted interaction state. Keeping its identity in
	// reactive state prevents generated prop reconciliation from replacing an
	// open child editor with callbacks bound to a discarded parent menu.
	chooser  *tui.State[*credentialRow]
	choosing *tui.State[bool]
}

func newBedrockAuthenticationMenu(w *TargetConfig, backout func()) *bedrockAuthenticationMenu {
	row := newCredentialRow(w, false)
	row.props.Apply = func(ref string) { w.changeCredentialRef(strings.TrimSpace(ref)); backout() }
	menu := &bedrockAuthenticationMenu{target: w, backout: backout, chooser: tui.NewState(row), choosing: tui.NewState(false)}
	row.stage.Set(credStageMenu)
	return menu
}

func (m *bedrockAuthenticationMenu) BindApp(app *tui.App) {
	m.bindAppFields(app)
	m.chooser.Get().BindApp(app)
}

func (m *bedrockAuthenticationMenu) UnbindApp() {}

func (m *bedrockAuthenticationMenu) KeyMap() tui.KeyMap {
	return ui.BackScope(func() bool { return true }, func() {
		if m.choosing.Get() {
			if m.chooser.Get().stage.Get() != credStageMenu {
				m.chooser.Get().stage.Set(credStageMenu)
				return
			}
			m.choosing.Set(false)
			return
		}
		m.backout()
	})
}

func BedrockAuthenticationField(w *TargetConfig) *ui.Select {
	ref := strings.TrimSpace(w.Draft.Get().CredentialRef)
	value := "AWS identity"
	if ref == "" {
		if evidence := w.catalogResult().BedrockAuthentication.AWSIdentity; evidence != nil && evidence.State == "resolved" {
			value = bedrockAWSIdentitySummary(*evidence)
		}
		if w.catalogResult().BedrockAuthentication.FailureStage == "authentication" {
			value = "AWS identity unavailable"
		}
	} else {
		value = "Bedrock API key · " + bedrockCredentialSource(ref)
		if w.catalogResult().BedrockAuthentication.FailureStage == "authentication" {
			value = "Bedrock API key unavailable"
		}
	}
	return ui.NewSelect(ui.SelectProps{ID: TargetAddMountKey(w, "bedrock-authentication"), Label: "authentication", Value: value, Detail: BedrockAuthenticationDetail(w), Action: "manage ↵", Body: func(backout func()) tui.Component { return newBedrockAuthenticationMenu(w, backout) }})
}

func bedrockCredentialSource(ref string) string {
	return credentialSourceDisplay(credentialref.Parse(ref))
}

func bedrockCredentialDetail(ref string) string {
	parsed := credentialref.Parse(ref)
	_, detail, ok := strings.Cut(parsed.String(), ":")
	if !ok {
		return parsed.String()
	}
	return detail
}

func BedrockRefreshIdentityOption(m *bedrockAuthenticationMenu) *ui.SelectableRow {
	value, action := "refresh identity", "refresh ↵"
	return ui.NewSelectableRow(TargetAddMountKey(m.target, "refresh-identity"), "", value, action, m.target.RefreshBedrockIdentity)
}

func BedrockUseAPIKeyOption(m *bedrockAuthenticationMenu) *ui.SelectableRow {
	return ui.NewSelectableRow(TargetAddMountKey(m.target, "use-api-key"), "", "use Bedrock API key", "select ↵", func() { m.choosing.Set(true) })
}

func BedrockChangeCredentialOption(m *bedrockAuthenticationMenu) *ui.SelectableRow {
	return ui.NewSelectableRow(TargetAddMountKey(m.target, "change-api-key"), "", "change credential", "enter ↵", func() { m.choosing.Set(true) })
}

func BedrockUseAWSIdentityOption(m *bedrockAuthenticationMenu) *ui.SelectableRow {
	return ui.NewSelectableRow(TargetAddMountKey(m.target, "use-aws-identity"), "", "use AWS identity", "select ↵", func() { m.target.changeCredentialRef(""); m.backout() })
}

func BedrockProviderForm(w *TargetConfig) tui.Component { return &bedrockProviderForm{target: w} }

func bedrockReadiness(w *TargetConfig, base providerSetupState) providerSetupState {
	setup := base
	setup.CredentialRequired = false
	region := strings.TrimSpace(w.Draft.Get().Locator)
	if region == "" {
		setup.Status = setupMissingLocator
		return setup
	}
	setup.Status = setupReady
	return setup
}

func (w *TargetConfig) IsBedrockFlow() bool {
	return profile.ProviderID(w.Draft.Get().ProviderSpec) == profile.ProviderSpecBedrock
}

func BedrockEndpointRow(w *TargetConfig) *ui.EditableRow {
	row := ui.NewEditableRow(TargetAddMountKey(w, "bedrock-endpoint"), "API URL", w.BaseURL)
	row.ViewAction = "edit ↵"
	row.EditAction = "save ↵"
	row.OpenAtStart = true
	w.syncBedrockEndpointRow(row)
	row.OnSubmit = func(raw string) {
		// Submitted input is validated transactionally. Invalid input remains in
		// the shared row's private editor draft; valid input is canonicalized into
		// the target draft's one explicit endpoint fact.
		if _, err := profile.ResolveBedrockEndpoint(raw, strings.TrimSpace(w.Draft.Get().Locator), bedrockEndpointProtocolKind(w)); err != nil {
			return
		}
		resolution, _ := profile.ResolveBedrockEndpoint(raw, strings.TrimSpace(w.Draft.Get().Locator), bedrockEndpointProtocolKind(w))
		w.Draft.Update(func(d readmodel.TargetDraft) readmodel.TargetDraft {
			d.Endpoint = resolution.BaseURL
			return d
		})
		w.BaseURL.Set(resolution.BaseURL)
		w.Error.Set("")
		w.CommitEdit(w.actionContext())
	}
	row.CloseAfterSubmit = func() bool {
		_, err := profile.ResolveBedrockEndpoint(w.BaseURL.Get(), strings.TrimSpace(w.Draft.Get().Locator), bedrockEndpointProtocolKind(w))
		return err == nil
	}
	row.OnClose = func() {
		w.BaseURL.Set(strings.TrimSpace(w.Draft.Get().Endpoint))
	}
	return row
}

func (w *TargetConfig) syncBedrockEndpointRow(row *ui.EditableRow) {
	validation, text := bedrockEndpointValidation(w.BaseURL.Get(), strings.TrimSpace(w.Draft.Get().Locator), bedrockEndpointProtocolKind(w))
	row.Validation = validation
	row.ValidationText = text
}

func bedrockEndpointProtocolKind(w *TargetConfig) protocolkind.ProtocolKind {
	draft := w.Draft.Get()
	if kind, ok := profile.ProviderProtocolKind(draft.ProviderSpec, draft.ProviderProtocol); ok {
		return kind
	}
	return protocolkind.ProtocolKind("")
}

func bedrockEndpointValidation(value, region string, kind protocolkind.ProtocolKind) (ui.EditableRowValidation, string) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ui.EditableRowValidationRequired, "Paste the API URL shown by AWS."
	}
	resolution, err := profile.ResolveBedrockEndpoint(trimmed, region, kind)
	if err != nil {
		return ui.EditableRowValidationInvalid, err.Error()
	}
	if resolution.InputWasComplete {
		return ui.EditableRowValidationNone, "Complete request URL normalized to its API base."
	}
	return ui.EditableRowValidationNone, "Explicit API URL."
}

func BedrockRegionControl(w *TargetConfig) *ui.Select {
	region := strings.TrimSpace(w.Draft.Get().Locator)
	value, action := profile.BedrockMantleRegionLabel(region), "change ↵"
	if region == "" {
		value, action = "required", "choose ↵"
	}
	return ui.NewSelect(ui.SelectProps{
		ID: TargetAddMountKey(w, "bedrock-region"), Label: "region", Value: value, Action: action,
		AutoFocus: w.setupState().RequiresLocator() && region == "",
		Body:      func(backout func()) tui.Component { return BedrockRegionPicker(w, backout) },
	})
}

func BedrockAuthenticationDetail(w *TargetConfig) string {
	if ref := strings.TrimSpace(w.Draft.Get().CredentialRef); ref != "" {
		if evidence := w.catalogResult().BedrockAuthentication; evidence.FailureStage == "authentication" {
			if strings.TrimSpace(evidence.Error) != "" {
				return strings.TrimSpace(evidence.Error)
			}
			return "Bedrock API key could not be resolved."
		}
		return bedrockCredentialDetail(ref)
	}
	catalog := w.catalogResult()
	diagnostics := catalog.BedrockAuthentication
	if diagnostics.FailureStage == "authentication" && strings.TrimSpace(diagnostics.Error) != "" {
		return strings.TrimSpace(diagnostics.Error)
	}
	if diagnostics.AWSIdentity == nil {
		return ""
	}
	switch diagnostics.AWSIdentity.State {
	case "resolved":
		return diagnostics.AWSIdentity.ARN
	case "credentials_missing":
		return "No AWS credentials found."
	case "identity_probe_failed":
		return strings.TrimSpace(diagnostics.AWSIdentity.Error)
	default:
		return ""
	}
}

func bedrockAWSIdentitySummary(identity readmodel.AWSIdentityReadModel) string {
	compact := compactAWSIdentity(identity.ARN, identity.Account)
	if compact == "" {
		return "AWS identity"
	}
	return "AWS identity · " + compact
}

func compactAWSIdentity(arn, account string) string {
	name := ""
	for _, marker := range []string{"assumed-role/", "role/", "user/"} {
		if _, tail, ok := strings.Cut(arn, marker); ok {
			name = strings.SplitN(tail, "/", 2)[0]
			break
		}
	}
	if strings.TrimSpace(account) == "" {
		return name
	}
	if name == "" {
		return account
	}
	return name + " · " + account
}

func BedrockRegionPicker(w *TargetConfig, backout func()) *ui.SearchPicker {
	regions := profile.BedrockMantleRegions()
	opts := make([]ui.SearchOption, len(regions))
	for i, region := range regions {
		opts[i] = ui.SearchOption{ID: region.ID, Label: region.Label, Keywords: append([]string{region.ID}, region.Keywords...)}
	}
	picker := ui.NewSearchPicker(TargetAddMountKey(w, "bedrock-region-picker"), "region", opts, func(sel ui.Selection) {
		w.SelectBedrockRegion(sel.Value)
		if backout != nil {
			backout()
		}
	}, func() {
		if backout != nil {
			backout()
		}
	})
	picker.AutoFocus = true
	return picker
}

func (f *bedrockProviderForm) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := app.Mount(f, 0, func() tui.Component {
		return BedrockRegionControl(f.target)
	})
	__tui_0.AddChild(__tui_1)
	__tui_2 := app.Mount(f, 1, func() tui.Component {
		return BedrockAuthenticationField(f.target)
	})
	__tui_0.AddChild(__tui_2)

	return __tui_0
}

func (f *bedrockProviderForm) UpdateProps(fresh tui.Component) {
	ff, ok := fresh.(*bedrockProviderForm)
	if !ok {
		return
	}
	f.target = ff.target
}

var _ tui.PropsUpdater = (*bedrockProviderForm)(nil)

func (m *bedrockAuthenticationMenu) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if m.choosing.Get() {
		__tui_1 := app.Mount(m, 0, func() tui.Component {
			return CredentialChooser(m.chooser.Get())
		})
		__tui_0.AddChild(__tui_1)
	} else if strings.TrimSpace(m.target.Draft.Get().CredentialRef) == "" {
		if detail := BedrockAuthenticationDetail(m.target); detail != "" {
			__tui_2 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_3 := app.Mount(m, 1, func() tui.Component {
				return FlowText(detail)
			})
			__tui_2.AddChild(__tui_3)
			__tui_0.AddChild(__tui_2)
		}
		__tui_4 := app.Mount(m, 2, func() tui.Component {
			return BedrockRefreshIdentityOption(m)
		})
		__tui_0.AddChild(__tui_4)
		__tui_5 := app.Mount(m, 3, func() tui.Component {
			return BedrockUseAPIKeyOption(m)
		})
		__tui_0.AddChild(__tui_5)
	} else {
		__tui_6 := tui.New(
			tui.WithWidthPercent(100.00),
		)
		__tui_7 := app.Mount(m, 4, func() tui.Component {
			return FlowText(bedrockCredentialDetail(m.target.Draft.Get().CredentialRef))
		})
		__tui_6.AddChild(__tui_7)
		__tui_0.AddChild(__tui_6)
		__tui_8 := app.Mount(m, 5, func() tui.Component {
			return BedrockChangeCredentialOption(m)
		})
		__tui_0.AddChild(__tui_8)
		__tui_9 := app.Mount(m, 6, func() tui.Component {
			return BedrockUseAWSIdentityOption(m)
		})
		__tui_0.AddChild(__tui_9)
	}

	return __tui_0
}

func (m *bedrockAuthenticationMenu) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*bedrockAuthenticationMenu)
	if !ok {
		return
	}
	m.target = f.target
}

var _ tui.PropsUpdater = (*bedrockAuthenticationMenu)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (m *bedrockAuthenticationMenu) bindAppFields(app *tui.App) {
	if m.chooser != nil {
		m.chooser.BindApp(app)
	}
	if m.choosing != nil {
		m.choosing.BindApp(app)
	}
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*bedrockAuthenticationMenu)(nil)
)
