// Code generated by tui generate. DO NOT EDIT.
// Source: tail.gsx

package target_config

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
	"github.com/swobuforge/swobu/internal/profile"
)

type catalogErrorClassification struct {
	summary    string
	showDetail bool
}

type targetTail struct{ root *TargetConfig }

func TargetModelLabel(w *TargetConfig) string {
	return profile.CatalogItemLabelForSpec(w.Draft.Get().ProviderSpec)
}

func setupAllowsModelChoice(w *TargetConfig) bool {
	if w.RequiresInteractiveAuth() && strings.TrimSpace(w.Draft.Get().CredentialRef) == "" {
		return false
	}
	return w.setupState().Ready() && !w.catalogLoading()
}

func ModelPicker(w *TargetConfig, backout func()) *ui.SearchPicker {
	catalog := w.catalogResult()
	opts := make([]ui.SearchOption, 0, len(catalog.Options))
	for _, option := range catalog.Options {
		opts = append(opts, ui.SearchOption{ID: option.ID, Label: option.Name})
	}
	picker := ui.NewSearchPicker(TargetAddMountKey(w, "model-picker"), TargetModelLabel(w), opts, func(sel ui.Selection) {
		w.selectModelByID(sel.Value)
		if backout != nil {
			backout()
		}
	}, func() {
		if backout != nil {
			backout()
		}
	})
	picker.AutoFocus = true
	picker.Mode = ui.SearchPickerOpen
	return picker
}

func classifyCatalogError(errText string) catalogErrorClassification {
	trimmed := strings.TrimSpace(errText)
	switch strings.ToLower(trimmed) {
	case "project not found":
		return catalogErrorClassification{summary: "project not found", showDetail: false}
	case "unauthorized":
		return catalogErrorClassification{summary: "unauthorized", showDetail: false}
	case "none found":
		return catalogErrorClassification{summary: "none found", showDetail: false}
	default:
		return catalogErrorClassification{summary: "catalog failed", showDetail: trimmed != ""}
	}
}

func ModelCatalogRetry(w *TargetConfig) *ui.SelectableRow {
	cls := classifyCatalogError(w.Catalog.Get().Err)
	row := ui.NewSelectableRow(TargetAddMountKey(w, "catalog-retry"), "models", cls.summary, "retry ↵", w.RetryCatalog)
	row.AutoFocus = !w.permitsManualModelRecovery()
	return row
}

func ModelCatalogLoading(w *TargetConfig) *ui.SelectableRow {
	row := ui.NewSelectableRow(TargetAddMountKey(w, "loading-catalog"), TargetModelLabel(w), "loading catalog…", "wait", nil)
	row.AutoFocus = true
	return row
}

func ModelSelectRow(w *TargetConfig) *ui.Select {
	model := strings.TrimSpace(w.SelectedModel.Get().ModelName)
	value, action := model, "change ↵"
	if value == "" {
		value, action = "required", "choose ↵"
	}
	return ui.NewSelect(ui.SelectProps{ID: TargetAddMountKey(w, "model-display"), Label: TargetModelLabel(w), Value: value, Action: action, AutoFocus: model == "" && setupAllowsModelChoice(w), CanEnter: func() bool { return setupAllowsModelChoice(w) }, Body: func(backout func()) tui.Component { return ModelPicker(w, backout) }})
}

func ManualModelInput(w *TargetConfig) *ui.EditableRow {
	model := strings.TrimSpace(w.SelectedModel.Get().ModelName)
	row := ui.NewEditableRow(TargetAddMountKey(w, "manual-model-input"), TargetModelLabel(w), tui.NewState(model))
	row.Placeholder = "required"
	row.ViewAction = "enter ↵"
	row.EditAction = "use ↵"
	row.StartEditing = model == "" && !w.permitsManualModelRecovery()
	row.AutoFocus = w.permitsManualModelRecovery()
	row.OnSubmit = func(value string) {
		w.selectModelByID(strings.TrimSpace(value))
	}
	row.CloseAfterSubmit = func() bool { return true }
	return row
}

func protocolDisplayLabel(w *TargetConfig, protocol string) string {
	for _, option := range w.CurrentProtocolOptions() {
		if option.ID == protocol {
			return option.Label
		}
	}
	return protocol
}

func SetupAllowsProtocolChoice(w *TargetConfig) bool {
	return strings.TrimSpace(w.SelectedModel.Get().ModelName) != "" && len(w.CurrentProtocolOptions()) > 1
}

func fixedProviderProtocol(w *TargetConfig) (string, bool) {
	options := w.CurrentProtocolOptions()
	if strings.TrimSpace(w.SelectedModel.Get().ModelName) == "" || len(options) != 1 {
		return "", false
	}
	return options[0].Label, true
}

func ProtocolPicker(w *TargetConfig, backout func()) *ui.SearchPicker {
	options := w.CurrentProtocolOptions()
	opts := make([]ui.SearchOption, len(options))
	for i, option := range options {
		opts[i] = ui.SearchOption{ID: option.ID, Label: option.Label, Keywords: option.Keywords}
	}
	picker := ui.NewSearchPicker(TargetAddMountKey(w, "protocol-picker"), "protocol", opts, func(sel ui.Selection) {
		w.selectProtocol(sel.Value)
		if backout != nil {
			backout()
		}
	}, func() {
		if backout != nil {
			backout()
		}
	})
	picker.AutoFocus = true
	return picker
}

func ProtocolSelect(w *TargetConfig) *ui.Select {
	protocol := strings.TrimSpace(w.Draft.Get().ProviderProtocol)
	options := w.CurrentProtocolOptions()
	modelSelected := strings.TrimSpace(w.SelectedModel.Get().ModelName) != ""
	required := modelSelected && protocol == "" && len(options) > 1
	value, action, enterable := protocol, "change ↵", true
	switch {
	case protocol == "":
		if len(options) == 1 {
			value, action, enterable = protocolDisplayLabel(w, options[0].ID), "fixed", false
		} else {
			value, action = "required", "choose ↵"
		}
	case len(options) == 1:
		value, action, enterable = protocolDisplayLabel(w, protocol), "fixed", false
	default:
		value = protocolDisplayLabel(w, protocol)
	}
	props := ui.SelectProps{ID: TargetAddMountKey(w, "protocol-display"), Label: "protocol", Value: value, Action: action, AutoFocus: required, CanEnter: func() bool { return enterable }}
	if enterable {
		props.Body = func(backout func()) tui.Component { return ProtocolPicker(w, backout) }
	}
	return ui.NewSelect(props)
}

func PlacementSelect(w *TargetConfig) *ui.Select {
	return ui.NewSelect(ui.SelectProps{ID: TargetAddMountKey(w, "placement-display"), Label: "routing", Value: w.Placement.Get().Summary(), Action: "change ↵", CanEnter: w.readyToCreate, Body: func(backout func()) tui.Component { return PlacementPicker(w, backout) }})
}

func PlacementPicker(w *TargetConfig, backout func()) *ui.ChoicePicker {
	opts := placementOptions(w.Route, w.mode, w.Target.ID)
	items := make([]ui.ChoiceOption, 0, len(opts))
	for _, opt := range opts {
		items = append(items, ui.ChoiceOption{ID: placementOptionID(opt), Label: opt.Summary()})
	}
	picker := ui.NewChoicePicker(TargetAddMountKey(w, "placement-picker"), items, placementOptionID(w.Placement.Get()), func(value string) {
		for _, opt := range opts {
			if placementOptionID(opt) == value {
				w.SelectPlacement(opt)
				break
			}
		}
		if backout != nil {
			backout()
		}
	}, func() {
		if backout != nil {
			backout()
		}
	})
	return picker
}

func canChangePlacement(w *TargetConfig) bool {
	if w.mode == targetConfigModeEdit {
		return routeWithoutTarget(w.Route, w.Target.ID).TargetCount() > 0
	}
	return w.Route.TargetCount() > 0
}

func TargetConfigHeader(w *TargetConfig) *ui.SelectableRow {
	return ui.NewSelectableRow(TargetAddMountKey(w, "target-config-parent"), "", targetConfigTitle(w), targetConfigParentAction(w), w.Close)
}

func CreateRetryControl(w *TargetConfig) *ui.SelectableRow {
	return ui.NewSelectableRow(TargetAddMountKey(w, "create-retry"), w.saveVerb(), "failed", "retry ↵", w.RetryCreate)
}

func DeleteControl(w *TargetConfig) *ui.SelectableRow {
	value, action := "target", "delete ↵"
	activate := func() { w.DeleteArmed.Set(true) }
	if w.DeleteArmed.Get() {
		value, action = "delete target?", "confirm ↵"
		activate = func() {
			if w.OnDeleteConfirmed == nil {
				w.Error.Set("target delete is not wired yet")
				return
			}
			if err := w.OnDeleteConfirmed(); err != nil {
				w.Error.Set(err.Error())
				return
			}
			w.Error.Set("")
			w.DeleteArmed.Set(false)
		}
	}
	return ui.NewSelectableRow(TargetAddMountKey(w, "delete"), "delete", value, action, activate)
}

func CreateControl(w *TargetConfig) *ui.SelectableRow {
	row := ui.NewSelectableRow(TargetAddMountKey(w, "create"), w.saveVerb(), "", w.saveVerb()+" ↵", func() { w.Create(w.actionContext()) })
	row.AutoFocus = true
	return row
}

func (w *TargetConfig) saveVerb() string {
	if w.mode == targetConfigModeEdit {
		return "save"
	}
	return "create"
}

func TargetConfigTail(w *TargetConfig) tui.Component { return &targetTail{root: w} }

type InertTargetFieldView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *InertTargetFieldView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *InertTargetFieldView) GetRoot() *tui.Element { return v.Root }

func (v *InertTargetFieldView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *InertTargetFieldView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *InertTargetFieldView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *InertTargetFieldView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*InertTargetFieldView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*InertTargetFieldView)(nil)

var _ tui.AppUnbinder = (*InertTargetFieldView)(nil)

var _ tui.PropsUpdater = (*InertTargetFieldView)(nil)

func InertTargetField(label string, value string, action string) *InertTargetFieldView {
	var view InertTargetFieldView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(label),
		tui.WithWidth(18),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(value),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_3)
	if action != "" {
		__tui_4 := tui.New(
			tui.WithText(action),
			tui.WithWidth(14),
		)
		__tui_0.AddChild(__tui_4)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = InertTargetFieldView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

func (t *targetTail) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if targetCatalogLoading(t.root) {
		__tui_1 := app.Mount(t, 0, func() tui.Component {
			return ModelCatalogLoading(t.root)
		})
		__tui_0.AddChild(__tui_1)
	} else if targetCatalogFailed(t.root) && t.root.IsBedrockFlow() {
		__tui_2 := InertTargetField(TargetModelLabel(t.root), "waiting for setup", "")
		__tui_0.AddChild(__tui_2.Root)
	} else if setupAllowsModelChoice(t.root) && t.root.usesManualModelInput() {
		__tui_3 := app.Mount(t, 1, func() tui.Component {
			return ManualModelInput(t.root)
		})
		__tui_0.AddChild(__tui_3)
	} else if targetCatalogFailed(t.root) && targetCatalogRetryable(t.root) {
		__tui_4 := app.Mount(t, 2, func() tui.Component {
			return ModelCatalogRetry(t.root)
		})
		__tui_0.AddChild(__tui_4)
		if cls := classifyCatalogError(t.root.Catalog.Get().Err); cls.showDetail {
			__tui_5 := tui.New(
				tui.WithWidthPercent(100.00),
				tui.WithPaddingTRBL(0, 0, 0, 20),
			)
			__tui_6 := app.Mount(t, 3, func() tui.Component {
				return FlowText(strings.TrimSpace(t.root.Catalog.Get().Err))
			})
			__tui_5.AddChild(__tui_6)
			__tui_0.AddChild(__tui_5)
		}
		if t.root.permitsManualModelRecovery() {
			__tui_7 := app.Mount(t, 4, func() tui.Component {
				return ManualModelInput(t.root)
			})
			__tui_0.AddChild(__tui_7)
		}
	} else if setupAllowsModelChoice(t.root) {
		__tui_8 := app.Mount(t, 5, func() tui.Component {
			return ModelSelectRow(t.root)
		})
		__tui_0.AddChild(__tui_8)
	} else {
		__tui_9 := InertTargetField(TargetModelLabel(t.root), "waiting for setup", "")
		__tui_0.AddChild(__tui_9.Root)
	}
	if SetupAllowsProtocolChoice(t.root) {
		__tui_10 := app.Mount(t, 6, func() tui.Component {
			return ProtocolSelect(t.root)
		})
		__tui_0.AddChild(__tui_10)
	} else if label, fixed := fixedProviderProtocol(t.root); fixed {
		__tui_11 := InertTargetField("protocol", label, "fixed")
		__tui_0.AddChild(__tui_11.Root)
	} else if len(t.root.CurrentProtocolOptions()) == 1 {
	} else {
		__tui_12 := InertTargetField("protocol", "waiting for "+TargetModelLabel(t.root), "")
		__tui_0.AddChild(__tui_12.Root)
	}
	if t.root.IsBedrockFlow() {
		__tui_13 := app.Mount(t, 7, func() tui.Component {
			return BedrockEndpointRow(t.root)
		})
		__tui_0.AddChild(__tui_13)
	}
	if canChangePlacement(t.root) {
		__tui_14 := app.Mount(t, 8, func() tui.Component {
			return PlacementSelect(t.root)
		})
		__tui_0.AddChild(__tui_14)
	}
	if t.root.mode == targetConfigModeEdit {
		__tui_15 := app.Mount(t, 9, func() tui.Component {
			return DeleteControl(t.root)
		})
		__tui_0.AddChild(__tui_15)
	} else if targetCreateFailed(t.root) {
		__tui_16 := app.Mount(t, 10, func() tui.Component {
			return CreateRetryControl(t.root)
		})
		__tui_0.AddChild(__tui_16)
	} else if targetReadyToCreate(t.root) {
		__tui_17 := app.Mount(t, 11, func() tui.Component {
			return CreateControl(t.root)
		})
		__tui_0.AddChild(__tui_17)
	} else {
		__tui_18 := InertTargetField(targetSaveVerb(t.root), "", "complete setup")
		__tui_0.AddChild(__tui_18.Root)
	}

	return __tui_0
}

func (t *targetTail) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*targetTail)
	if !ok {
		return
	}
	t.root = f.root
}

var _ tui.PropsUpdater = (*targetTail)(nil)
