// Code generated by tui generate. DO NOT EDIT.
// Source: view.gsx

package target_config

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
	"github.com/swobuforge/swobu/internal/profile"
)

func ProviderSelect(w *TargetConfig) *ui.SearchPicker {
	opts := make([]ui.SearchOption, len(w.providerOptions))
	for i, p := range w.providerOptions {
		opts[i] = ui.SearchOption{ID: p.ProviderSpec, Label: providerPickerLabel(p.ProviderSpec, p.DisplayName), Keywords: providerPickerKeywords(p)}
	}
	picker := ui.NewSearchPicker("provider-picker", "provider", opts, func(sel ui.Selection) {
		w.SelectProvider(sel.Value)
		w.ContinueSetup()
	}, func() { w.Back() })
	picker.AutoFocus = true
	return picker
}

func providerDisplay(w *TargetConfig) string {
	if setup := w.setupState(); setup.DisplayName != "" {
		return setup.DisplayName
	}
	spec := w.Draft.Get().ProviderSpec
	for _, option := range w.providerOptions {
		if option.ProviderSpec == spec {
			return option.DisplayName
		}
	}
	return spec
}

func ProviderSummary(w *TargetConfig) *ui.SelectableRow {
	action := "change ↵"
	activate := func() { w.ChangeProvider() }
	if w.mode == targetConfigModeEdit {
		action, activate = "fixed", nil
	}
	return ui.NewSelectableRow(TargetAddMountKey(w, "provider-display"), "provider", providerDisplay(w), action, activate)
}

func shouldRenderEndpointRow(w *TargetConfig) bool {
	setup := w.setupState()
	return setup.EndpointLabel != "" && setup.LocatorKind != profile.LocatorFixed
}

func EndpointInput(w *TargetConfig, autoFocus bool) *ui.EditableRow {
	label := strings.TrimSpace(w.setupState().EndpointLabel)
	if label == "" {
		label = "endpoint"
	}
	row := ui.NewEditableRow(TargetAddMountKey(w, "provider-setup-endpoint"), label, w.BaseURL)
	row.Placeholder, row.ViewAction, row.EditAction, row.AutoFocus = "enter "+label, "edit ↵", "save ↵", autoFocus
	row.OnSubmit = func(raw string) {
		w.BaseURL.Set(strings.TrimSpace(raw))
		w.invalidateCatalogEvidence()
		w.reseedInferredCredentialHeader()
		w.advanceFromSetup()
	}
	row.CloseAfterSubmit = func() bool { return !w.setupState().RequiresLocator() }
	return row
}

func (w *TargetConfig) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if w.IsOpen() {
		if !w.Embedded {
			__tui_1 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_2 := app.Mount(w, tui.MountKey(0, TargetAddMountKey(w, "target-config-parent")), func() tui.Component {
				return TargetConfigHeader(w)
			})
			__tui_1.AddChild(__tui_2)
			__tui_0.AddChild(__tui_1)
		}
		__tui_3 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		if strings.TrimSpace(w.Draft.Get().ProviderSpec) == "" {
			__tui_4 := app.Mount(w, 1, func() tui.Component {
				return ProviderSelect(w)
			})
			__tui_3.AddChild(__tui_4)
		} else {
			__tui_5 := app.Mount(w, 2, func() tui.Component {
				return ProviderSummary(w)
			})
			__tui_3.AddChild(__tui_5)
			if profile.ProviderID(w.Draft.Get().ProviderSpec) == profile.ProviderSpecAzure {
				__tui_6 := app.Mount(w, 3, func() tui.Component {
					return AzureProviderForm(w)
				})
				__tui_3.AddChild(__tui_6)
			} else if profile.ProviderID(w.Draft.Get().ProviderSpec) == profile.ProviderSpecCustom {
				__tui_7 := app.Mount(w, 4, func() tui.Component {
					return CustomProviderForm(w)
				})
				__tui_3.AddChild(__tui_7)
			} else if profile.ProviderID(w.Draft.Get().ProviderSpec) == profile.ProviderSpecBedrock {
				__tui_8 := app.Mount(w, 5, func() tui.Component {
					return BedrockProviderForm(w)
				})
				__tui_3.AddChild(__tui_8)
			} else if profile.ProviderID(w.Draft.Get().ProviderSpec) == profile.ProviderSpecChatGPT {
				__tui_9 := app.Mount(w, 6, func() tui.Component {
					return ChatGPTProviderForm(w)
				})
				__tui_3.AddChild(__tui_9)
			} else if profile.ProviderID(w.Draft.Get().ProviderSpec) == profile.ProviderSpecZAI {
				__tui_10 := app.Mount(w, 7, func() tui.Component {
					return ZAIProviderForm(w)
				})
				__tui_3.AddChild(__tui_10)
			} else {
				__tui_11 := app.Mount(w, 8, func() tui.Component {
					return HTTPProviderForm(w)
				})
				__tui_3.AddChild(__tui_11)
			}
			if w.ShouldRenderTargetTail() {
				__tui_12 := app.Mount(w, 9, func() tui.Component {
					return TargetConfigTail(w)
				})
				__tui_3.AddChild(__tui_12)
			}
			__tui_13 := app.Mount(w, 10, func() tui.Component {
				return TargetConfigError(w)
			})
			__tui_3.AddChild(__tui_13)
		}
		__tui_0.AddChild(__tui_3)
	}

	return __tui_0
}
