// Code generated by tui generate. DO NOT EDIT.
// Source: section.gsx

package routes

import (
	tui "github.com/grindlemire/go-tui"
)

func (s *SectionView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidthPercent(100.00),
	)
	__tui_2 := app.Mount(s, tui.MountKey(0, sectionHeaderKey(s)), func() tui.Component {
		return SectionHeaderComponent(s)
	})
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	if s.Expanded.Get() {
		__tui_3 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		if len(s.State.Routes) == 0 {
			__tui_4 := SectionInertRow("(no routes)", "", "")
			__tui_3.AddChild(__tui_4.Root)
		} else {
			for __idx_0, route := range s.State.Routes {
				_ = __idx_0
				__tui_5 := tui.New(
					tui.WithWidthPercent(100.00),
				)
				__tui_6 := app.Mount(s, tui.MountKey(1, routeMountKey(route)), func() tui.Component {
					return RouteRowComponent(s, route)
				})
				__tui_5.AddChild(__tui_6)
				__tui_3.AddChild(__tui_5)
				if s.isExpanded(route) {
					__tui_7 := tui.New(
						tui.WithWidthPercent(100.00),
						tui.WithPaddingTRBL(0, 0, 0, 3),
					)
					__tui_8 := tui.New(
						tui.WithWidthPercent(100.00),
					)
					__tui_9 := app.Mount(s, tui.MountKey(2, s.routeNameRowKey(route)), func() tui.Component {
						return RouteNameRowComponent(s, route)
					})
					__tui_8.AddChild(__tui_9)
					__tui_7.AddChild(__tui_8)
					if route.TargetCount() > 0 {
						__tui_10 := tui.New(
							tui.WithWidthPercent(100.00),
						)
						__tui_11 := app.Mount(s, tui.MountKey(3, s.routeDefaultRowKey(route)), func() tui.Component {
							return RouteDefaultRowComponent(s, route)
						})
						__tui_10.AddChild(__tui_11)
						__tui_7.AddChild(__tui_10)
					}
					__tui_12 := tui.New(
						tui.WithWidthPercent(100.00),
					)
					__tui_13 := app.Mount(s, tui.MountKey(4, s.shareRowKey(route)), func() tui.Component {
						return ShareRowComponent(s, route)
					})
					__tui_12.AddChild(__tui_13)
					__tui_7.AddChild(__tui_12)
					if route.Share != nil {
						__tui_14 := tui.New(
							tui.WithWidthPercent(100.00),
						)
						__tui_15 := app.Mount(s, tui.MountKey(5, s.shareRevokeRowKey(route)), func() tui.Component {
							return ShareRevokeRowComponent(s, route)
						})
						__tui_14.AddChild(__tui_15)
						__tui_7.AddChild(__tui_14)
					}
					for tierIdx, tierTargets := range groupedTargets(route) {
						_ = tierIdx
						__tui_16 := StepHeaderRow(tierHeaderText(tierIdx, len(tierTargets) > 1))
						__tui_7.AddChild(__tui_16.Root)
						__tui_17 := tui.New(
							tui.WithWidthPercent(100.00),
							tui.WithPaddingTRBL(0, 0, 0, 3),
						)
						for __idx_2, target := range tierTargets {
							_ = __idx_2
							if s.State.OpenTarget.Get() == target.ID {
								config := s.targetEditConfig(route, target)
								__tui_18 := tui.New(
									tui.WithWidthPercent(100.00),
								)
								__tui_19 := app.Mount(s, tui.MountKey(6, __idx_0, tierIdx, s.targetConfigKey(route, target.ID)), func() tui.Component {
									return TargetConfigComponent(config)
								})
								__tui_18.AddChild(__tui_19)
								__tui_17.AddChild(__tui_18)
							} else {
								__tui_20 := tui.New(
									tui.WithWidthPercent(100.00),
								)
								__tui_21 := app.Mount(s, tui.MountKey(7, __idx_0, tierIdx, targetMountKey(route, target)), func() tui.Component {
									return TargetRowComponent(s, route, target)
								})
								__tui_20.AddChild(__tui_21)
								__tui_17.AddChild(__tui_20)
							}
							if s.State.DeleteConfirmTarget.Get() == target.ID {
								__tui_22 := tui.New(
									tui.WithWidthPercent(100.00),
								)
								__tui_23 := app.Mount(s, tui.MountKey(8, __idx_0, tierIdx, "del:"+string(target.ID)), func() tui.Component {
									return TargetDeleteConfirmRow(s, route, target)
								})
								__tui_22.AddChild(__tui_23)
								__tui_17.AddChild(__tui_22)
							}
						}
						__tui_7.AddChild(__tui_17)
					}
					if s.State.AddTargetRoute.Get() == route.ID {
						config := s.targetAddConfig(route)
						__tui_24 := tui.New(
							tui.WithWidthPercent(100.00),
							tui.WithMarginTRBL(1, 0, 0, 0),
						)
						__tui_25 := app.Mount(s, tui.MountKey(9, targetAddMountKey(route)), func() tui.Component {
							return TargetConfigComponent(config)
						})
						__tui_24.AddChild(__tui_25)
						__tui_7.AddChild(__tui_24)
					} else {
						__tui_26 := tui.New(
							tui.WithWidthPercent(100.00),
							tui.WithMarginTRBL(1, 0, 0, 0),
						)
						__tui_27 := app.Mount(s, tui.MountKey(10, addTargetMountKey(route)), func() tui.Component {
							return AddTargetRowComponent(s, route)
						})
						__tui_26.AddChild(__tui_27)
						__tui_7.AddChild(__tui_26)
						__tui_28 := tui.New(
							tui.WithWidthPercent(100.00),
						)
						__tui_29 := app.Mount(s, tui.MountKey(11, s.routeDeleteRowKey(route)), func() tui.Component {
							return RouteDeleteRowComponent(s, route)
						})
						__tui_28.AddChild(__tui_29)
						__tui_7.AddChild(__tui_28)
					}
					__tui_3.AddChild(__tui_7)
				}
			}
		}
		__tui_30 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithMarginTRBL(1, 0, 0, 0),
		)
		__tui_3.AddChild(__tui_30)
		if s.DraftRoute != nil && s.DraftRoute.IsExpanded() {
			__tui_31 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_32 := app.Mount(s, tui.MountKey(12, "draft-route"), func() tui.Component {
				return DraftParentRowComponent(s)
			})
			__tui_31.AddChild(__tui_32)
			__tui_3.AddChild(__tui_31)
			__tui_33 := tui.New(
				tui.WithWidthPercent(100.00),
				tui.WithPaddingTRBL(0, 0, 0, 3),
			)
			__tui_34 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_35 := app.Mount(s, tui.MountKey(13, "draft-name"), func() tui.Component {
				return DraftNameRowComponent(s)
			})
			__tui_34.AddChild(__tui_35)
			__tui_33.AddChild(__tui_34)
			__tui_3.AddChild(__tui_33)
		}
		if s.DraftRoute == nil {
			__tui_36 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_37 := app.Mount(s, tui.MountKey(14, addRouteMountKey()), func() tui.Component {
				return AddRouteRowComponent(s)
			})
			__tui_36.AddChild(__tui_37)
			__tui_3.AddChild(__tui_36)
		}
		__tui_0.AddChild(__tui_3)
	}

	return __tui_0
}

type StepHeaderRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *StepHeaderRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *StepHeaderRowView) GetRoot() *tui.Element { return v.Root }

func (v *StepHeaderRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *StepHeaderRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *StepHeaderRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *StepHeaderRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*StepHeaderRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*StepHeaderRowView)(nil)

var _ tui.AppUnbinder = (*StepHeaderRowView)(nil)

var _ tui.PropsUpdater = (*StepHeaderRowView)(nil)

func StepHeaderRow(label string) *StepHeaderRowView {
	var view StepHeaderRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
		tui.WithMarginTRBL(1, 0, 0, 0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(label),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = StepHeaderRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type SectionInertRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SectionInertRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SectionInertRowView) GetRoot() *tui.Element { return v.Root }

func (v *SectionInertRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SectionInertRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SectionInertRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SectionInertRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SectionInertRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SectionInertRowView)(nil)

var _ tui.AppUnbinder = (*SectionInertRowView)(nil)

var _ tui.PropsUpdater = (*SectionInertRowView)(nil)

func SectionInertRow(label string, value string, action string) *SectionInertRowView {
	var view SectionInertRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(label),
		tui.WithWidth(18),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(value),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_3)
	if action != "" {
		__tui_4 := tui.New(
			tui.WithText(action),
			tui.WithWidth(14),
		)
		__tui_0.AddChild(__tui_4)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SectionInertRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
