// Code generated by tui generate. DO NOT EDIT.
// Source: section.gsx

package routes

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
)

func tierTargetRowClass(targetIndex int) string {
	if targetIndex == 0 {
		return "w-full mt-1"
	}
	return "w-full"
}

func (s *SectionView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidthPercent(100.00),
	)
	__tui_2 := app.Mount(s, tui.MountKey(0, "routes-header"), func() tui.Component {
		return SectionHeaderComponent(s)
	})
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	if s.Expanded.Get() {
		__tui_3 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		if len(s.State.Routes) == 0 {
			__tui_4 := SectionInertRow("(no routes)", "", "")
			__tui_3.AddChild(__tui_4.Root)
		} else {
			for __idx_0, route := range s.State.Routes {
				_ = __idx_0
				__tui_5 := tui.New(
					tui.WithWidthPercent(100.00),
				)
				__tui_6 := app.Mount(s, tui.MountKey(1, routeMountKey(route)), func() tui.Component {
					return RouteRowComponent(s, route)
				})
				__tui_5.AddChild(__tui_6)
				__tui_3.AddChild(__tui_5)
				if s.isExpanded(route) {
					__tui_7 := tui.New(
						tui.WithWidthPercent(100.00),
						tui.WithPaddingTRBL(0, 0, 0, 3),
					)
					__tui_8 := tui.New(
						tui.WithWidthPercent(100.00),
					)
					__tui_9 := app.Mount(s, tui.MountKey(2, s.routeNameRowKey(route)), func() tui.Component {
						return RouteNameRowComponent(s, route)
					})
					__tui_8.AddChild(__tui_9)
					__tui_7.AddChild(__tui_8)
					if route.TargetCount() > 0 {
						__tui_10 := tui.New(
							tui.WithWidthPercent(100.00),
						)
						__tui_11 := app.Mount(s, tui.MountKey(3, s.routeDefaultRowKey(route)), func() tui.Component {
							return RouteDefaultRowComponent(s, route)
						})
						__tui_10.AddChild(__tui_11)
						__tui_7.AddChild(__tui_10)
					}
					__tui_12 := tui.New(
						tui.WithWidthPercent(100.00),
					)
					__tui_13 := app.Mount(s, tui.MountKey(4, s.shareRowKey(route)), func() tui.Component {
						return ShareRowComponent(s, route)
					})
					__tui_12.AddChild(__tui_13)
					__tui_7.AddChild(__tui_12)
					if route.Share != nil {
						__tui_14 := tui.New(
							tui.WithWidthPercent(100.00),
						)
						__tui_15 := app.Mount(s, tui.MountKey(5, s.shareRevokeRowKey(route)), func() tui.Component {
							return ShareRevokeRowComponent(s, route)
						})
						__tui_14.AddChild(__tui_15)
						__tui_7.AddChild(__tui_14)
					}
					for tierIdx, tierTargets := range groupedTargets(route) {
						_ = tierIdx
						for targetIdx, target := range tierTargets {
							_ = targetIdx
							__tui_16 := tui.New()
							__tui_17 := app.Mount(s, tui.MountKey(6, __idx_0, tierIdx, targetMountKey(route, target)), func() tui.Component {
								return TargetControlComponent(s, route, target, tierIdx, targetIdx)
							})
							__tui_16.AddChild(__tui_17)
							__tui_7.AddChild(__tui_16)
						}
					}
					__tui_18 := tui.New(
						tui.WithWidthPercent(100.00),
						tui.WithMarginTRBL(1, 0, 0, 0),
					)
					__tui_19 := app.Mount(s, tui.MountKey(7, addTargetMountKey(route)), func() tui.Component {
						return AddTargetControlComponent(s, route)
					})
					__tui_18.AddChild(__tui_19)
					__tui_7.AddChild(__tui_18)
					if s.State.AddTargetRoute.Get() != route.ID {
						__tui_20 := tui.New(
							tui.WithWidthPercent(100.00),
						)
						__tui_21 := app.Mount(s, tui.MountKey(8, s.routeDeleteRowKey(route)), func() tui.Component {
							return RouteDeleteRowComponent(s, route)
						})
						__tui_20.AddChild(__tui_21)
						__tui_7.AddChild(__tui_20)
					}
					__tui_3.AddChild(__tui_7)
				}
			}
		}
		__tui_22 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithMarginTRBL(1, 0, 0, 0),
		)
		__tui_3.AddChild(__tui_22)
		if s.DraftRoute != nil && s.DraftRoute.IsExpanded() {
			__tui_23 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_24 := app.Mount(s, tui.MountKey(9, "draft-route"), func() tui.Component {
				return DraftParentRowComponent(s)
			})
			__tui_23.AddChild(__tui_24)
			__tui_3.AddChild(__tui_23)
			__tui_25 := tui.New(
				tui.WithWidthPercent(100.00),
				tui.WithPaddingTRBL(0, 0, 0, 3),
			)
			__tui_26 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_27 := app.Mount(s, tui.MountKey(10, "draft-name"), func() tui.Component {
				return DraftNameRowComponent(s)
			})
			__tui_26.AddChild(__tui_27)
			__tui_25.AddChild(__tui_26)
			__tui_3.AddChild(__tui_25)
		}
		if s.DraftRoute == nil {
			__tui_28 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_29 := app.Mount(s, tui.MountKey(11, addRouteMountKey()), func() tui.Component {
				return AddRouteRowComponent(s)
			})
			__tui_28.AddChild(__tui_29)
			__tui_3.AddChild(__tui_28)
		}
		__tui_0.AddChild(__tui_3)
	}

	return __tui_0
}

type TierContextRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *TierContextRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *TierContextRowView) GetRoot() *tui.Element { return v.Root }

func (v *TierContextRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *TierContextRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *TierContextRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *TierContextRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*TierContextRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*TierContextRowView)(nil)

var _ tui.AppUnbinder = (*TierContextRowView)(nil)

var _ tui.PropsUpdater = (*TierContextRowView)(nil)

func TierContextRow(label string, tone ui.Tone) *TierContextRowView {
	var view TierContextRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
		tui.WithMarginTRBL(1, 0, 0, 0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(label),
		tui.WithWidth(18),
		tui.WithTextStyle(ui.ToneStyle(tone)),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithFlexGrow(1),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = TierContextRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type SectionInertRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SectionInertRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SectionInertRowView) GetRoot() *tui.Element { return v.Root }

func (v *SectionInertRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SectionInertRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SectionInertRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SectionInertRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SectionInertRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SectionInertRowView)(nil)

var _ tui.AppUnbinder = (*SectionInertRowView)(nil)

var _ tui.PropsUpdater = (*SectionInertRowView)(nil)

func SectionInertRow(label string, value string, action string) *SectionInertRowView {
	var view SectionInertRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(label),
		tui.WithWidth(18),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(value),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_3)
	if action != "" {
		__tui_4 := tui.New(
			tui.WithText(action),
			tui.WithWidth(14),
		)
		__tui_0.AddChild(__tui_4)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SectionInertRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
