// Code generated by tui generate. DO NOT EDIT.
// Source: section.gsx

package routes

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
)

func tierTargetRowClass(targetIndex int) string {
	if targetIndex == 0 {
		return "w-full mt-1"
	}
	return "w-full"
}

func (s *SectionView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidthPercent(100.00),
	)
	__tui_2 := app.Mount(s, tui.MountKey(0, sectionHeaderKey(s)), func() tui.Component {
		return SectionHeaderComponent(s)
	})
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	if s.Expanded.Get() {
		__tui_3 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		if len(s.State.Routes) == 0 {
			__tui_4 := SectionInertRow("(no routes)", "", "")
			__tui_3.AddChild(__tui_4.Root)
		} else {
			for __idx_0, route := range s.State.Routes {
				_ = __idx_0
				__tui_5 := tui.New(
					tui.WithWidthPercent(100.00),
				)
				__tui_6 := app.Mount(s, tui.MountKey(1, routeMountKey(route)), func() tui.Component {
					return RouteRowComponent(s, route)
				})
				__tui_5.AddChild(__tui_6)
				__tui_3.AddChild(__tui_5)
				if s.isExpanded(route) {
					__tui_7 := tui.New(
						tui.WithWidthPercent(100.00),
						tui.WithPaddingTRBL(0, 0, 0, 3),
					)
					__tui_8 := tui.New(
						tui.WithWidthPercent(100.00),
					)
					__tui_9 := app.Mount(s, tui.MountKey(2, s.routeNameRowKey(route)), func() tui.Component {
						return RouteNameRowComponent(s, route)
					})
					__tui_8.AddChild(__tui_9)
					__tui_7.AddChild(__tui_8)
					if route.TargetCount() > 0 {
						__tui_10 := tui.New(
							tui.WithWidthPercent(100.00),
						)
						__tui_11 := app.Mount(s, tui.MountKey(3, s.routeDefaultRowKey(route)), func() tui.Component {
							return RouteDefaultRowComponent(s, route)
						})
						__tui_10.AddChild(__tui_11)
						__tui_7.AddChild(__tui_10)
					}
					__tui_12 := tui.New(
						tui.WithWidthPercent(100.00),
					)
					__tui_13 := app.Mount(s, tui.MountKey(4, s.shareRowKey(route)), func() tui.Component {
						return ShareRowComponent(s, route)
					})
					__tui_12.AddChild(__tui_13)
					__tui_7.AddChild(__tui_12)
					if route.Share != nil {
						__tui_14 := tui.New(
							tui.WithWidthPercent(100.00),
						)
						__tui_15 := app.Mount(s, tui.MountKey(5, s.shareRevokeRowKey(route)), func() tui.Component {
							return ShareRevokeRowComponent(s, route)
						})
						__tui_14.AddChild(__tui_15)
						__tui_7.AddChild(__tui_14)
					}
					for tierIdx, tierTargets := range groupedTargets(route) {
						_ = tierIdx
						for targetIdx, target := range tierTargets {
							_ = targetIdx
							if s.State.OpenTarget.Get() == target.ID {
								if targetIdx == 0 {
									__tui_16 := TierContextRow(tierLabel(tierIdx), tierTone(tierIdx))
									__tui_7.AddChild(__tui_16.Root)
								}
								config := s.targetEditConfig(route, target)
								__tui_17 := tui.New(
									tui.WithWidthPercent(100.00),
								)
								__tui_18 := app.Mount(s, tui.MountKey(6, __idx_0, tierIdx, s.targetConfigKey(route, target.ID)), func() tui.Component {
									return TargetConfigComponent(config)
								})
								__tui_17.AddChild(__tui_18)
								__tui_7.AddChild(__tui_17)
							} else {
								__tui_19 := tui.New()
								__tui_20 := app.Mount(s, tui.MountKey(7, __idx_0, tierIdx, targetMountKey(route, target)), func() tui.Component {
									return TargetRowComponent(s, route, target, tierIdx, targetIdx)
								})
								__tui_19.AddChild(__tui_20)
								__tui_7.AddChild(__tui_19)
							}
							if s.State.DeleteConfirmTarget.Get() == target.ID {
								__tui_21 := tui.New(
									tui.WithWidthPercent(100.00),
								)
								__tui_22 := app.Mount(s, tui.MountKey(8, __idx_0, tierIdx, "del:"+string(target.ID)), func() tui.Component {
									return TargetDeleteConfirmRow(s, route, target)
								})
								__tui_21.AddChild(__tui_22)
								__tui_7.AddChild(__tui_21)
							}
						}
					}
					if s.State.AddTargetRoute.Get() == route.ID {
						config := s.targetAddConfig(route)
						__tui_23 := tui.New(
							tui.WithWidthPercent(100.00),
							tui.WithMarginTRBL(1, 0, 0, 0),
						)
						__tui_24 := app.Mount(s, tui.MountKey(9, targetAddMountKey(route)), func() tui.Component {
							return TargetConfigComponent(config)
						})
						__tui_23.AddChild(__tui_24)
						__tui_7.AddChild(__tui_23)
					} else {
						__tui_25 := tui.New(
							tui.WithWidthPercent(100.00),
							tui.WithMarginTRBL(1, 0, 0, 0),
						)
						__tui_26 := app.Mount(s, tui.MountKey(10, addTargetMountKey(route)), func() tui.Component {
							return AddTargetRowComponent(s, route)
						})
						__tui_25.AddChild(__tui_26)
						__tui_7.AddChild(__tui_25)
						__tui_27 := tui.New(
							tui.WithWidthPercent(100.00),
						)
						__tui_28 := app.Mount(s, tui.MountKey(11, s.routeDeleteRowKey(route)), func() tui.Component {
							return RouteDeleteRowComponent(s, route)
						})
						__tui_27.AddChild(__tui_28)
						__tui_7.AddChild(__tui_27)
					}
					__tui_3.AddChild(__tui_7)
				}
			}
		}
		__tui_29 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithMarginTRBL(1, 0, 0, 0),
		)
		__tui_3.AddChild(__tui_29)
		if s.DraftRoute != nil && s.DraftRoute.IsExpanded() {
			__tui_30 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_31 := app.Mount(s, tui.MountKey(12, "draft-route"), func() tui.Component {
				return DraftParentRowComponent(s)
			})
			__tui_30.AddChild(__tui_31)
			__tui_3.AddChild(__tui_30)
			__tui_32 := tui.New(
				tui.WithWidthPercent(100.00),
				tui.WithPaddingTRBL(0, 0, 0, 3),
			)
			__tui_33 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_34 := app.Mount(s, tui.MountKey(13, "draft-name"), func() tui.Component {
				return DraftNameRowComponent(s)
			})
			__tui_33.AddChild(__tui_34)
			__tui_32.AddChild(__tui_33)
			__tui_3.AddChild(__tui_32)
		}
		if s.DraftRoute == nil {
			__tui_35 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_36 := app.Mount(s, tui.MountKey(14, addRouteMountKey()), func() tui.Component {
				return AddRouteRowComponent(s)
			})
			__tui_35.AddChild(__tui_36)
			__tui_3.AddChild(__tui_35)
		}
		__tui_0.AddChild(__tui_3)
	}

	return __tui_0
}

type TierContextRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *TierContextRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *TierContextRowView) GetRoot() *tui.Element { return v.Root }

func (v *TierContextRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *TierContextRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *TierContextRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *TierContextRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*TierContextRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*TierContextRowView)(nil)

var _ tui.AppUnbinder = (*TierContextRowView)(nil)

var _ tui.PropsUpdater = (*TierContextRowView)(nil)

func TierContextRow(label string, tone ui.Tone) *TierContextRowView {
	var view TierContextRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
		tui.WithMarginTRBL(1, 0, 0, 0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(label),
		tui.WithWidth(18),
		tui.WithTextStyle(ui.ToneStyle(tone)),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithFlexGrow(1),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = TierContextRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type SectionInertRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SectionInertRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SectionInertRowView) GetRoot() *tui.Element { return v.Root }

func (v *SectionInertRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SectionInertRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SectionInertRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SectionInertRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SectionInertRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SectionInertRowView)(nil)

var _ tui.AppUnbinder = (*SectionInertRowView)(nil)

var _ tui.PropsUpdater = (*SectionInertRowView)(nil)

func SectionInertRow(label string, value string, action string) *SectionInertRowView {
	var view SectionInertRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(label),
		tui.WithWidth(18),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(value),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_3)
	if action != "" {
		__tui_4 := tui.New(
			tui.WithText(action),
			tui.WithWidth(14),
		)
		__tui_0.AddChild(__tui_4)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SectionInertRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
