// Code generated by tui generate. DO NOT EDIT.
// Source: cockpit.gsx

package cockpit

import (
	"context"
	"time"

	tui "github.com/grindlemire/go-tui"
	help_page "github.com/swobuforge/swobu/internal/cockpit/pages/help"
	workspace_page "github.com/swobuforge/swobu/internal/cockpit/pages/workspace"
	"github.com/swobuforge/swobu/internal/cockpit/ports"
	"github.com/swobuforge/swobu/internal/cockpit/readmodel"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
)

const cockpitRefreshTimeout = 5 * time.Second

type Cockpit struct {
	Model          readmodel.CockpitReadModel
	ActiveTabIndex *tui.State[int]
	Notice         *tui.State[readmodel.Notice]
	BodyViewport   *ui.Viewport
	Reloader       *ModelReloader
	WorkspacePages map[readmodel.WorkspaceID]*workspace_page.PageView
	HelpPage       *help_page.PageView
	Context        context.Context
	WorkspacePorts ports.WorkspaceCommands
	WorkspaceQuery ports.WorkspaceQueries
}

type FlowTextView = ui.FlowTextView

func NewCockpit(model readmodel.CockpitReadModel) *Cockpit {
	return NewCockpitWithContext(model, context.Background(), nil, nil)
}

func NewCockpitWithContext(model readmodel.CockpitReadModel, ctx context.Context, query ports.WorkspaceQueries, commands ports.WorkspaceCommands) *Cockpit {
	if ctx == nil {
		ctx = context.Background()
	}
	model = ensureWorkspaceRegistry(model)
	activeTab := selectedTabIndex(model.Tabs)
	cockpit := &Cockpit{
		Model:          model,
		ActiveTabIndex: tui.NewState(activeTab),
		Notice:         tui.NewState(readmodel.Notice{}),
		BodyViewport:   &ui.Viewport{Ref: tui.NewRef(), ScrollY: tui.NewState(0), FollowFocused: true, MarginRows: 2},
		Reloader:       NewModelReloader(ctx, query, cockpitRefreshTimeout),
		HelpPage:       help_page.View(model.Help),
		Context:        ctx,
		WorkspacePorts: commands,
		WorkspaceQuery: query,
	}
	cockpit.WorkspacePages = cockpit.workspacePagesByTab(model)
	return cockpit
}

func (c *Cockpit) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnPreemptStop(tui.KeyCtrlC, c.quit),
		tui.OnPreemptStop(tui.KeyTab, c.activateNextTab),
		tui.OnPreemptStop(tui.KeyTab.Shift(), c.activatePreviousTab),
		tui.OnStop(tui.KeyF1, c.activateHelpTab),
		tui.OnStop(tui.KeyPageUp, func(event tui.KeyEvent) { c.BodyViewport.Page(-1) }),
		tui.OnStop(tui.KeyPageDown, func(event tui.KeyEvent) { c.BodyViewport.Page(1) }),
	}
}

func (c *Cockpit) activateNextTab(event tui.KeyEvent) {
	c.activateTab(c.activeTabIndex() + 1)
}

func (c *Cockpit) activatePreviousTab(event tui.KeyEvent) {
	c.activateTab(c.activeTabIndex() - 1)
}

func (c *Cockpit) activateHelpTab(event tui.KeyEvent) {
	if focusedTextEditor(event) {
		return
	}
	if index, ok := helpTabIndex(c.Model.Tabs); ok {
		c.activateTab(index)
	}
}

func (c *Cockpit) BindApp(app *tui.App) {
	c.bindAppFields(app)
	c.BodyViewport.BindApp(app)
}

func (c *Cockpit) currentWorkspacePage() *workspace_page.PageView {
	model := c.activeModel()
	if model.ActivePage != readmodel.CockpitWorkspacePage {
		return nil
	}
	return c.activeWorkspacePage(model)
}

func (c *Cockpit) quit(event tui.KeyEvent) {
	if app := event.App(); app != nil {
		app.Stop()
	}
}

func (c *Cockpit) activateTab(index int) {
	if len(c.Model.Tabs) == 0 {
		return
	}
	index = wrapTabIndex(index, len(c.Model.Tabs))
	c.ActiveTabIndex.Set(index)
	c.BodyViewport.Reset()
}

func (c *Cockpit) activeTabIndex() int {
	if c.ActiveTabIndex == nil {
		return selectedTabIndex(c.Model.Tabs)
	}
	return wrapTabIndex(c.ActiveTabIndex.Get(), len(c.Model.Tabs))
}

func (c *Cockpit) activeModel() readmodel.CockpitReadModel {
	model := c.Model
	index := c.activeTabIndex()
	for i := range model.Tabs {
		model.Tabs[i].Selected = i == index
	}
	if len(model.Tabs) == 0 {
		return model
	}

	tab := model.Tabs[index]
	if tab.Kind == readmodel.WorkspaceTabHelp {
		model.SelectedWorkspaceID = tab.ID
		model.ActivePage = readmodel.CockpitHelpPage
		return model
	}

	workspace := workspaceForTab(model, tab)
	model.SelectedWorkspaceID = tab.ID
	model.ActivePage = readmodel.CockpitWorkspacePage
	model.SelectedWorkspace = workspace
	return model
}

func (c *Cockpit) activeWorkspacePage(model readmodel.CockpitReadModel) *workspace_page.PageView {
	if c.WorkspacePages == nil {
		c.WorkspacePages = c.workspacePagesByTab(c.Model)
	}
	if page := c.WorkspacePages[model.SelectedWorkspaceID]; page != nil {
		return page
	}
	page := c.workspacePage(model.SelectedWorkspace)
	c.WorkspacePages[model.SelectedWorkspaceID] = page
	return page
}

func activityQueryPort(query ports.WorkspaceQueries) ports.ActivityQueries {
	if query == nil {
		return nil
	}
	if activity, ok := any(query).(ports.ActivityQueries); ok {
		return activity
	}
	return nil
}

func (c *Cockpit) refreshAfterWorkspaceSave(saved readmodel.WorkspaceReadModel) {
	active := c.activeModel()
	wasOnboarding := active.SelectedWorkspace.IsOnboarding()
	model, notice := c.Reloader.RefreshAfterSave(active, saved)
	c.Notice.Set(notice)
	c.replaceModel(model, !wasOnboarding)
}

func (c *Cockpit) refreshWorkspaceProjection(workspace readmodel.WorkspaceReadModel) {
	model := c.activeModel()
	model = updateWorkspaceInModel(model, workspace)
	c.Model = model
}

func (c *Cockpit) refreshAfterWorkspaceDelete(deleted readmodel.WorkspaceID) {
	model, notice := c.Reloader.RefreshAfterDelete(c.activeModel(), deleted)
	c.Notice.Set(notice)
	c.replaceModel(model, true)
}

func (c *Cockpit) publishNotice(notice readmodel.Notice) {
	c.Notice.Set(notice)
}

func (c *Cockpit) discardWorkspaceDraft() {
	model := c.activeModel()
	for i := range model.Tabs {
		if model.Tabs[i].Kind == readmodel.WorkspaceTabDraft {
			model.Tabs[i].Slug = ""
		}
	}
	model.SelectedWorkspaceID = "+"
	model.SelectedWorkspace = model.SelectedWorkspace.ResetDraftInput()
	c.replaceModel(model, false)
}

func (c *Cockpit) replaceModel(model readmodel.CockpitReadModel, preserveDraftPages bool) {
	activeTab := selectedTabIndex(model.Tabs)
	previousPages := c.WorkspacePages
	c.Model = model
	c.ActiveTabIndex.Set(activeTab)
	c.BodyViewport.Reset()
	c.WorkspacePages = c.workspacePagesByTab(model)
	// Persisted workspace pages are rebuilt from the authoritative registry.
	// Only draft pages retain local authoring state across refreshes.
	if preserveDraftPages {
		c.preserveDraftWorkspacePages(previousPages, model)
	}
	c.HelpPage = help_page.View(model.Help)
}

func (c *Cockpit) preserveDraftWorkspacePages(previous map[readmodel.WorkspaceID]*workspace_page.PageView, model readmodel.CockpitReadModel) {
	if previous == nil {
		return
	}
	for _, tab := range model.Tabs {
		if tab.Kind != readmodel.WorkspaceTabDraft {
			continue
		}
		page := previous[tab.ID]
		if page == nil || !page.OverviewSection.Model.IsDraft() {
			continue
		}
		c.WorkspacePages[tab.ID] = page
	}
}

func ActiveHelpPage(c *Cockpit) *help_page.PageView {
	return c.HelpPage
}

func ActiveWorkspacePage(c *Cockpit, model readmodel.CockpitReadModel) *workspace_page.PageView {
	if model.ActivePage != readmodel.CockpitWorkspacePage {
		return nil
	}
	return c.activeWorkspacePage(model)
}

func activeWorkspaceMountKey(model readmodel.CockpitReadModel) string {
	key := "workspace-page:" + string(model.SelectedWorkspaceID)
	// Projected and persisted `default` deliberately share product identity but
	// not component lifetime. Promotion must remount persisted-only Activity and
	// discard onboarding workflow state.
	if model.SelectedWorkspace.IsBootstrap() {
		return key + ":bootstrap"
	}
	if model.SelectedWorkspace.IsDraft() && model.SelectedWorkspace.Slug != "" {
		return key + ":" + model.SelectedWorkspace.Slug
	}
	return key
}

func staleRefreshNotice(message string) readmodel.Notice {
	return readmodel.Notice{Kind: readmodel.NoticeStale, Message: message}
}

func FlowText(text string) *FlowTextView {
	return ui.FlowText(text)
}

func activeTabLabel(tab readmodel.WorkspaceTabReadModel) string {
	return "[› " + tabLabel(tab) + "]"
}

func inactiveTabLabel(tab readmodel.WorkspaceTabReadModel) string {
	return "[" + tabLabel(tab) + "]"
}

func tabLabel(tab readmodel.WorkspaceTabReadModel) string {
	switch tab.Kind {
	case readmodel.WorkspaceTabDraft:
		return "+"
	case readmodel.WorkspaceTabHelp:
		return "?"
	default:
		return tab.Slug
	}
}

func (c *Cockpit) workspacePagesByTab(model readmodel.CockpitReadModel) map[readmodel.WorkspaceID]*workspace_page.PageView {
	pages := make(map[readmodel.WorkspaceID]*workspace_page.PageView, len(model.Tabs))
	for _, tab := range model.Tabs {
		if tab.Kind == readmodel.WorkspaceTabHelp {
			continue
		}
		workspace := workspaceForTab(model, tab)
		pages[tab.ID] = c.workspacePage(workspace)
	}
	return pages
}

func (c *Cockpit) workspacePage(workspace readmodel.WorkspaceReadModel) *workspace_page.PageView {
	page := workspace_page.Page(
		workspace,
		c.WorkspacePorts,
		targetSetupQueriesPort(c.WorkspacePorts),
		targetAuthCommandsPort(c.WorkspacePorts),
		c.Context,
		activityQueryPort(c.WorkspaceQuery),
		targetCredentialCommandsPort(c.WorkspacePorts),
	)
	page.OnWorkspaceSaved = c.refreshAfterWorkspaceSave
	page.OnWorkspaceCommitted = c.refreshWorkspaceProjection
	page.OnWorkspaceDeleted = c.refreshAfterWorkspaceDelete
	page.OnWorkspaceDiscarded = c.discardWorkspaceDraft
	page.OnNotice = c.publishNotice
	return page
}

func targetSetupQueriesPort(commands ports.WorkspaceCommands) ports.TargetSetupQueries {
	if commands == nil {
		return nil
	}
	if setupQueries, ok := any(commands).(ports.TargetSetupQueries); ok {
		return setupQueries
	}
	return nil
}

func targetAuthCommandsPort(commands ports.WorkspaceCommands) ports.TargetAuthCommands {
	if commands == nil {
		return nil
	}
	if authCommands, ok := any(commands).(ports.TargetAuthCommands); ok {
		return authCommands
	}
	return nil
}

func targetCredentialCommandsPort(commands ports.WorkspaceCommands) ports.TargetCredentialCommands {
	if commands == nil {
		return nil
	}
	if credentialCommands, ok := any(commands).(ports.TargetCredentialCommands); ok {
		return credentialCommands
	}
	return nil
}

func (c *Cockpit) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithHeightPercent(100.00),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := ShellHeader(c.activeModel())
	__tui_0.AddChild(__tui_1.Root)
	if c.Notice.Get().Visible() {
		__tui_2 := ShellNotice(c.Notice.Get())
		__tui_0.AddChild(__tui_2.Root)
	}
	__tui_3 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_3)
	__tui_4 := app.Mount(c, 0, func() tui.Component {
		return CockpitBodyViewport(c)
	})
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithHR(),
	)
	__tui_0.AddChild(__tui_5)
	__tui_6 := ShellFooter(c.activeModel())
	__tui_0.AddChild(__tui_6.Root)

	return __tui_0
}

func (c *Cockpit) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*Cockpit)
	if !ok {
		return
	}
	c.Model = f.Model
	c.BodyViewport = f.BodyViewport
	c.Reloader = f.Reloader
	c.WorkspacePages = f.WorkspacePages
	c.HelpPage = f.HelpPage
	c.Context = f.Context
	c.WorkspacePorts = f.WorkspacePorts
	c.WorkspaceQuery = f.WorkspaceQuery
}

var _ tui.PropsUpdater = (*Cockpit)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (c *Cockpit) bindAppFields(app *tui.App) {
	if c.ActiveTabIndex != nil {
		c.ActiveTabIndex.BindApp(app)
	}
	if c.Notice != nil {
		c.Notice.BindApp(app)
	}
}

type ShellNoticeView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ShellNoticeView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ShellNoticeView) GetRoot() *tui.Element { return v.Root }

func (v *ShellNoticeView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ShellNoticeView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ShellNoticeView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ShellNoticeView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ShellNoticeView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ShellNoticeView)(nil)

var _ tui.AppUnbinder = (*ShellNoticeView)(nil)

var _ tui.PropsUpdater = (*ShellNoticeView)(nil)

func ShellNotice(notice readmodel.Notice) *ShellNoticeView {
	var view ShellNoticeView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := FlowText(notice.Message)
	__tui_0.AddChild(__tui_1.Root)

	watchers = append(watchers, __tui_1.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_1).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_1).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = ShellNoticeView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ShellHeaderView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ShellHeaderView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ShellHeaderView) GetRoot() *tui.Element { return v.Root }

func (v *ShellHeaderView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ShellHeaderView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ShellHeaderView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ShellHeaderView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ShellHeaderView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ShellHeaderView)(nil)

var _ tui.AppUnbinder = (*ShellHeaderView)(nil)

var _ tui.PropsUpdater = (*ShellHeaderView)(nil)

func ShellHeader(model readmodel.CockpitReadModel) *ShellHeaderView {
	var view ShellHeaderView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithText("⛉ SWOBU"),
		tui.WithWidth(9),
		tui.WithWrap(false),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
		tui.WithJustify(tui.JustifyEnd),
	)
	for __idx_0, tab := range model.Tabs {
		_ = __idx_0
		if tab.Selected {
			__tui_3 := tui.New(
				tui.WithText(activeTabLabel(tab)),
				tui.WithTruncate(true),
				tui.WithWrap(false),
				tui.WithMinWidth(0),
			)
			__tui_2.AddChild(__tui_3)
		} else {
			__tui_4 := tui.New(
				tui.WithText(inactiveTabLabel(tab)),
				tui.WithTruncate(true),
				tui.WithWrap(false),
				tui.WithMinWidth(0),
			)
			__tui_2.AddChild(__tui_4)
		}
	}
	__tui_0.AddChild(__tui_2)
	if model.HeaderRight != "" {
		__tui_5 := tui.New(
			tui.WithText(model.HeaderRight),
			tui.WithTruncate(true),
			tui.WithWrap(false),
			tui.WithMarginTRBL(0, 0, 0, 2),
			tui.WithMinWidth(0),
		)
		__tui_0.AddChild(__tui_5)
	}

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ShellHeaderView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ShellFooterView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ShellFooterView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ShellFooterView) GetRoot() *tui.Element { return v.Root }

func (v *ShellFooterView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ShellFooterView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ShellFooterView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ShellFooterView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ShellFooterView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ShellFooterView)(nil)

var _ tui.AppUnbinder = (*ShellFooterView)(nil)

var _ tui.PropsUpdater = (*ShellFooterView)(nil)

func ShellFooter(model readmodel.CockpitReadModel) *ShellFooterView {
	var view ShellFooterView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(3),
	)
	__tui_1 := tui.New(
		tui.WithText("↑↓ move"),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("↵ action"),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("? help"),
	)
	__tui_0.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText("esc back"),
	)
	__tui_0.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText("tab switch"),
	)
	__tui_0.AddChild(__tui_5)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ShellFooterView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*Cockpit)(nil)
)
