// Code generated by tui generate. DO NOT EDIT.
// Source: workflow.gsx

package workspace_edit

import (
	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
)

type FlowTextView = ui.FlowTextView

func FlowText(text string) *FlowTextView {
	return ui.FlowText(text)
}

func (w *Workflow) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := app.Mount(w, 0, func() tui.Component {
		return RowComponent(w)
	})
	__tui_0.AddChild(__tui_1)
	if w.Workspace.IsDraft() {
		__tui_2 := EndpointPreviewRow(w.WorkspaceURLPreview())
		__tui_0.AddChild(__tui_2.Root)
	}

	return __tui_0
}

type EndpointPreviewRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *EndpointPreviewRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *EndpointPreviewRowView) GetRoot() *tui.Element { return v.Root }

func (v *EndpointPreviewRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *EndpointPreviewRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *EndpointPreviewRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *EndpointPreviewRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*EndpointPreviewRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*EndpointPreviewRowView)(nil)

var _ tui.AppUnbinder = (*EndpointPreviewRowView)(nil)

var _ tui.PropsUpdater = (*EndpointPreviewRowView)(nil)

func EndpointPreviewRow(value string) *EndpointPreviewRowView {
	var view EndpointPreviewRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_2 := tui.New(
		tui.WithWidth(2),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("endpoint"),
		tui.WithWidth(18),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithFlexGrow(1),
	)
	__tui_1.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText("preview"),
		tui.WithWidth(14),
	)
	__tui_1.AddChild(__tui_5)
	__tui_0.AddChild(__tui_1)
	__tui_6 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithPaddingTRBL(0, 0, 0, 20),
	)
	__tui_7 := FlowText(value)
	__tui_6.AddChild(__tui_7.Root)
	__tui_0.AddChild(__tui_6)

	watchers = append(watchers, __tui_7.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_7).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_7).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = EndpointPreviewRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
