// Code generated by tui generate. DO NOT EDIT.
// Source: page_view.gsx

package workspace

import (
	"context"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ports"
	"github.com/swobuforge/swobu/internal/cockpit/readmodel"
	activitysection "github.com/swobuforge/swobu/internal/cockpit/sections/activity"
	routessection "github.com/swobuforge/swobu/internal/cockpit/sections/routes"
	overviewsection "github.com/swobuforge/swobu/internal/cockpit/sections/workspace_overview"
	"github.com/swobuforge/swobu/internal/cockpit/ui"
)

type PageView struct {
	OverviewSection      *overviewsection.SectionView
	RoutesSection        *routessection.SectionView
	ActivitySection      *activitysection.SectionView
	OnWorkspaceSaved     func(readmodel.WorkspaceReadModel)
	OnWorkspaceCommitted func(readmodel.WorkspaceReadModel)
	OnWorkspaceDeleted   func(readmodel.WorkspaceID)
	OnWorkspaceDiscarded func()
	OnNotice             func(readmodel.Notice)
}

func Page(workspace readmodel.WorkspaceReadModel, commands ports.WorkspaceCommands, setupQueries ports.TargetSetupQueries, authCommands ports.TargetAuthCommands, ctx context.Context, activityQuery ports.ActivityQueries, credentialCommands ports.TargetCredentialCommands) *PageView {
	page := &PageView{
		OverviewSection: overviewsection.Section(workspace, commands),
		RoutesSection:   routessection.Section(workspace, routeCommandPort(commands)),
		ActivitySection: activitysection.Section(workspace, ctx, activityQuery),
	}
	if shareCommands, ok := any(commands).(ports.ShareCommands); ok {
		page.OverviewSection.ShareCommands = shareCommands
		page.RoutesSection.ShareCommands = shareCommands
	}
	if setupQueries != nil {
		page.RoutesSection.TargetConfigs.Commands.Setup = setupQueries
	}
	if authCommands != nil {
		page.RoutesSection.TargetConfigs.Commands.Auth = authCommands
	}
	if credentialCommands != nil {
		page.RoutesSection.TargetConfigs.Commands.Credentials = credentialCommands
	}
	page.OverviewSection.OnWorkspaceSaved = page.workspaceSaved
	page.RoutesSection.OnWorkspaceCommitted = page.workspaceCommitted
	page.OverviewSection.OnWorkspaceDeleted = page.workspaceDeleted
	page.OverviewSection.OnWorkspaceDiscarded = page.workspaceDiscarded
	page.OverviewSection.OnNotice = page.publishNotice
	page.RoutesSection.OnNotice = page.publishNotice
	page.RoutesSection.OnWorkspacePersisted = page.workspacePersisted
	return page
}

func (v *PageView) publishNotice(notice readmodel.Notice) {
	if v.OnNotice != nil {
		v.OnNotice(notice)
	}
}

func routeCommandPort(commands ports.WorkspaceCommands) ports.RouteCommands {
	if commands == nil {
		return nil
	}
	if routes, ok := any(commands).(ports.RouteCommands); ok {
		return routes
	}
	return nil
}

func (v *PageView) workspaceSaved(workspace readmodel.WorkspaceReadModel) {
	requestAddRouteFocusAfterSave(workspace)
	if v.OnWorkspaceSaved != nil {
		v.OnWorkspaceSaved(workspace)
	}
}

func (v *PageView) workspaceDeleted(workspaceID readmodel.WorkspaceID) {
	if v.OnWorkspaceDeleted != nil {
		v.OnWorkspaceDeleted(workspaceID)
	}
}

func (v *PageView) workspaceDiscarded() {
	if v.OnWorkspaceDiscarded != nil {
		v.OnWorkspaceDiscarded()
	}
}

func (v *PageView) workspacePersisted(workspace readmodel.WorkspaceReadModel) {
	if v.OnWorkspaceSaved != nil {
		v.OnWorkspaceSaved(workspace)
	}
}

func (v *PageView) workspaceCommitted(workspace readmodel.WorkspaceReadModel) {
	if v.OnWorkspaceCommitted != nil {
		v.OnWorkspaceCommitted(workspace)
	}
}

func (v *PageView) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.OnStop(tui.KeyUp, v.selectPrevious),
		tui.OnStop(tui.KeyDown, v.selectNext),
		tui.OnStop(tui.KeyEscape, v.backOut),
		tui.OnStop(tui.KeyEnter, ui.ActivateCurrentSelection),
	}
}

func (v *PageView) selectPrevious(event tui.KeyEvent) {
	ui.SelectPrevious(event)
}

func (v *PageView) selectNext(event tui.KeyEvent) {
	ui.SelectNext(event)
}

func OverviewSectionComponent(v *PageView) tui.Component { return v.OverviewSection }

func RoutesSectionComponent(v *PageView) tui.Component {
	if consumeAddRouteFocusAfterSave(v.OverviewSection.Model) {
		v.RoutesSection.RequestAddRouteFocus()
	}
	return v.RoutesSection
}

func (v *PageView) backOut(event tui.KeyEvent) {
	app := event.App()
	if ui.BackFocused(app) {
		return
	}
	if app != nil {
		app.Stop()
	}
}

func (v *PageView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := app.Mount(v, 0, func() tui.Component {
		return OverviewSectionComponent(v)
	})
	__tui_0.AddChild(__tui_1)
	if !v.OverviewSection.Model.IsDraft() || v.OverviewSection.Model.Slug != "" {
		__tui_2 := tui.New(
			tui.WithWidth(0),
			tui.WithHeight(1),
		)
		__tui_0.AddChild(__tui_2)
		__tui_3 := app.Mount(v, 1, func() tui.Component {
			return RoutesSectionComponent(v)
		})
		__tui_0.AddChild(__tui_3)
		if !v.OverviewSection.Model.IsDraft() {
			__tui_4 := tui.New(
				tui.WithWidth(0),
				tui.WithHeight(1),
			)
			__tui_0.AddChild(__tui_4)
			__tui_5 := v.ActivitySection.Render(app)
			__tui_0.AddChild(__tui_5)
		}
	}
	__tui_6 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithWidth(0),
		tui.WithHeight(1),
	)
	__tui_0.AddChild(__tui_7)

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (v *PageView) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*PageView)
	if !ok {
		return
	}
	v.OverviewSection = f.OverviewSection
	v.RoutesSection = f.RoutesSection
	v.ActivitySection = f.ActivitySection
}

func (v *PageView) UpdateProps(fresh tui.Component) {
	v.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*PageView)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (v *PageView) bindAppFields(app *tui.App) {
	if binder, ok := any(v.ActivitySection).(tui.AppBinder); ok {
		binder.BindApp(app)
	}
}

func (v *PageView) BindApp(app *tui.App) {
	v.bindAppFields(app)
}

var _ tui.AppBinder = (*PageView)(nil)

// unbindAppFields is generated. It detaches topic-based Events
// subscriptions and any component-expression AppUnbinder fields.
// Call this from your UnbindApp if you override it.
func (v *PageView) unbindAppFields() {
	if unbinder, ok := any(v.ActivitySection).(tui.AppUnbinder); ok {
		unbinder.UnbindApp()
	}
}

func (v *PageView) UnbindApp() {
	v.unbindAppFields()
}

var _ tui.AppUnbinder = (*PageView)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener = (*PageView)(nil)
)
