// Code generated by tui generate. DO NOT EDIT.
// Source: choice_picker.gsx

package ui

import (
	tui "github.com/grindlemire/go-tui"
)

func (p *ChoicePicker) Render(app *tui.App) *tui.Element {
	win := p.list.Window()
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	for __idx_0, row := range win.Rows {
		_ = __idx_0
		__tui_2 := tui.New(
			tui.WithWidthPercent(100.00),
		)
		__tui_3 := app.Mount(p, tui.MountKey(0, p.ID+":option:"+choiceRowKey(row)), func() tui.Component {
			return ChoicePickerOptionComponent(p, row)
		})
		__tui_2.AddChild(__tui_3)
		__tui_1.AddChild(__tui_2)
	}
	__tui_0.AddChild(__tui_1)
	if win.TotalRows > win.ShownRows {
		__tui_4 := ChoicePickerFooterRow(p.list.CountLabel(win))
		__tui_0.AddChild(__tui_4.Root)
	}

	return __tui_0
}

type ChoicePickerFooterRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ChoicePickerFooterRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ChoicePickerFooterRowView) GetRoot() *tui.Element { return v.Root }

func (v *ChoicePickerFooterRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ChoicePickerFooterRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ChoicePickerFooterRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ChoicePickerFooterRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ChoicePickerFooterRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ChoicePickerFooterRowView)(nil)

var _ tui.AppUnbinder = (*ChoicePickerFooterRowView)(nil)

var _ tui.PropsUpdater = (*ChoicePickerFooterRowView)(nil)

func ChoicePickerFooterRow(countLabel string) *ChoicePickerFooterRowView {
	var view ChoicePickerFooterRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
		tui.WithMarginTRBL(1, 0, 0, 0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(countLabel),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("↑↓ choose"),
		tui.WithWidth(14),
		tui.WithTextStyle(ToneStyle(ToneMuted)),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ChoicePickerFooterRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
