// Code generated by tui generate. DO NOT EDIT.
// Source: file_browser.gsx

package ui

import (
	tui "github.com/grindlemire/go-tui"
)

func FileBrowserEntryComponent(b *FileBrowser, list *ChoiceList, row ChoiceRowModel, first bool) *ChoiceRow {
	return NewChoiceRow(b.ID+":entry:"+choiceRowKey(row), list, row, list.AutoFocus && first)
}

func (b *FileBrowser) Render(app *tui.App) *tui.Element {
	win := b.Window()
	list := b.choiceList()
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if b.Title != "" {
		__tui_1 := FileBrowserTitleRow(b.Title)
		__tui_0.AddChild(__tui_1.Root)
	}
	if b.Loading.Get() {
		__tui_2 := FileBrowserLoadingRow()
		__tui_0.AddChild(__tui_2.Root)
	} else {
		__tui_3 := FileBrowserDirRow(win.CurrentDir)
		__tui_0.AddChild(__tui_3.Root)
		__tui_4 := FileBrowserSearchRow(win.Query)
		__tui_0.AddChild(__tui_4.Root)
	}
	if !b.Loading.Get() && !win.HasError {
		__tui_5 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithWidthPercent(100.00),
		)
		for i, row := range list.Window().Rows {
			_ = i
			__tui_6 := tui.New(
				tui.WithWidthPercent(100.00),
			)
			__tui_7 := app.Mount(b, tui.MountKey(0, b.ID+":entry:"+choiceRowKey(row)), func() tui.Component {
				return FileBrowserEntryComponent(b, list, row, i == 0)
			})
			__tui_6.AddChild(__tui_7)
			__tui_5.AddChild(__tui_6)
		}
		__tui_0.AddChild(__tui_5)
		__tui_8 := FileBrowserHintRow(fileBrowserCountLabel(win.ShownRows, win.TotalRows))
		__tui_0.AddChild(__tui_8.Root)
	}
	if win.HasError {
		__tui_9 := FileBrowserErrorRow(win.ErrorText)
		__tui_0.AddChild(__tui_9.Root)
	}

	return __tui_0
}

type FileBrowserTitleRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FileBrowserTitleRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FileBrowserTitleRowView) GetRoot() *tui.Element { return v.Root }

func (v *FileBrowserTitleRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FileBrowserTitleRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FileBrowserTitleRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FileBrowserTitleRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FileBrowserTitleRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FileBrowserTitleRowView)(nil)

var _ tui.AppUnbinder = (*FileBrowserTitleRowView)(nil)

var _ tui.PropsUpdater = (*FileBrowserTitleRowView)(nil)

func FileBrowserTitleRow(title string) *FileBrowserTitleRowView {
	var view FileBrowserTitleRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(title),
		tui.WithFlexGrow(1),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = FileBrowserTitleRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type FileBrowserDirRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FileBrowserDirRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FileBrowserDirRowView) GetRoot() *tui.Element { return v.Root }

func (v *FileBrowserDirRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FileBrowserDirRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FileBrowserDirRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FileBrowserDirRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FileBrowserDirRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FileBrowserDirRowView)(nil)

var _ tui.AppUnbinder = (*FileBrowserDirRowView)(nil)

var _ tui.PropsUpdater = (*FileBrowserDirRowView)(nil)

func FileBrowserDirRow(dir string) *FileBrowserDirRowView {
	var view FileBrowserDirRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("dir"),
		tui.WithWidth(18),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(dir),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = FileBrowserDirRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type FileBrowserSearchRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FileBrowserSearchRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FileBrowserSearchRowView) GetRoot() *tui.Element { return v.Root }

func (v *FileBrowserSearchRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FileBrowserSearchRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FileBrowserSearchRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FileBrowserSearchRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FileBrowserSearchRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FileBrowserSearchRowView)(nil)

var _ tui.AppUnbinder = (*FileBrowserSearchRowView)(nil)

var _ tui.PropsUpdater = (*FileBrowserSearchRowView)(nil)

func FileBrowserSearchRow(query string) *FileBrowserSearchRowView {
	var view FileBrowserSearchRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
		tui.WithMarginTRBL(0, 0, 1, 0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("search"),
		tui.WithWidth(18),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(searchPickerQueryValue(query)),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = FileBrowserSearchRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type FileBrowserErrorRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FileBrowserErrorRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FileBrowserErrorRowView) GetRoot() *tui.Element { return v.Root }

func (v *FileBrowserErrorRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FileBrowserErrorRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FileBrowserErrorRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FileBrowserErrorRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FileBrowserErrorRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FileBrowserErrorRowView)(nil)

var _ tui.AppUnbinder = (*FileBrowserErrorRowView)(nil)

var _ tui.PropsUpdater = (*FileBrowserErrorRowView)(nil)

func FileBrowserErrorRow(msg string) *FileBrowserErrorRowView {
	var view FileBrowserErrorRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithPaddingTRBL(0, 0, 0, 2),
	)
	__tui_1 := FlowText(msg)
	__tui_0.AddChild(__tui_1.Root)

	watchers = append(watchers, __tui_1.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_1).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_1).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = FileBrowserErrorRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type FileBrowserLoadingRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FileBrowserLoadingRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FileBrowserLoadingRowView) GetRoot() *tui.Element { return v.Root }

func (v *FileBrowserLoadingRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FileBrowserLoadingRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FileBrowserLoadingRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FileBrowserLoadingRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FileBrowserLoadingRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FileBrowserLoadingRowView)(nil)

var _ tui.AppUnbinder = (*FileBrowserLoadingRowView)(nil)

var _ tui.PropsUpdater = (*FileBrowserLoadingRowView)(nil)

func FileBrowserLoadingRow() *FileBrowserLoadingRowView {
	var view FileBrowserLoadingRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithPaddingTRBL(0, 0, 0, 2),
	)
	__tui_1 := FlowText("loading…")
	__tui_0.AddChild(__tui_1.Root)

	watchers = append(watchers, __tui_1.GetWatchers()...)

	__bindApp := func(app *tui.App) {
		if binder, ok := any(__tui_1).(tui.AppBinder); ok {
			binder.BindApp(app)
		}
	}

	__unbindApp := func() {
		if unbinder, ok := any(__tui_1).(tui.AppUnbinder); ok {
			unbinder.UnbindApp()
		}
	}

	view = FileBrowserLoadingRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type FileBrowserHintRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FileBrowserHintRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FileBrowserHintRowView) GetRoot() *tui.Element { return v.Root }

func (v *FileBrowserHintRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FileBrowserHintRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FileBrowserHintRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FileBrowserHintRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FileBrowserHintRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FileBrowserHintRowView)(nil)

var _ tui.AppUnbinder = (*FileBrowserHintRowView)(nil)

var _ tui.PropsUpdater = (*FileBrowserHintRowView)(nil)

func FileBrowserHintRow(countLabel string) *FileBrowserHintRowView {
	var view FileBrowserHintRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
		tui.WithMarginTRBL(1, 0, 0, 0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(countLabel),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
		tui.WithMinWidth(0),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText("↑↓ choose"),
		tui.WithWidth(14),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = FileBrowserHintRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
