// Code generated by tui generate. DO NOT EDIT.
// Source: flow_text.gsx

package ui

import (
	tui "github.com/grindlemire/go-tui"
)

type FlowTextView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *FlowTextView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *FlowTextView) GetRoot() *tui.Element { return v.Root }

func (v *FlowTextView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *FlowTextView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *FlowTextView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *FlowTextView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*FlowTextView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*FlowTextView)(nil)

var _ tui.AppUnbinder = (*FlowTextView)(nil)

var _ tui.PropsUpdater = (*FlowTextView)(nil)

func FlowText(text string) *FlowTextView {
	var view FlowTextView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithText(text),
		tui.WithWidthPercent(100.00),
		tui.WithHeightAuto(),
		tui.WithWrap(true),
		tui.WithMinWidth(0),
	)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = FlowTextView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
