// Code generated by tui generate. DO NOT EDIT.
// Source: search_picker.gsx

package ui

import (
	tui "github.com/grindlemire/go-tui"
)

func SearchPickerOptionComponent(p *SearchPicker, list *ChoiceList, row ChoiceRowModel, first bool) *ChoiceRow {
	return NewChoiceRow(p.ID+":option:"+choiceRowKey(row), list, row, list.AutoFocus && first)
}

func (p *SearchPicker) Render(app *tui.App) *tui.Element {
	list := p.choiceList()
	win := list.Window()
	countLabel, hint := p.countLabel(win), "↑↓ search"
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if p.Title != "" {
		__tui_1 := SearchPickerTitleRow(p.Title)
		__tui_0.AddChild(__tui_1.Root)
	}
	__tui_2 := SearchPickerQueryRow(p.Query.Get())
	__tui_0.AddChild(__tui_2.Root)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	for i, row := range win.Rows {
		_ = i
		__tui_4 := tui.New(
			tui.WithWidthPercent(100.00),
		)
		__tui_5 := app.Mount(p, tui.MountKey(0, p.ID+":option:"+choiceRowKey(row)), func() tui.Component {
			return SearchPickerOptionComponent(p, list, row, i == 0)
		})
		__tui_4.AddChild(__tui_5)
		__tui_3.AddChild(__tui_4)
	}
	__tui_0.AddChild(__tui_3)
	__tui_6 := SearchPickerFooterRow(countLabel, hint)
	__tui_0.AddChild(__tui_6.Root)

	return __tui_0
}

type SearchPickerTitleRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SearchPickerTitleRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SearchPickerTitleRowView) GetRoot() *tui.Element { return v.Root }

func (v *SearchPickerTitleRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SearchPickerTitleRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SearchPickerTitleRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SearchPickerTitleRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SearchPickerTitleRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SearchPickerTitleRowView)(nil)

var _ tui.AppUnbinder = (*SearchPickerTitleRowView)(nil)

var _ tui.PropsUpdater = (*SearchPickerTitleRowView)(nil)

func SearchPickerTitleRow(title string) *SearchPickerTitleRowView {
	var view SearchPickerTitleRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText(title),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SearchPickerTitleRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type SearchPickerQueryRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SearchPickerQueryRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SearchPickerQueryRowView) GetRoot() *tui.Element { return v.Root }

func (v *SearchPickerQueryRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SearchPickerQueryRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SearchPickerQueryRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SearchPickerQueryRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SearchPickerQueryRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SearchPickerQueryRowView)(nil)

var _ tui.AppUnbinder = (*SearchPickerQueryRowView)(nil)

var _ tui.PropsUpdater = (*SearchPickerQueryRowView)(nil)

func SearchPickerQueryRow(query string) *SearchPickerQueryRowView {
	var view SearchPickerQueryRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
		tui.WithMarginTRBL(0, 0, 1, 0),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("search"),
		tui.WithWidth(18),
	)
	__tui_0.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(searchPickerQueryValue(query)),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
	)
	__tui_0.AddChild(__tui_3)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SearchPickerQueryRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type SearchPickerFooterRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *SearchPickerFooterRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *SearchPickerFooterRowView) GetRoot() *tui.Element { return v.Root }

func (v *SearchPickerFooterRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *SearchPickerFooterRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *SearchPickerFooterRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *SearchPickerFooterRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SearchPickerFooterRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*SearchPickerFooterRowView)(nil)

var _ tui.AppUnbinder = (*SearchPickerFooterRowView)(nil)

var _ tui.PropsUpdater = (*SearchPickerFooterRowView)(nil)

func SearchPickerFooterRow(countLabel string, hint string) *SearchPickerFooterRowView {
	var view SearchPickerFooterRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithWidthPercent(100.00),
		tui.WithMarginTRBL(1, 0, 0, 0),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_2 := tui.New(
		tui.WithWidth(2),
	)
	__tui_1.AddChild(__tui_2)
	__tui_3 := tui.New(
		tui.WithText(countLabel),
		tui.WithFlexGrow(1),
		tui.WithTruncate(true),
		tui.WithWrap(false),
	)
	__tui_1.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(hint),
		tui.WithWidth(14),
	)
	__tui_1.AddChild(__tui_4)
	__tui_0.AddChild(__tui_1)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = SearchPickerFooterRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
