// Code generated by tui generate. DO NOT EDIT.
// Source: select.gsx

package ui

import (
	"strings"

	tui "github.com/grindlemire/go-tui"
)

func (s *Select) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := app.Mount(s, 0, func() tui.Component {
		return SelectHeaderComponent(s)
	})
	__tui_0.AddChild(__tui_1)
	if !s.IsEntered() && strings.TrimSpace(s.props.Detail) != "" {
		__tui_2 := tui.New(
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 20),
		)
		__tui_3 := app.Mount(s, 1, func() tui.Component {
			return FlowText(s.props.Detail)
		})
		__tui_2.AddChild(__tui_3)
		__tui_0.AddChild(__tui_2)
	}
	if s.IsEntered() && s.props.Body != nil {
		__tui_4 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithWidthPercent(100.00),
			tui.WithPaddingTRBL(0, 0, 0, 3),
		)
		__tui_5 := app.Mount(s, 2, func() tui.Component {
			return SelectBodyComponent(s)
		})
		__tui_4.AddChild(__tui_5)
		__tui_0.AddChild(__tui_4)
	}

	return __tui_0
}
