// Code generated by tui generate. DO NOT EDIT.
// Source: section.gsx

package activity

import (
	"context"
	"fmt"
	"strings"
	"time"

	tui "github.com/grindlemire/go-tui"
	"github.com/swobuforge/swobu/internal/cockpit/ports"
	"github.com/swobuforge/swobu/internal/cockpit/readmodel"
)

type SectionView struct {
	Workspace        readmodel.WorkspaceReadModel
	Ctx              context.Context
	ActivityQuery    ports.ActivityQueries
	ActivitySnapshot *tui.State[readmodel.ActivityReadModel]
	RefreshInterval  time.Duration
	RefreshLifecycle *activityRefreshLifecycle
}

var _ tui.Component = (*SectionView)(nil)

func Section(workspace readmodel.WorkspaceReadModel, ctx context.Context, activityQuery ports.ActivityQueries) *SectionView {
	if ctx == nil {
		ctx = context.Background()
	}
	return &SectionView{
		Workspace:        workspace,
		Ctx:              ctx,
		ActivityQuery:    activityQuery,
		ActivitySnapshot: tui.NewState(workspace.Activity),
		RefreshInterval:  time.Second,
		RefreshLifecycle: &activityRefreshLifecycle{},
	}
}

func (s *SectionView) BindApp(app *tui.App) {
	s.bindAppFields(app)
	s.startActivityRefresh(app)
}

func (s *SectionView) UnbindApp() {
	s.stopActivityRefresh()
}

func (s *SectionView) activityRows() []readmodel.ActivityRowReadModel {
	activity := s.ActivitySnapshot.Get()
	if len(activity.Rows) > 0 {
		return activity.Rows
	}
	latest, ok := activity.LatestRow()
	if !ok {
		return nil
	}
	return []readmodel.ActivityRowReadModel{latest}
}

func (s *SectionView) emptyActivityText() string {
	if s.Workspace.IsDraft() {
		return "(no activity)"
	}
	return "no requests yet"
}

func activityObservedAt(row readmodel.ActivityRowReadModel) string {
	observedAt := strings.TrimSpace(row.ObservedAt) // swobu:io-string source=boundary
	if observedAt == "" {
		return "unknown"
	}
	return observedAt
}

func activityRouteIdentity(row readmodel.ActivityRowReadModel) string {
	return strings.TrimSpace(string(row.RouteID)) // swobu:io-string source=boundary
}

func activityRouteLabel(row readmodel.ActivityRowReadModel) string {
	if route := strings.TrimSpace(row.RouteLabel); route != "" { // swobu:io-string source=boundary
		return route
	}
	return string(row.RouteID)
}

func activityTarget(row readmodel.ActivityRowReadModel) string {
	provider := strings.TrimSpace(row.ProviderSpec) // swobu:io-string source=boundary
	model := strings.TrimSpace(row.ProviderModel)   // swobu:io-string source=boundary
	if provider == "" || model == "" {
		return ""
	}
	return provider + "/" + model
}

func activityClientEvidence(row readmodel.ActivityRowReadModel) string {
	client := strings.TrimSpace(row.ClientLabel) // swobu:io-string source=boundary
	if client == "" {
		return ""
	}
	return "· " + client
}

func activityAttemptEvidence(row readmodel.ActivityRowReadModel) string {
	if row.AttemptCount <= 1 {
		return ""
	}
	return fmt.Sprintf("%d attempts", row.AttemptCount)
}

func activityStatusLabel(row readmodel.ActivityRowReadModel) string {
	if row.Status == readmodel.ActivityPending {
		return "…"
	}
	if row.HTTPStatus > 0 {
		return fmt.Sprint(row.HTTPStatus)
	}
	return ""
}

func activityDurationLabel(row readmodel.ActivityRowReadModel) string {
	if !row.DurationKnown || row.Status == readmodel.ActivityPending {
		return ""
	}
	duration := row.Duration
	switch {
	case duration < time.Second:
		duration = duration.Round(time.Millisecond)
	case duration < 10*time.Second:
		duration = duration.Round(100 * time.Millisecond)
	default:
		duration = duration.Round(time.Second)
	}
	return duration.String()
}

func activityShowsClient(app *tui.App) bool {
	if app == nil {
		return false
	}
	width, _ := app.Size()
	return width >= 112
}

func activityPathParts(row readmodel.ActivityRowReadModel) (string, string, string) {
	requested := strings.TrimSpace(row.RequestedModel) // swobu:io-string source=boundary
	routeID := activityRouteIdentity(row)
	route := activityRouteLabel(row)
	if requested != "" && requested == routeID {
		requested = ""
	}
	return requested, route, activityTarget(row)
}

func (s *SectionView) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := ActivityHeader()
	__tui_0.AddChild(__tui_1.Root)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithWidthPercent(100.00),
	)
	if rows := s.activityRows(); len(rows) > 0 {
		for __idx_0, row := range rows {
			_ = __idx_0
			__tui_3 := ActivityRow(row, activityShowsClient(app))
			__tui_2.AddChild(__tui_3.Root)
		}
	} else {
		__tui_4 := ActivityColumns("", "", s.emptyActivityText(), "", "")
		__tui_2.AddChild(__tui_4.Root)
	}
	__tui_0.AddChild(__tui_2)

	return __tui_0
}

func (s *SectionView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*SectionView)
	if !ok {
		return
	}
	s.Workspace = f.Workspace
	s.Ctx = f.Ctx
	s.ActivityQuery = f.ActivityQuery
	s.RefreshInterval = f.RefreshInterval
	s.RefreshLifecycle = f.RefreshLifecycle
}

var _ tui.PropsUpdater = (*SectionView)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (s *SectionView) bindAppFields(app *tui.App) {
	if s.ActivitySnapshot != nil {
		s.ActivitySnapshot.BindApp(app)
	}
}

type ActivityHeaderView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ActivityHeaderView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ActivityHeaderView) GetRoot() *tui.Element { return v.Root }

func (v *ActivityHeaderView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ActivityHeaderView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ActivityHeaderView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ActivityHeaderView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ActivityHeaderView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ActivityHeaderView)(nil)

var _ tui.AppUnbinder = (*ActivityHeaderView)(nil)

var _ tui.PropsUpdater = (*ActivityHeaderView)(nil)

func ActivityHeader() *ActivityHeaderView {
	var view ActivityHeaderView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(2),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithText("activity"),
	)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ActivityHeaderView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ActivityRowView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ActivityRowView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ActivityRowView) GetRoot() *tui.Element { return v.Root }

func (v *ActivityRowView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ActivityRowView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ActivityRowView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ActivityRowView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ActivityRowView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ActivityRowView)(nil)

var _ tui.AppUnbinder = (*ActivityRowView)(nil)

var _ tui.PropsUpdater = (*ActivityRowView)(nil)

func ActivityRow(row readmodel.ActivityRowReadModel, showClient bool) *ActivityRowView {
	var view ActivityRowView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexWrap(tui.WrapNone),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(5),
		tui.WithFlexShrink(0),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexWrap(tui.WrapNone),
		tui.WithFlexGrow(1), tui.WithFlexShrink(1),
		tui.WithMinWidth(0),
	)
	__tui_3 := tui.New(
		tui.WithText(activityObservedAt(row)),
		tui.WithWidth(8),
		tui.WithFlexShrink(0),
		tui.WithWrap(false),
		tui.WithTruncate(true),
		tui.WithOverflow(tui.OverflowHidden),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithWidth(2),
		tui.WithFlexShrink(0),
	)
	__tui_2.AddChild(__tui_4)
	if requested, route, target := activityPathParts(row); requested != "" || route != "" || target != "" {
		if requested != "" {
			__tui_5 := tui.New(
				tui.WithText(requested),
				tui.WithFlexShrink(3),
				tui.WithMinWidth(3),
				tui.WithWrap(false),
				tui.WithTruncate(true),
				tui.WithOverflow(tui.OverflowHidden),
			)
			__tui_2.AddChild(__tui_5)
			if route != "" || target != "" {
				__tui_6 := tui.New(
					tui.WithText("→"),
					tui.WithFlexShrink(0),
					tui.WithPaddingTRBL(0, 1, 0, 1),
				)
				__tui_2.AddChild(__tui_6)
			}
		}
		if route != "" {
			__tui_7 := tui.New(
				tui.WithText(route),
				tui.WithFlexShrink(1),
				tui.WithMinWidth(3),
				tui.WithWrap(false),
				tui.WithTruncate(true),
				tui.WithOverflow(tui.OverflowHidden),
			)
			__tui_2.AddChild(__tui_7)
			if target != "" {
				__tui_8 := tui.New(
					tui.WithText("→"),
					tui.WithFlexShrink(0),
					tui.WithPaddingTRBL(0, 1, 0, 1),
				)
				__tui_2.AddChild(__tui_8)
			}
		}
		if target != "" {
			__tui_9 := tui.New(
				tui.WithText(target),
				tui.WithFlexShrink(5),
				tui.WithMinWidth(5),
				tui.WithWrap(false),
				tui.WithTruncate(true),
				tui.WithOverflow(tui.OverflowHidden),
			)
			__tui_2.AddChild(__tui_9)
		}
	}
	__tui_10 := tui.New(
		tui.WithWidth(2),
		tui.WithFlexGrow(1),
		tui.WithFlexShrink(1),
		tui.WithMinWidth(0),
	)
	__tui_2.AddChild(__tui_10)
	if attempts := activityAttemptEvidence(row); attempts != "" {
		if client := activityClientEvidence(row); showClient && client != "" {
			__tui_11 := tui.New(
				tui.WithText(client),
				tui.WithWidth(18),
				tui.WithFlexShrink(5),
				tui.WithMinWidth(0),
				tui.WithWrap(false),
				tui.WithTruncate(true),
				tui.WithOverflow(tui.OverflowHidden),
			)
			__tui_2.AddChild(__tui_11)
			__tui_12 := tui.New(
				tui.WithWidth(2),
				tui.WithFlexShrink(0),
			)
			__tui_2.AddChild(__tui_12)
		}
		__tui_13 := tui.New(
			tui.WithText(attempts),
			tui.WithFlexShrink(0),
			tui.WithWrap(false),
		)
		__tui_2.AddChild(__tui_13)
	} else if client := activityClientEvidence(row); showClient && client != "" {
		__tui_14 := tui.New(
			tui.WithText(client),
			tui.WithWidth(22),
			tui.WithFlexShrink(5),
			tui.WithMinWidth(0),
			tui.WithWrap(false),
			tui.WithTruncate(true),
			tui.WithOverflow(tui.OverflowHidden),
		)
		__tui_2.AddChild(__tui_14)
	}
	__tui_15 := tui.New(
		tui.WithWidth(2),
		tui.WithFlexShrink(0),
	)
	__tui_2.AddChild(__tui_15)
	__tui_16 := tui.New(
		tui.WithText(activityStatusLabel(row)),
		tui.WithWidth(3),
		tui.WithFlexShrink(0),
		tui.WithWrap(false),
		tui.WithTruncate(true),
		tui.WithOverflow(tui.OverflowHidden),
	)
	__tui_2.AddChild(__tui_16)
	__tui_17 := tui.New(
		tui.WithWidth(1),
		tui.WithFlexShrink(0),
	)
	__tui_2.AddChild(__tui_17)
	__tui_18 := tui.New(
		tui.WithText(activityDurationLabel(row)),
		tui.WithWidth(7),
		tui.WithFlexShrink(0),
		tui.WithWrap(false),
		tui.WithTruncate(true),
		tui.WithOverflow(tui.OverflowHidden),
	)
	__tui_2.AddChild(__tui_18)
	__tui_19 := tui.New(
		tui.WithWidth(3),
		tui.WithFlexShrink(0),
	)
	__tui_2.AddChild(__tui_19)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ActivityRowView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}

type ActivityColumnsView struct {
	Root      *tui.Element
	watchers  []tui.Watcher
	bindApp   func(*tui.App)
	unbindApp func()
}

func (v *ActivityColumnsView) UnbindApp() {
	if v.unbindApp != nil {
		v.unbindApp()
	}
}

func (v *ActivityColumnsView) GetRoot() *tui.Element { return v.Root }

func (v *ActivityColumnsView) GetWatchers() []tui.Watcher { return v.watchers }

func (v *ActivityColumnsView) Render(app *tui.App) *tui.Element { return v.Root }

func (v *ActivityColumnsView) BindApp(app *tui.App) {
	if v.bindApp != nil {
		v.bindApp(app)
	}
}

func (v *ActivityColumnsView) UpdateProps(fresh tui.Component) {
	f, ok := fresh.(*ActivityColumnsView)
	if !ok {
		return
	}
	v.Root = f.Root
	v.watchers = f.watchers
	v.bindApp = f.bindApp
	v.unbindApp = f.unbindApp
}

var _ tui.AppBinder = (*ActivityColumnsView)(nil)

var _ tui.AppUnbinder = (*ActivityColumnsView)(nil)

var _ tui.PropsUpdater = (*ActivityColumnsView)(nil)

func ActivityColumns(observedAt string, route string, evidence string, status string, duration string) *ActivityColumnsView {
	var view ActivityColumnsView
	var watchers []tui.Watcher

	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexWrap(tui.WrapNone),
		tui.WithWidthPercent(100.00),
	)
	__tui_1 := tui.New(
		tui.WithWidth(5),
		tui.WithFlexShrink(0),
	)
	__tui_0.AddChild(__tui_1)
	__tui_2 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithFlexWrap(tui.WrapNone),
		tui.WithGap(2),
		tui.WithFlexGrow(1), tui.WithFlexShrink(1),
		tui.WithMinWidth(0),
	)
	__tui_3 := tui.New(
		tui.WithText(observedAt),
		tui.WithWidth(8),
		tui.WithFlexShrink(0),
		tui.WithWrap(false),
		tui.WithTruncate(true),
		tui.WithOverflow(tui.OverflowHidden),
	)
	__tui_2.AddChild(__tui_3)
	__tui_4 := tui.New(
		tui.WithText(route),
		tui.WithWidth(18),
		tui.WithFlexShrink(0),
		tui.WithMinWidth(0),
		tui.WithWrap(false),
		tui.WithTruncate(true),
		tui.WithOverflow(tui.OverflowHidden),
	)
	__tui_2.AddChild(__tui_4)
	__tui_5 := tui.New(
		tui.WithText(evidence),
		tui.WithFlexGrow(1),
		tui.WithFlexShrink(1),
		tui.WithMinWidth(0),
		tui.WithWrap(false),
		tui.WithTruncate(true),
		tui.WithOverflow(tui.OverflowHidden),
	)
	__tui_2.AddChild(__tui_5)
	__tui_6 := tui.New(
		tui.WithText(status),
		tui.WithWidth(3),
		tui.WithFlexShrink(0),
		tui.WithWrap(false),
		tui.WithTruncate(true),
		tui.WithOverflow(tui.OverflowHidden),
	)
	__tui_2.AddChild(__tui_6)
	__tui_7 := tui.New(
		tui.WithText(duration),
		tui.WithWidth(7),
		tui.WithFlexShrink(0),
		tui.WithWrap(false),
		tui.WithTruncate(true),
		tui.WithOverflow(tui.OverflowHidden),
	)
	__tui_2.AddChild(__tui_7)
	__tui_8 := tui.New(
		tui.WithWidth(3),
		tui.WithFlexShrink(0),
	)
	__tui_2.AddChild(__tui_8)
	__tui_0.AddChild(__tui_2)

	__bindApp := func(app *tui.App) {
	}

	__unbindApp := func() {
	}

	view = ActivityColumnsView{
		Root:      __tui_0,
		watchers:  watchers,
		bindApp:   __bindApp,
		unbindApp: __unbindApp,
	}
	return &view
}
